### ISSUE TITLE
[threat intelligence]  logs-ti_abusech_latest.dest_threatfox-1 missing event.module field -> Threat Intel IP Match rule not working

### ISSUE THREAD

**Issue by Danouchka** [elastic/integrations#10032]
**Description**
Abuse CH threat intel integration  (2.0.0)  is pulling ip addresses ioc in the data stream logs_ti-abusech.threatfox-default indice 
The transform **logs-ti_abusech.latest_threatfox-default-0.1.0**  is pulling from there the iocs and send them in a destination index named logs-ti_abusech_latest.dest_threatfox-1.
But in this index the field `event.module` is missing and its missing because it's not in the mappings 

**Problem**
 the **Threat Intel IP Match** rule  is looking in  logs_ti-* with the following query : 
 `@timestamp >= "now-30d/d" and event.module:(threatintel or ti_*) and threat.indicator.ip:* and not labels.is_ioc_transform_source:"true"` _and event.category:"threat" and event.kind:"enrichment" and event.type:"indicator"_

As a result, since event.module is missing in the index, no match will be ever done for ip iocs coming from abuse ch threatfox 

Same issues for other transforms below. The event.module field is missing in dest indexes and all **Threat Intel * Math** rules cannot trigger any alerts

- logs-ti_abusech.latest_malwarebazaar-default-0.1.0 
- logs-ti_abusech.latest_malware-default-0.1.0 
- logs-ti_abusech.latest_url-default-0.1.0 
- ...

Many thanks for the correction

**Comment by Danouchka** [comment]
PS: using 8.13.4 on Elastic Cloud

**Comment by Danouchka** [comment]
cc @elastic/security-threat-intelligence  cc @elastic/threat-research-and-detection-engineering

**Comment by kcreddy** [comment]
I was able to replicate this behaviour ( i.e., missing `event.module` inside destination index).

The destination index field `event.module` is defined in https://github.com/elastic/integrations/blob/main/packages/ti_abusech/elasticsearch/transform/latest_threatfox/fields/base-fields.yml#L10-L13.

Mapping difference between [source-index](https://github.com/user-attachments/files/15513157/source-index.json) and [destination-index](https://github.com/user-attachments/files/15513156/destination-index.json) showed some fields missing from destination indices:
```
74,79c75,76
<       "properties": {
<         "is_ioc_transform_source": {
<           "type": "constant_keyword",
<           "value": "true"
<         }
<       }
---
>       "dynamic": true,
>       "type": "object"
429,440d425
<             }
<           }
<         },
<         "feed": {
<           "properties": {
<             "name": {
<               "type": "constant_keyword",
<               "value": "AbuseCH Threat Fox"
<             },
<             "dashboard_id": {
<               "type": "constant_keyword",
<               "value": "ti_abusech-c0d8d1f0-3b20-11ec-ae50-2fdf1e96c6a6"
479,482d463
<         "module": {
<           "type": "constant_keyword",
<           "value": "ti_abusech"
<         },
490,493d470
<         },
<         "dataset": {
<           "type": "constant_keyword",
<           "value": "ti_abusech.threatfox"
497c474,475
<   }
```

Note that, while `is_ioc_transform_source` field is intentionally removed to facilitate IOC expiration, other missing fields were all defined inside the same file https://github.com/elastic/integrations/blob/main/packages/ti_abusech/elasticsearch/transform/latest_threatfox/fields/base-fields.yml.

1. Also noticed that all the fields missing from the destination mapping i.e., `event.module`, `event.dataset`, `threat.feed.name` and `threat.feed.dashboard_id` are of same type `constant_keyword` while they are defined as `keyword` inside ECS. Could this mapping conflict be dropping them?
2. Even though `event.dataset` is missing from mappings, it is present inside the destination index document. The other difference I noticed is that except for `event.dataset`, the 3 other fields namely `event.module`, `threat.feed.name`, and `threat.feed.dashboard_id` were inside `fields` and not inside [`_source`](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html) in the source indices. 

@jsoriano / @andrewkroh Do you think transform is dropping the fields because it doesn't query source index's runtime fields? Is there anyway to mitigate this? I think one way to temporarily fix this is to create an ingest pipeline to add to transform's definition, and I created this PR: https://github.com/elastic/integrations/pull/10042. Please let me know your thoughts.

**Comment by andrewkroh** [comment]
`constant_keyword` fields with a static value in the mapping may optionally include that same value in the `_source`, but it's better to omit the value to save on storage. Elastic Agent happens to be setting some of those fields in the _source (it sets various "dataset" fields), but not all of them.

> @jsoriano / @andrewkroh Do you think transform is dropping these fields because it doesn't query source index's runtime fields?

It's reading the _source which doesn't include the static constant_keyword fields that are only present in the mapping. So it's not dropping them, instead it never saw them.

> Is there anyway to mitigate this?

> other missing fields were all defined inside the same file https://github.com/elastic/integrations/blob/main/packages/ti_abusech/elasticsearch/transform/latest_threatfox/fields/base-fields.yml.

I think you have done the correct thing which is to define the same constant_keyword mappings within the template for the transform index. But when I look at the `logs-ti_abusech.latest_threatfox-template@package` that is installed by TI AbuseCH 2.0.0 under stack 8.13.4, it does not have any of [these fields](https://github.com/elastic/integrations/blob/9ecfa0117812a9900af0237d0f03eb4ba9678d64/packages/ti_abusech/elasticsearch/transform/latest_threatfox/fields/base-fields.yml#L10-L23). **That seems like a bug in Fleet,**  unless there is some good reason that it's not including them in the template.

**Comment by kcreddy** [comment]
> For transforms, tt seems like there is some lack of merging between fields in different files.

Thats what seems to be happening here.

The issue is with how the field mappings are built for the transform. It is fixed in https://github.com/elastic/kibana/pull/177608 which aims at `8.14`. As most `ti_*` packages have `kibana.version` constrained to `^8.12.0`, a temporary fix could be made moving all fields having same prefix into same file. 

For AbuseCH, this would mean moving all the 4 fields `event.module`, `event.dataset`, `threat.feed.name`, and `threat.feed.dashboard_id` into `ecs.yml` which already has `event.*` and `threat.*` fields. Created https://github.com/elastic/integrations/pull/10049 for having this fix. 
@andrewkroh feel free to review/let me know your thoughts on this temporary fix. I can replicate this for other `ti_*` packages.

**Comment by kcreddy** [comment]
Fixed by https://github.com/elastic/integrations/pull/10049

Also another bug was identified in `malware` datastream, linking here: https://github.com/elastic/kibana/issues/184759.
