### ISSUE TITLE
No Information is provided for data events collection for rest API on the System integration Overview page

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#1013]
While performing testing for system Package 12.3 on 7.13Snapshot build, we have observed that new logs collection sub-tab is added to system integration related to Rest API. Screenshot is provided here for reference:
 
![image](https://user-images.githubusercontent.com/72375798/118994665-261ad580-b9a4-11eb-854a-4a2795f7345d.png)

**Query**
It would be very helpful if anybody could let us know to validate these events. Kindly share document links or PRs if available.

**Comment by fearful-symmetry** [comment]
So, that was added by @marc-gr as part of a splunk input. Alas, I don't have any splunk experience, so I can't say much more.

**Comment by marc-gr** [comment]
@EricDavisX I will prepare a local environment to validate it works and add the screenshots here

**Comment by marc-gr** [comment]
I checked again setting up a new env, and it is working correctly with the experimental input 
![image](https://user-images.githubusercontent.com/15213755/119501675-5e862f00-bd69-11eb-9e0c-44a22335bc44.png)

hope that helps!

**Comment by EricDavisX** [comment]
Thanks Marc, it does help!  

@dikshachauhan-qasource I will recommend we leave this testing for the Engineering team to manage for now.  But before we do that I wish to confirm with the team if this portion of the Integration is not expected to change much?  Also, any quick discussion on how much this feature set is covered with your team's automation systems? 

If nothing else comes, we will expect you can manage any subsequent test needs @marc-gr.  And of course, I am confirming this detail cross-team because it is part of the System Intgration and therefore the Default policy.  But I recognize this isn't turned on itself since it requires more info to connect, I think it is ok if we explicitly don't cover it on the manual side, unless a detail comes up that it is warranted or desired.  Let us know and keep in touch.

**Comment by dikshachauhan-qasource** [comment]
@EricDavisX 

Thanks for the confirmation for now and keeping it out of scope of our testing.

@marc-gr  However, if we ever need to test this in future, we will be requiring related docs/steps so that we can validate it accordingly.

Thanks
QAS

**Comment by EricDavisX** [comment]
I spoke briefly with @dikshachauhan-qasource this morning and if we were more familiar with Splunk it might be clearer.  In re-reviewing the image she attached I think we have all the info we need to test, if we ever wish to.  Diksha, the Endgame Splunk server should be available if we want to try it out, I can fwd you the creds if you don't have them.

The UI in the screenshot says scheme://IP:Port
and that the endpoint is inferred automatically.  So it seems clear enough to me now.

With this I'm closing this out and we can chat off line.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 

We have re-attempted this on released 7.13 Kibana cloud and self managed 7.13 Kibana builds.
We used the Endgame splunk credentials to validate this. However, we are unable to get the desired results.

Further, as discussed on slack we will continue with System third party rest API tests when it will be available in a stable position.

Thanks
QAS
