### ISSUE TITLE
[New Integration] Check Point Harmony Endpoint

### ISSUE THREAD

**Issue by cpascale43** [elastic/integrations#10168]
# Description

Harmony Endpoint is Check Point's endpoint management tool. Users can ingest alerts, log events and audit logs in Elastic to achieve the following use cases:
- Correlate endpoint alerts and events with network traffic, user behavior and other security logs
- Search detailed forensic data to gain insights into the nature and scope of an attack
- Aggregate endpoint alerts to generate compliance reports required by various regulations like GDPR, HIPAA, and PCI

# Dashboard
The dashboard serves as a security summary to gain a snapshot of endpoint compliance, active alerts and security status per endpoint. See: [Introduction to Endpoint Security](https://sc1.checkpoint.com/documents/R80.40/SmartEndpoint_OLH/EN/Topics-EPSG/index.htm?TocPath=Introduction%20to%20Endpoint%20Security%7CManaging%20the%20Security%20of%20Users%2C%20Not%20Just%20Machines%20%7C_____0#Centralized_Monitoring) for a full overview of the solution and example visualization, linked below.

### <img width="1647" alt="Screenshot 2024-06-17 at 2 35 57 PM" src="https://github.com/elastic/integrations/assets/52431501/38e0c7f6-dc96-4ac3-939f-8d9b28f5c8b5">
- Pie chart or donut chart showing the overall security status of endpoints (aligned, warnings, violations) similar to this image 
- List or table view of active alerts categorized by type (expired certificates, compliance warnings, deployment errors, malware infections) as shown
- Table view or log stream visualization displaying user activity logs with details like source IP, destination IP, action taken (accept/reject), policy rule, etc.

# Architecture
Check Point exposes endpoint data via the following APIs:
- Endpoint security events and alerts: Referred to as "events" and "incidents" in the [Infinity Events API](https://app.swaggerhub.com/apis-docs/Check-Point/infinity-events-api/1.0.0)
-  [Harmony Endpoint Management API](https://app.swaggerhub.com/apis/Check-Point/web-mgmt-external-api-production/1.9.212#/) enables programmatic management of endpoint assets and response to endpoint security incidents

Check Point also recommends the use of [Event Forwarding](https://sc1.checkpoint.com/documents/Infinity_Portal/WebAdminGuides/EN/Infinity-Portal-Admin-Guide/Content/Topics-Infinity-Portal/Event-Forwarding.htm) to export Infinity Portal data to a SIEM over syslog.

Duplicate issue: https://github.com/elastic/integrations/issues/8606

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists, [useful guidelines](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md) to follow
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

**Comment by chrisberkhout** [comment]
Here I expand on the information in the Architecture section above and discuss the WIP PR, to help answer the questions:
- Where are we getting the data?
- Is it the right data?

---

The [Harmony Endpoint Management API](https://app.swaggerhub.com/apis/Check-Point/web-mgmt-external-api-production/1.9.212#/) does seem to be mainly for actions such as policy management and remediation and response. It does have endpoints for fetching IOCs, and vulnerabilities from the posture management feature.

**➛ This is not the source for the "alerts, log events and audit logs" that we want.**

---

The [Infinity Events API](https://app.swaggerhub.com/apis-docs/Check-Point/infinity-events-api/1.0.0) provides a unified interface to search security event logs for these Check Point products:
- Harmony Connect
- **Harmony Endpoint**
- Harmony Mobile
- Harmony Email & Collaboration
- Harmony Browse
- Quantum Security Management
- Quantum Spark Management
- CloudGuard WAF
- Quantum Self-Hosted Management

**➛ This does have "alerts, log events and audit logs" for Harmony Endpoint, as well data for many other products.**

Although the same API can provide a wider range of data, I think it's best to limit the scope to Harmony Endpoint, at least initially. It would be a significantly larger project to map data for all products covered by the Infinity Events API.

---

Using [Event Forwarding](https://sc1.checkpoint.com/documents/Infinity_Portal/WebAdminGuides/EN/Infinity-Portal-Admin-Guide/Content/Topics-Infinity-Portal/Event-Forwarding.htm) to export Infinity Portal data seems to be a way to get the same Infinity Events data via the `syslog` protocol.

**➛ We prefer outbound requests for JSON data rather than incoming requests with `syslog` data.**

---

As of 2024-09-20, the WIP [PR](https://github.com/elastic/integrations/pull/10780) uses the Infinity Events API, and requests specific data.

Requests are limited to Harmony Endpoint data by setting `"cloudService": "Harmony Endpoint"`.
Each request also filters for a specific data type within Harmony Endpoint using a filter. There are separate data streams for each type of data:

| Data stream | Product/blade filter |
|---|---|
| `threatextraction` | `"filter": "product:\"Threat Extraction\" AND NOT event_type:\"TEX Info Event\""` |
| `forensics` | `"filter": "product:\"Forensics\""` |
| `zerophishing` | `"filter": "product:\"Zero Phishing\""` |
| `threatemulation` | `"filter": "product:\"Threat Emulation\" AND NOT event_type:\"TE Info Event\""` |
| `antimalware` | `"filter": "product:\"Anti-Malware\""` |
| `antibot` | `"filter": "product:\"Anti-Bot\""` |
| `urlfiltering` | `"filter": "product:\"URL Filtering\""` |


The API documentation does not list available values for the `product` field.

In [Harmony Endpoint EPMaaS Administration Guide > Introduction to Harmony Endpoint EPMaas](https://sc1.checkpoint.com/documents/Infinity_Portal/WebAdminGuides/EN/Harmony-Endpoint-Admin-Guide/Topics-HEP/Query-Language-Overview.htm#Field_Keywords), there is a list of "components" supported by Harmony Endpoint:

- Threat Prevention
- Data Protection
- Media Encryption & Port Protection
- Firewall
- Application Control
- Developer Protection
- Compliance
- Software Deployment

In [Harmony Endpoint EPMaaS Administration Guide > Query Language Overview > Field Keywords](https://sc1.checkpoint.com/documents/Infinity_Portal/WebAdminGuides/EN/Harmony-Endpoint-Admin-Guide/Topics-HEP/Query-Language-Overview.htm#Field_Keywords), `product` is shown as an alias of `blade`. Software Blades are described as:

> Specific security solution (module): (1) On a Security Gateway, each Software Blade inspects specific characteristics of the traffic (2) On a Management Server, each Software Blade enables different management capabilities.

The Harmony Endpoint Management API documentation contains schemas for [`BladeFamily` and `LegacyBladeFamily`](https://app.swaggerhub.com/apis/Check-Point/web-mgmt-external-api-production/1.9.212#/BladeFamily), as follows:

```yaml
    BladeFamily:
      enum:
      - "General Settings"
      - "Threat Prevention"
      - "Data Protection"
      - "OneCheck"
      - "Deployment"
      - "Remote Access VPN"
      - "Capsule Docs"
      - "Access"
      - "Agent Settings"
      type: "string"
    LegacyBladeFamily:
      enum:
      - "Anti Bot"
      - "Anti Malware"
      - "Threat Emulation"
      - "Forensics"
      - "Full Disk Encryption"
      - "Full Disk Encryption Global"
      - "OneCheck"
      - "Common Client Settings"
      - "Deployment"
      - "EncryptedAccessRules"
      - "VPN"
      - "Capsule Docs"
      - "Media Encryption"
      - "Firewall"
      - "Access Zones"
      - "Application Control"
      - "Compliance"
      type: "string"
```

The existence of an certain blade does not necessarily mean there will be events for it in the Infinity Events API.

**Comment by chrisberkhout** [comment]
@cpascale43 @jamiehynds Above I've gathered together all the information I could find regarding scope/coverage. In my PR review I've asked Gavs to comment on whether they consider it complete or not. Please let me know if you have any thoughts or information about this. Since documentation is limited it may be a matter of gathering user feedback and adding more data as we discover it.

**Comment by chrisberkhout** [comment]
Information from @gauravneelwarna:

> > Do you think we already have good coverage with these data streams or are there more to add?
> > Is there any extra information that we need to answer that question?
>
> Yes, the summary is comprehensive and covers all the points we've identified about Harmony Endpoint so far.
> 
> We've achieved good coverage by creating as many events as possible through various activities on a managed Windows endpoint. While we may have missed some scenarios—such as ransomware-related events—due to the impossibility of safely triggering them, we can always add these in the future when we encounter real-world samples.

I'm happy with this coverage. Do you agree @cpascale43, @jamiehynds?

**Comment by cpascale43** [comment]
Agreed for now @chrisberkhout and @gaurav-elastic, we can always add other datastreams as new ones are requested.

**Comment by gaurav-elastic** [comment]
> Agreed for now [@chrisberkhout](https://github.com/chrisberkhout) and [@gaurav-elastic](https://github.com/gaurav-elastic), we can always add other datastreams as new ones are requested.

Hey, guess you meant to tag @gauravneelwarna (although I can't find his profile in the dropdown now)
