### ISSUE TITLE
[Crowdstrike]Investigate potential support for Event Streaming API in Crowdstrike

### ISSUE THREAD

**Issue by narph** [elastic/integrations#10262]
Meta issue https://github.com/elastic/integrations/issues/9082
Create proposal/investigation result doc for potential custom input.

**Comment by efd6** [comment]
# Proposed approach

The Crowdstrike streaming API operates by allowing the client to start a long-running chunked transfer encoding GET request to the API endpoint. This allows the client to operate on events as they arrive rather than waiting for the request to complete, potentially significantly after the request is made. This would potentially entail buffering a significant number of events if the request the stream is busy.

We already have an input that has a similar behaviour, the websocket input. The architecture of this input is an initial, optional, preparatory phase that collects information from the state store and allows conditioning of the endpoint URL base on stored cursor values, an initial triggering request to the API endpoint to start the websocket stream, and a main loop that receives, processes and publishes the events. This can be conceptually abstracted into an interface type with a setup constructor and a single `FollowStream` method.

```
// NewStreamFollower performs environment construction including CEL
// program and regexp compilation, and input metrics set-up.
func NewStreamFollower(ctx context.Context, id string, cfg config, pub inputcursor.Publisher, log *logp.Logger) (StreamFollower, error)
```

At this stage the stream has not been initiated; this happens with the `FollowStream` method, a `context.Context`-cancellable blocking method that runs until the stream ends or the context is cancelled.
```
type StreamFollower interface {
	FollowStream(context.Context) error
}
```

`FollowStream` would trigger the stream, in the case of a websocket stream this would be the initial dial, followed by a loop receiving the events on the socket, processing them with the stored CEL program and publishing on the provided `inputcursor.Publisher`.

Integrating the Crowdstrike streaming API into this architecture would require minor changes to the `NewStreamFollower` constructor that would allow it to return different concrete types depending on the config's URL scheme; a `ws` scheme would return the current websocket implementation as describe above, while an `http`/`https` scheme would return a streaming GET type with the following `FollowStream` implementation.

The `FollowStream` runs a loop that repeatedly makes GET stream refresh calls and then consumes the incoming response chunks with a streaming JSON decoder (an example of an implementation for this is available in the [encoding/json godoc](https://pkg.go.dev/encoding/json#example-Decoder.Decode-Stream)), continuing the outer loop when exhausted. The actual implementation of this would require an `io.Reader` implementation that wraps the GET/chunk read operations into a single `Read` method to allow the `json.Decoder` to be oblivious to potential object splits over refreshes. There may be a requirement to allow back communication between the decoder loop and the `io.Reader`'s concrete implementation to allow URL changes; this is yet to be determined.

# Confusions

The current websocket input named entirely reasonably, "websocket", if the input is generalised to other streaming mechanisms, the name should be changed, probably to "streaming", to avoid confusion. This would have an impact on downstream users, including any integrations that current make use of it; it does not look like there are any in our catalogue, so this may not be an issue. Renaming the input can be papered over by adding an alias "websocket" to the new "streaming" input (or if required, the other way around). If there is more than one name to reach the input, it may be worth including a check in the `NewStreamFollower` to ensure that the scheme matches the input name that the input was reached by.

/cc @ShourieG @narph @andrewkroh

**Comment by ShourieG** [comment]
So we currently have the proof point integration under dev by Crest and it would be ready soon, also the generic websocket integration which is undergoing final fixes before a pr merge. This new rework won't be out till 8.16 but by that timeline we would already have 2 integrations leveraging the current input and could be potentially used by users. This rework seems like the right approach so we need to decide if we want to hold back those integrations for now or not. cc: @jamiehynds.

**Comment by andrewkroh** [comment]
The input can be aliased to keep existing `websocket` configurations working. Within Filebeat the input can be registered under two different plugins (each with unique names). And for Agent, we need to update the [agentbeat spec file](https://github.com/elastic/beats/blob/main/x-pack/agentbeat/agentbeat.spec.yml) to declare the new input name.

**Comment by narph** [comment]
direction defined, implementation in https://github.com/elastic/beats/issues/40264
