### ISSUE TITLE
[fortinet_fortigate] Adjust firewall field names to match ECS guidelines

### ISSUE THREAD

**Issue by cpascale43** [elastic/integrations#10475]
The [Fortigate integration](https://www.elastic.co/docs/current/integrations/fortinet_fortigate) contains some fields that do not match ECS naming conventions. These use a dash instead of an underscore, as documented in the ECS [guidelines](https://www.elastic.co/guide/en/ecs/current/ecs-guidelines.html#_guidelines_for_field_names):

`fortinet.firewall.app-type` should be `fortinet.firewall.app_type`
`fortinet.firewall.cert-type` should be `fortinet.firewall.cert_type`
`fortinet.firewall.ha-prio` should be `fortinet.firewall.ha_prio`
`fortinet.firewall.monitor-name` should be `fortinet.firewall.monitor_name`
`fortinet.firewall.monitor-type` should be `fortinet.firewall.monitor_type`

Raised here: https://github.com/elastic/enhancements/issues/22139

**Comment by narph** [comment]
@cpascale43 , fortinet integrations belong to @elastic/sec-deployment-and-devices, https://github.com/elastic/integrations/blob/main/.github/CODEOWNERS

**Comment by aleksmaus** [comment]
@qcorporation are we doing this?
As far as I understood from the previous conversation https://github.com/elastic/enhancements/issues/22139 there are lots of integrations that do not change the original field names, and keep them as is (with dashes), since they are not the part of ECS. 
Are we changing all that in all of the integrations or just these few specific fields or just all the fields with dashes in the particular integration?

I tend to agree with @andrewkroh point that we should leave them as is, since this way they be easily found in the original log format documentation such as (for app-type)
https://docs.fortinet.com/index.php/document/fortigate/6.2.3/fortios-log-message-reference/65532

**Comment by qcorporation** [comment]
@aleksmaus - I also tend to agree with @andrewkroh as well - it looks like the original enhancement was closed by originator of this ticket. @cpascale43 I'm assuming you agree with the assessment.

Thanks, @aleksmaus, for bringing this up - I wasn't aware of the decision made by that enhancement request.
@cpascale43 if you fully agree please close the ticket.

> [@qcorporation](https://github.com/qcorporation) are we doing this? As far as I understood from the previous conversation [elastic/enhancements#22139](https://github.com/elastic/enhancements/issues/22139) there are lots of integrations that do not change the original field names, and keep them as is (with dashes), since they are not the part of ECS. Are we changing all that in all of the integrations or just these few specific fields or just all the fields with dashes in the particular integration?
> 
> I tend to agree with [@andrewkroh](https://github.com/andrewkroh) point that we should leave them as is, since this way they be easily found in the original log format documentation such as (for app-type) https://docs.fortinet.com/index.php/document/fortigate/6.2.3/fortios-log-message-reference/65532
