### ISSUE TITLE
[O11y][AWS] Need to do analysis on dashboard panels

### ISSUE THREAD

**Issue by harnish-elastic** [elastic/integrations#10695]
The error count, total count, and throttled count appear with decimal places. Is there any issue with the formula? Need to do further analysis.

<img width="1249" alt="image" src="https://github.com/user-attachments/assets/819d6422-a77a-4675-b9b1-7a542513438c">

**Comment by anil-elastic** [comment]
Hi @agithomas 

Regarding the Decimal values:

1. **4xx and 5xx Errors**: These errors are considered as average values in s3_request.
2. **Cloudwatch Lambda**: Lambda _Errors, Throttles and Invocations_ are defined as average. So, the values are shows on the UI in the decimal.


These are expected behavior if you want then I can make it to show in Integer values.

**Comment by agithomas** [comment]
Going with the above-mentioned explanation, i guess, it would be best to change the title of the panel to `HTTP 4xx errors(Avg)` and  `HTTP 5xx errors (Avg)` 

This task is added to the backlog for consideration in the upcoming sprints, after review.

**Comment by agithomas** [comment]
@lalit-satapathy, you may review and prioritise.
