### ISSUE TITLE
Testing: use test logs to verify ingest pipeline

### ISSUE THREAD

**Issue by mtojek** [elastic/integrations#14]
Use test logs to verify integration's ingest pipeline.

From developer perspective

The command `mage test` or `PACKAGES=aws mage test` uses a tool which performs the following steps:
1. Render/adapt pipelines if necessary (substitution for Kibana).
2. Push temporary pipelines to the Elasticsearch instance.
3. Push test logs to the Elasticsearch instance.
4. Fetch generated logs from the Elasticsearch.
5. Compare generated logs with expected output.
5. Clean temporary pipelines.

**Comment by mtojek** [comment]
@skh Shall I ask you to respond to this question?

Re 1: what modifications does Kibana apply to the ingest pipeline? Let's say I need to apply same modifications and install the pipeline in ES manually.

**Comment by skh** [comment]
IngestManager / EPM replaces `'{{IngestPipeline "some-pipeline" }}' with `"PACKAGEPREFIX-some-pipeline"`.

`PACKAGEPREFIX` will look like: `"logs-PACKAGE.DATASET-VERSION"`.

We also rename the referenced pipeline before installation so the name matches.

**Comment by mtojek** [comment]
Thank you, @skh !

**Comment by exekias** [comment]
From my experience, mage is not a great tool for this for the following reason: mage belongs in a main directory, so you need to run it form there, because of that, you add parameters to tell mage what integration to look into. The list of parameters tends to grow and it is not really usable, as they are not passed as flags that you can document.

I'm fine with this as a PoC, but in the longer run, wow about creating our own tool that can run inside an integration dir? Only minded to work on a single integration, able to run tests and also help on the development

**Comment by mtojek** [comment]
> I'm fine with this as a PoC, but in the longer run, wow about creating our own tool that can run inside an integration dir? Only minded to work on a single integration, able to run tests and also help on the development

Actually we a chat about it with @ruflin to use a dedicated tool that you can use in different repos (`integrations`, `package-storage`). I'm happy to follow this path as I'm not a fan of mage :)

**Comment by ruflin** [comment]
I assume your step 3 will get a bit more complex. It will require the agent to be run with the stream template and fill in the config variables, as otherwise you will not know how to read and process the log locally. This is basically the code in https://github.com/elastic/beats/blob/master/filebeat/tests/system/test_modules.py but finally implemented in Golang.

**Comment by mtojek** [comment]
I think we have a plan for this so resolving.
