### ISSUE TITLE
[Bug] Elastic Agent Filebeat Data Stream incorrectly maps `source` field as a `keyword` rather than an `object`

### ISSUE THREAD

**Issue by BenB196** [elastic/integrations#1573]
Elastic Agent 7.14.0 Filebeat Data Stream incorrectly maps the `source` field as a `keyword`, rather than an `object` as specified by [ECS](https://www.elastic.co/guide/en/ecs/1.11/ecs-source.html)

This is causing an issue in Kibana as its causing a mapping conflict within the Kibana Index Pattern `logs-*`.

Example:

`GET /.ds-logs-elastic_agent.filebeat-test-2021.08.25-000001/_mapping/field/source`

```json
{
  ".ds-logs-elastic_agent.filebeat-test-2021.08.25-000001" : {
    "mappings" : {
      "source" : {
        "full_name" : "source",
        "mapping" : {
          "source" : {
            "type" : "keyword",
            "ignore_above" : 1024
          }
        }
      }
    }
  }
}
```

**Comment by legoguy1000** [comment]
It appears there is no `source.*` fields defined in the package https://github.com/elastic/integrations/blob/master/packages/elastic_agent/data_stream/filebeat_logs/fields/ecs.yml

**Comment by rroemer** [comment]
I have the same issue. In my case I think the problem is that the logger input.harvester prints log with a file log path in the source fields. Heres a sample document:
`{
  "_index": ".ds-logs-elastic_agent.filebeat-default-2021.08.28-000006",
  "_type": "_doc",
  "_id": "0qN96XsBgvuFJGcvbN-u",
  "_score": 1,
  "_source": {
    "@timestamp": "2021-09-15T12:45:11.994Z",
    "log.logger": "input.harvester",
    "old_os_id": "1573363-64769",
    "event": {
      "dataset": "elastic_agent.filebeat"
    },
    "host": {
      "name": "<REMOVED>",
      "mac": [<REMOVED>
      ],
      "hostname": "<REMOVED>",
      "architecture": "x86_64",
      "os": {
        "codename": "focal",
        "type": "linux",
        "platform": "ubuntu",
        "version": "20.04.2 LTS (Focal Fossa)",
        "family": "debian",
        "name": "Ubuntu",
        "kernel": "5.4.0-77-generic"
      },
      "id": "<REMOVED>",
      "containerized": false,
      "ip": [<REMOVED>
      ]
    },
    "agent": {
      "ephemeral_id": "<REMOVED>",
      "id": "<REMOVED>",
      "name": "relation.cegohost.dk",
      "type": "filebeat",
      "version": "7.14.1",
      "hostname": "<REMOVED>"
    },
    "input_id": "eead62b6-cc15-459c-8ce2-4e769db7d797",
    "state_id": "native::1573363-64769",
    "finished": false,
    "data_stream": {
      "type": "logs",
      "dataset": "elastic_agent.filebeat",
      "namespace": "default"
    },
    "old_finished": true,
    "old_source": "/var/log/syslog",
    "log.origin": {
      "file.name": "log/harvester.go",
      "file.line": 309
    },
    "service.name": "filebeat",
    "message": "Harvester started for file.",
    "os_id": "<REMOVED>",
    "harvester_id": "<REMOVED>",
    "input": {
      "type": "filestream"
    },
    "log": {
      "path": "/opt/Elastic/Agent/data/elastic-agent-703d58/logs/default/filebeat-json.log",
      "offset": 528
    },
    "log.level": "info",
    "ecs": {
      "version": "1.10.0"
    },
    "source": "/var/log/syslog",
    "elastic_agent": {
      "snapshot": false,
      "version": "7.14.1",
      "id": "<REMOVED>"
    }
  },
  "fields": {
    "elastic_agent.version": [
      "7.14.1"
    ],
    "os_id": [
      "1573363-64769"
    ],
    "host.hostname": [
      "<REMOVED>"
    ],
    "source": [
      "/var/log/syslog"
    ],
    "host.mac": [<REMOVED>
    ],
    "log.logger": [
      "input.harvester"
    ],
    "host.ip": [<REMOVED>
    ],
    "agent.type": [
      "filebeat"
    ],
    "host.os.version": [
      "20.04.2 LTS (Focal Fossa)"
    ],
    "host.os.kernel": [
      "5.4.0-77-generic"
    ],
    "host.os.name": [
      "Ubuntu"
    ],
    "log.level": [
      "info"
    ],
    "agent.name": [
      "<REMOVED>"
    ],
    "state_id": [
      "native::1573363-64769"
    ],
    "elastic_agent.snapshot": [
      false
    ],
    "host.name": [
      "r<REMOVED>"
    ],
    "host.id": [
      "<REMOVED>"
    ],
    "log.path": [
      "/opt/Elastic/Agent/data/elastic-agent-703d58/logs/default/filebeat-json.log"
    ],
    "old_source": [
      "/var/log/syslog"
    ],
    "log.origin.file.line": [
      309
    ],
    "host.os.type": [
      "linux"
    ],
    "service.name": [
      "filebeat"
    ],
    "elastic_agent.id": [
      "<REMOVED>"
    ],
    "data_stream.namespace": [
      "default"
    ],
    "harvester_id": [
      "<REMOVED>"
    ],
    "host.os.codename": [
      "focal"
    ],
    "input.type": [
      "filestream"
    ],
    "finished": [
      false
    ],
    "log.offset": [
      528
    ],
    "agent.hostname": [
      "<REMOVED>"
    ],
    "message": [
      "Harvester started for file."
    ],
    "data_stream.type": [
      "logs"
    ],
    "host.architecture": [
      "x86_64"
    ],
    "log.origin.file.name": [
      "log/harvester.go"
    ],
    "@timestamp": [
      "2021-09-15T12:45:11.994Z"
    ],
    "agent.id": [
      "<REMOVED>"
    ],
    "host.containerized": [
      false
    ],
    "host.os.platform": [
      "ubuntu"
    ],
    "ecs.version": [
      "1.10.0"
    ],
    "old_os_id": [
      "<REMOVED>"
    ],
    "data_stream.dataset": [
      "elastic_agent.filebeat"
    ],
    "agent.ephemeral_id": [
      "<REMOVED>"
    ],
    "agent.version": [
      "7.14.1"
    ],
    "old_finished": [
      true
    ],
    "host.os.family": [
      "debian"
    ],
    "input_id": [
      "<REMOVED>"
    ],
    "event.dataset": [
      "elastic_agent.filebeat"
    ]
  }
}`

**Comment by rroemer** [comment]
I have the same issue. In my case I think the problem is that the logger input.harvester prints log with a file log path in the source fields. Heres a sample document:
`{ "_index": ".ds-logs-elastic_agent.filebeat-default-2021.08.28-000006", "_type": "_doc", "_id": "0qN96XsBgvuFJGcvbN-u", "_score": 1, "_source": { "@timestamp": "2021-09-15T12:45:11.994Z", "log.logger": "input.harvester", "old_os_id": "1573363-64769", "event": { "dataset": "elastic_agent.filebeat" }, "host": { "name": "<REMOVED>", "mac": ["<REMOVED>" ], "hostname": "<REMOVED>", "architecture": "x86_64", "os": { "codename": "focal", "type": "linux", "platform": "ubuntu", "version": "20.04.2 LTS (Focal Fossa)", "family": "debian", "name": "Ubuntu", "kernel": "5.4.0-77-generic" }, "id": "<REMOVED>", "containerized": false, "ip": ["<REMOVED>"] }, "agent": { "ephemeral_id": "<REMOVED>", "id": "<REMOVED>", "name": "<REMOVED>", "type": "filebeat", "version": "7.14.1", "hostname": "<REMOVED>" }, "input_id": "eead62b6-cc15-459c-8ce2-4e769db7d797", "state_id": "native::1573363-64769", "finished": false, "data_stream": { "type": "logs", "dataset": "elastic_agent.filebeat", "namespace": "default" }, "old_finished": true, "old_source": "/var/log/syslog", "log.origin": { "file.name": "log/harvester.go", "file.line": 309 }, "service.name": "filebeat", "message": "Harvester started for file.", "os_id": "<REMOVED>", "harvester_id": "<REMOVED>", "input": { "type": "filestream" }, "log": { "path": "/opt/Elastic/Agent/data/elastic-agent-703d58/logs/default/filebeat-json.log", "offset": 528 }, "log.level": "info", "ecs": { "version": "1.10.0" }, "source": "/var/log/syslog", "elastic_agent": { "snapshot": false, "version": "7.14.1", "id": "<REMOVED>" } }, "fields": { "elastic_agent.version": [ "7.14.1" ], "os_id": [ "1573363-64769" ], "host.hostname": [ "<REMOVED>" ], "source": [ "/var/log/syslog" ], "host.mac": ["<REMOVED>" ], "log.logger": [ "input.harvester" ], "host.ip": ["<REMOVED>" ], "agent.type": [ "filebeat" ], "host.os.version": [ "20.04.2 LTS (Focal Fossa)" ], "host.os.kernel": [ "5.4.0-77-generic" ], "host.os.name": [ "Ubuntu" ], "log.level": [ "info" ], "agent.name": [ "<REMOVED>" ], "state_id": [ "native::1573363-64769" ], "elastic_agent.snapshot": [ false ], "host.name": [ "r<REMOVED>" ], "host.id": [ "<REMOVED>" ], "log.path": [ "/opt/Elastic/Agent/data/elastic-agent-703d58/logs/default/filebeat-json.log" ], "old_source": [ "/var/log/syslog" ], "log.origin.file.line": [ 309 ], "host.os.type": [ "linux" ], "service.name": [ "filebeat" ], "elastic_agent.id": [ "<REMOVED>" ], "data_stream.namespace": [ "default" ], "harvester_id": [ "<REMOVED>" ], "host.os.codename": [ "focal" ], "input.type": [ "filestream" ], "finished": [ false ], "log.offset": [ 528 ], "agent.hostname": [ "<REMOVED>" ], "message": [ "Harvester started for file." ], "data_stream.type": [ "logs" ], "host.architecture": [ "x86_64" ], "log.origin.file.name": [ "log/harvester.go" ], "@timestamp": [ "2021-09-15T12:45:11.994Z" ], "agent.id": [ "<REMOVED>" ], "host.containerized": [ false ], "host.os.platform": [ "ubuntu" ], "ecs.version": [ "1.10.0" ], "old_os_id": [ "<REMOVED>" ], "data_stream.dataset": [ "elastic_agent.filebeat" ], "agent.ephemeral_id": [ "<REMOVED>" ], "agent.version": [ "7.14.1" ], "old_finished": [ true ], "host.os.family": [ "debian" ], "input_id": [ "<REMOVED>" ], "event.dataset": [ "elastic_agent.filebeat" ] } }`

And here is what a similar document looks like in the elastic agent log on the server
`{ "log.level": "info", "@timestamp": "2021-09-15T13:00:09.314Z", "log.logger": "input.harvester", "log.origin": { "file.name": "log/harvester.go", "file.line": 340 }, "message": "File is inactive. Closing because close_inactive of 5m0s reached.", "service.name": "filebeat", "input_id": "b06a55c6-dc37-40ec-b5b6-e0c3e4e2f9cf", "source": "/var/log/syslog", "state_id": "native::10748194-64770", "finished": false, "os_id": "10748194-64770", "old_source": "/var/log/syslog", "old_finished": true, "old_os_id": "10748194-64770", "harvester_id": "c8c2cf1c-fb6e-403d-aacd-11230ac236ef", "ecs.version": "1.6.0" }`
