### ISSUE TITLE
Move all AWS, GCP & Azure datasets to use the generic input

### ISSUE THREAD

**Issue by exekias** [elastic/integrations#173]
We now have a generic metrics input for all cloud providers. AWS & Azure has a mix of metricsets based on them, with some others (the older ones) written in Go, with a different format in the output. GCP doesn't' have this inconsistency, and all its metricsets are based in lightweight modules.

The migration to integrations is a good opportunity to revisit this situation, as it opens the door to do breaking changes now, instead of waiting for 8.0.

**Proposal**

For AWS/Azure integrations, do not copy the old metricsets that are written in Go, but redo them based on the generic input.

A few questions we would need to answer:

- What is the extra data that we are collecting in those metricsets that doesnt' come from cloudwatch/azure monitor? How important is it, can we collect it in some other way?
- Currently metrics UI makes use of some AWS metrics, what would we need to do to maintain compatibility?

**Comment by exekias** [comment]
@kaiyan-sheng @narph would love your thoughts here

**Comment by kaiyan-sheng** [comment]
Thanks Carlos for the initiation! Here are my thoughts on AWS:

> * What is the extra data that we are collecting in those metricsets that doesnt' come from cloudwatch/azure monitor? How important is it, can we collect it in some other way?

For `aws` module, we have `ec2`, `rds`, `s3_daily_storage`, `s3_request` and `sqs` metricsets not using light weight module. Extra data collected for `ec2` is information from [DescribeInstances API](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html) such as `monitoring.state`, `state.code`, `state.name` and etc.

Extra data collected for `rds` is from [DescribeDBInstances API](https://docs.aws.amazon.com/cli/latest/reference/rds/describe-db-instances.html), such as `DBInstanceClass`, `DBInstanceStatus `.

I believe they are important information as meta data. What we can do is to add a function into `cloudwatch` to collect metadata for specific services, similar to what googlecloud stackdriver/metrics is doing: https://github.com/elastic/beats/blob/master/x-pack/metricbeat/module/googlecloud/stackdriver/metadata_services.go

> * Currently metrics UI makes use of some AWS metrics, what would we need to do to maintain compatibility?

If we change metrics to use generic input, we also need to update all dashboards to make them work with new metric name. For example, `aws.ec2.cpu.total.pct` would be `aws.ec2.metrics.CPUUtilization.avg`. We need to use alias for all fields in order to make metrics UI still work.

**Comment by exekias** [comment]
> For `aws` module, we have `ec2`, `rds`, `s3_daily_storage`, `s3_request` and `sqs` metricsets not using light weight module. Extra data collected for `ec2` is information from [DescribeInstances API](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html) such as `monitoring.state`, `state.code`, `state.name` and etc.
> 
> Extra data collected for `rds` is from [DescribeDBInstances API](https://docs.aws.amazon.com/cli/latest/reference/rds/describe-db-instances.html), such as `DBInstanceClass`, `DBInstanceStatus `.

SGTM!, we could also consider creating a processor for this (`add_ec2_metadata`?)

> 
> I believe they are important information as meta data. What we can do is to add a function into `cloudwatch` to collect metadata for specific services, similar to what googlecloud stackdriver/metrics is doing: https://github.com/elastic/beats/blob/master/x-pack/metricbeat/module/googlecloud/stackdriver/metadata_services.go
> 
> > * Currently metrics UI makes use of some AWS metrics, what would we need to do to maintain compatibility?
> 
> If we change metrics to use generic input, we also need to update all dashboards to make them work with new metric name. For example, `aws.ec2.cpu.total.pct` would be `aws.ec2.metrics.CPUUtilization.avg`. We need to use alias for all fields in order to make metrics UI still work.

Alias would work, we could also put a pipeline in place to copy over the fields to the names we want

**Comment by kaiyan-sheng** [comment]
Thanks @exekias ! For creating processor, we need `add_ec2_metadata`, `add_rds_metadata`, `add_s3_metadata` and etc for different services. Maybe we can create one called `add_aws_services_metadata` or something for all services in AWS? I haven't looked into processor code yet so not sure if this is a good idea 😄

**Comment by narph** [comment]
in case of Azure:
- users configure an option to select which resources they want to monitor and that can be a resource ID, resource group and type or a resource query.
- to retrieve actual details about these resource (as resource ID (which is needed for the rest of the calls), name etc) we call either List or GET by ID (https://docs.microsoft.com/en-us/rest/api/resources/resources/list) apis 
- not all resources support the namespaces provided so we will have to get the list of supported namespaces (https://docs.microsoft.com/en-us/rest/api/servicebus/namespaces/listbyresourcegroup) in some of the metricsets
- the same goes for the metrics and supported `aggregations`, `timegrain` , `dimensions` so in order to get a better view of supported metrics/aggs/dimensions we call https://docs.microsoft.com/en-us/rest/api/monitor/metricdefinitions/list
- these calls are useful for the GET metrics API (https://docs.microsoft.com/en-us/rest/api/monitor/metrics/list) since it will fail if any of metrics does not support an aggs/dimension/timegrain/namespace provided. Also, we are able to reduce the number of calls by grouping similar metrics knowing their supported properties.
That is where the `refresh_list_interval` comes handy where the previous steps can be `cached`.

**Comment by exekias** [comment]
Thank you @narph @kaiyan-sheng!

I think an enriching processor can be a good option in both cases. In GCP we are doing this directly from the stackdriver metricset, both options look good to me, although the processor may be more reusable, for instance with logs.

++ on adding mapping @narph. I wonder if the `ignore_missing_*` settings should be the default behavior 🤔 

Will have a look to the storage metricset, it sounds like it's complex enough to skip it here

**Comment by narph** [comment]
> ++ on adding mapping @narph. I wonder if the ignore_missing_* settings should be the default behavior 

I disagree, if users enter invalid namespaces and metric names we should consider that as an invalid configuration and allow the user to fix it.
In this special case, users might or might have not enabled the guest metrics so that namespace might be available per specific resource or not.

**Comment by kaiyan-sheng** [comment]
With adding `billing` metricset for both AWS and GCP, these will not be able to use generic input.

**Comment by exekias** [comment]
That makes sense @kaiyan-sheng, these services make use of specific APIs, right?

**Comment by kaiyan-sheng** [comment]
@exekias Yes. AWS billing metricset will now get data not only from CloudWatch but also Cost Explorer. GCP billing is directly making queries to BigQuery data warehouse.

**Comment by kaiyan-sheng** [comment]
I created https://github.com/elastic/beats/issues/21422 to track the work for moving metricsets under AWS module to use generic input.
