### ISSUE TITLE
Network Packet Capture GA Blockers

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#1767]
Our 'Network Packet Capture' experimental integration shipped in 7.15, allowing users to capture network traffic using Elastic Agent, with Packetbeat running under the hood. Before moving the integration to Beta/GA, we will use this meta issue to capture relevant enhancements:

- https://github.com/elastic/integrations/issues/2132
- [Add dashboards to integration](https://github.com/elastic/integrations/issues/2169) (including [new maps](https://github.com/elastic/beats/issues/26015))
- https://github.com/elastic/integrations/issues/2860
- Add option for processors within the integration inline with other integrations (e.g. dropping events)
- Documentation/integration description

**Comment by eric-ooi** [comment]
Any timeline for when the aarch64 flavor of packetbeat will be available?  Just switched out my macOS 8.2 agent to the aarch64 release and noticed it not deploying properly.  Searching through the logs and confirming on the downloads page that it's because packetbeat isn't available for aarch64 yet. :(

**Comment by andrewkroh** [comment]
I tracking for I found for that is in https://github.com/elastic/beats/issues/21855.

**Comment by epixa** [comment]
It looks like the protocol task is done. Is this package ready for GA? @andrewkroh @efd6

**Comment by efd6** [comment]
I'll do that today.

**Comment by efd6** [comment]
Looking through the packetbeat docs we currently don't expose the configurations for `packetbeat.interfaces.*` beyond `file` and `device`. Do we want to expose those (e.g. `type`, `buffer_size_mb`, `snaplen`...)? I think probably not in the first instance since in the context of integrations over a set of hosts managed by fleet they add potential for a bad user experience.

**Comment by efd6** [comment]
@jamiehynds Please take a look at the docs added at #3371.

**Comment by jamiehynds** [comment]
sorry for the delay @efd6 - I just added a comment to expand on the integration description. Otherwise, LGTM.

**Comment by epixa** [comment]
This is now GA

**Comment by Lokey92** [comment]
Was this tested for Windows 10 machines before it became GA?
