### ISSUE TITLE
Document evolution of integration mechanisms

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/integrations#1770]
We moved from Logstash to Beats to Agents for data ingestion into Elasticsearch. Even Elastic folks internally still struggle to understand how these are related and how each of these mechanisms works.

Ask here is to draft and publish a document that describes the evolution of "how" we enable third-party systems to integrate with Elastic.

**Comment by mostlyjason** [comment]
@akshay-saraswat is the goal to talk about the history and evolation, or is it more important to communicate the current state for new and existing users?

**Comment by 111andre111** [comment]
At least from a support perspective it would be good to have a clear documentation over the history, because we are having in support quite a lot of time cases of earlier version too.

However for sure the main concentration still should be the implementation how it's working today, so the former point could be for sure added later on if needed and can be a growing documentation. 👍

**Comment by akshay-saraswat** [comment]
> @akshay-saraswat is the goal to talk about the history and evolation, or is it more important to communicate the current state for new and existing users?

As @111andre111 said, the aim is to remove the confusion associated with the type of integrations we have and actually define what integration means.
