### ISSUE TITLE
Test and verify that Elastic-Agent with k8s and system integrations run on Openshift

### ISSUE THREAD

**Issue by ChrsMark** [elastic/integrations#2065]
We need to verify that both standalone and managed Agent can run properly on Openshift with the proposed manifests. `system` and `kubernetes` packages should be running without a problem.

Please take as an example the work done for Metricbeat/Filebeat: https://github.com/elastic/beats/issues/17516
We can verify this on minishift but running on actual Openshift deployment is recommended.

**Comment by tetianakravchenko** [comment]
Testing environments:
# Use case 1
minishift version:
```
minishift version
minishift v1.34.3+4b58f89
```
minishift started with virtualbox driver, issue - https://github.com/minishift/minishift/issues/3494:
```
minishift start --vm-driver virtualbox
```
(works on virtualbox version 6.1.26)
openshift version:
```
minishift openshift version
openshift v3.11.0+32a500f-598
```
openshift client (installed from https://mirror.openshift.com/pub/openshift-v3/clients/):
```
oc version
oc v3.11.587
kubernetes v1.11.0+d4cacc0
features: Basic-Auth
```
# Standalone elastic-agent
How-to: https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-standalone.html

**Comment by tetianakravchenko** [comment]
# CRC - openshift version 4
crc version:
```
crc version
CodeReady Containers version: 1.37.0+3876d27d
OpenShift version: 4.9.10 (bundle installed at /Applications/CodeReady Containers.app/Contents/Resources/crc_hyperkit_4.9.10.crcbundle)
```
openshift & k8s version:
```
crc start
eval $(crc oc-env)
% oc version
Client Version: 4.9.10
Server Version: 4.9.10
Kubernetes Version: v1.22.3+ffbb954
```
## Managed elastic-agent
How-to: https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-managed-by-fleet.html#running-on-kubernetes-managed-by-fleet

**Comment by ChrsMark** [comment]
Regarding `kube-proxy` there is some feedback at https://github.com/elastic/beats/issues/17863, which proves that it is doable to make `kube-proxy` metricsets/datastream to work with the proper configuration on k8s side. If we verify this we can document the steps required on k8s side and make `kube-proxy` available at Openshift both for Metricbeat and Agent.

**Comment by ChrsMark** [comment]
Thank you @tetianakravchenko ! Do you also plan to update the documentation accordingly? We have this section -> [running-on-kubernetes.html#_red_hat_openshift_configuration](https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-kubernetes.html#_red_hat_openshift_configuration) about Openshift specifics so this would be good fit there I think.

**Comment by tetianakravchenko** [comment]
Openshift on GCP:
errors:
1. Full Node name should be used:
```
error making http request: Get "https://name-openshift-v48hb-worker-b-km2m8:10250/stats/summary": x509: certificate is valid for name-openshift-v48hb-worker-b-km2m8.c.project_name.internal, not name-openshift-v48hb-worker-b-km2m8
```
-> used `'https://${env.NODE_NAME}.c.project_name.internal:10250'`, but it is specific to the GCP I think
2. When used `"https://kube-state-metrics.openshift-monitoring.svc:8443"` as a host for kubernetes.state_* datasets, we might miss some prometheus metrics we rely on due to metric deny list - https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/kube-state-metrics/deployment.yaml#L39-L51
Options here: either path kube-state-metrics deployment of cluster-monitoring-operator or install kube-state-metrics aside of elastic-agent (note: resources name shouldn't overrlap/override with the kube-state-metrics of cluster-monitoring-operator)

3. metrics kubernetes.state_* are collected with gaps:
<img width="2555" alt="Screenshot 2022-01-26 at 19 17 52" src="https://user-images.githubusercontent.com/28299531/151222932-4157219f-86cd-49ba-b33a-df270aa9b8bb.png">

the only errors I see in metricbeat logs:
```
2022-01-26T17:55:24.433Z	ERROR	module/wrapper.go:259	Error fetching data for metricset beat.stats: error making http request: Get "http://unix/stats": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2022-01-26T17:55:24.433Z	ERROR	module/wrapper.go:259	Error fetching data for metricset beat.state: error making http request: Get "http://unix/state": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2022-01-26T17:54:06.328Z	ERROR	module/wrapper.go:259	Error fetching data for metricset http.json: error making http request: Get "http://unix/stats": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2022-01-26T17:55:24.567Z	ERROR	module/wrapper.go:259	Error fetching data for metricset beat.stats: error making http request: Get "http://unix/stats": dial unix /usr/share/elastic-agent/state/data/tmp/default/metricbeat/metricbeat.sock: connect: connection refused
2022-01-26T17:55:24.574Z	ERROR	module/wrapper.go:259	Error fetching data for metricset http.json: error making http request: Get "http://unix/stats": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2022-01-26T17:55:24.575Z	ERROR	module/wrapper.go:259	Error fetching data for metricset beat.state: error making http request: Get "http://unix/state": dial unix /usr/share/elastic-agent/state/data/tmp/default/metricbeat/metricbeat.sock: connect: connection refused
2022-01-26T17:55:24.575Z	ERROR	module/wrapper.go:259	Error fetching data for metricset http.json: error making http request: Get "http://unix/stats": dial unix /usr/share/elastic-agent/state/data/tmp/default/metricbeat/metricbeat.sock: connect: connection refused
```
created an issue for that - https://github.com/elastic/beats/issues/30033

**Comment by mtojek** [comment]
Hey folks! How about adding support for Openshift in elastic-package, similarly to `kind`? Will it help or not really?

**Comment by ChrsMark** [comment]
> Hey folks! How about adding support for Openshift in elastic-package, similarly to `kind`? Will it help or not really?

That would be great! In the past we had thought about supporting Openshift in our CI but in Beats CI it was a bit more complicated. Now with `elastic-package` it should be more straight-forward. I'm wondering if it would make sense to use a local "cluster" or a cloud one on GCP for a more official approach. The second one would be more expensive if the cluster is always up but we can verify this with infra team. I think that ECK team does the same to test the operator.

**Comment by mtojek** [comment]
I created the relevant [issue](https://github.com/elastic/elastic-package/issues/672) and we can take it from there instead of polluting this thread.

**Comment by tetianakravchenko** [comment]
@ChrsMark 
> Do you also plan to update the documentation accordingly? We have this section -> running-on-kubernetes.html#_red_hat_openshift_configuration about Openshift specifics so this would be good fit there I think.

https://github.com/elastic/beats/pull/30054
it seems elastic-agent documentation is in different repo, would it be the proper place - https://github.com/elastic/observability-docs/blob/7.16/docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc ?

**Comment by ChrsMark** [comment]
> @ChrsMark
> 
> > Do you also plan to update the documentation accordingly? We have this section -> running-on-kubernetes.html#_red_hat_openshift_configuration about Openshift specifics so this would be good fit there I think.
> 
> [elastic/beats#30054](https://github.com/elastic/beats/pull/30054) it seems elastic-agent documentation is in different repo, would it be the proper place - https://github.com/elastic/observability-docs/blob/7.16/docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc ? any specific processes here?

That's the correct place for the docs yes. Nothing special there, we mostly update this specific docs so you can just go ahead and open a PR there and ask for a review from our team.

**Comment by tetianakravchenko** [comment]
For future references I will keep installation processes of crc and openshift on gcp in this issue:

## CRC:
1. create a redhat account
2. CRC intalator can be downloaded from https://mirror.openshift.com/pub/openshift-v4/clients/crc/ or from the redhat account.
3. `crc setup`
4. `crc start`
You might need to adjust cpu/memory configuration for crc.

To enable openshift cluster monitoring:
```
crc config set enable-cluster-monitoring true
```

## Openshift on GCP:
use https://github.com/openshift/installer
NOTE: use official openshift-install binary, not the one built from master - in my case worker nodes were not created due to the issue when bootstraping master nodes - some daemonset was crashing.
official openshift-install  can be found in you account https://console.redhat.com/openshift/create, here can be found pull secrets as well.
1. Create a google service account with all the required permissions - https://github.com/openshift/installer/blob/master/docs/user/gcp/iam.md, export this key:
```
export GCLOUD_KEYFILE_JSON=$(pwd)/elastic-obs-integrations-dev-*.json
```
1. Create a folder with the `install-config.yml`:
$ mkdir GCP
$ cat GCP/install-config.yml
```
apiVersion: v1
baseDomain: cf-obs.elastic.dev
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    gcp:
      type: n2-standard-4
  replicas: 4
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    gcp:
      type: n2-standard-4
  replicas: 3
metadata:
  name: tetiana-openshift
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  gcp:
    projectID: elastic-obs-integrations-dev
    region: us-central1
sshKey: ...
pullSecret: ...
```
> Note!: add `pullSecrets` in format `'{"auths":{"cloud.openshift.com":{"auth":...`
add `sshKey in format: `ssh-... ... ` - it is your public ssh key to access created node
full list of settings - [here](https://docs.openshift.com/container-platform/4.7/installing/installing_gcp/installing-gcp-customizations.html#installation-configuration-parameters-required_installing-gcp-customizations)
2. create cluster:
./openshift-install create cluster --dir=./GCP --log-level=debug

It creates 1 bootstrap node, 3 master and 3 worker. If you need for some reason ssh to the nodes - use 
`ssh core@'bootstrap-public-ip'`
3. Check installation progress:
```
oc --kubeconfig=${INSTALL_DIR}/auth/kubeconfig get clusterversion
```
4. destroy:
```
./openshift-install destroy cluster --dir=./GCPobsOCP --log-level=info
```

**Comment by ChrsMark** [comment]
Thanks for working on this @tetianakravchenko! It will help a lot to enhance our coverage and supportability for what's around the corner.

**Comment by Myasnik2000** [comment]
Hey folks, can anyone help me and provide elastic-agents configmap for atlassian integration ?
