### ISSUE TITLE
Discuss the breaking change of kubernetes.namespace in the processor fields

### ISSUE THREAD

**Issue by ChrsMark** [elastic/integrations#2165]
We have a solution in place for the data shipped by the k8s package. But every other data stream will break if the user migrates to 8.0 and was using k8s and there is no migration path at the moment.

_Originally posted by @ruflin in https://github.com/elastic/observability-test-environments/issues/1928#issuecomment-970219578_

cc: @MichaelKatsoulis

**Comment by MichaelKatsoulis** [comment]
>I wonder if we missed here a more fundamental issue. Lets assume someone collecting nginx logs in Kubernetes with a 7.x Elastic Agent and ships data to logs-nginx.access-default. Now this users upgrades to 8.0 and still ships logs to logs-nginx.access-default. The mapping of nginx is still compatible and the new package is installed, but not for the meta data. A rollover would fix the issue but in the worst case scenario, the users has 7.16 and 8.0 Elastic Agents shipping data. What should the user do now? Is there any option in 7.16 to enable the new structure?

@ruflin In order to have a more clear picture of what this scenario is about: 
1. A user has stack version 8.0 but runs agent 7.x on kubernetes with `nginx` integration enabled
2. The data are shipped to `logs-nginx.access-default` index where the mappings for the meta data(added by `add_kubernetes_metadata` processor) have the old types
3. User upgrades agent to 8.0 and `nginx data_stream` still ships data to the same index. For nginx fields everything is fine but the meta data fields are outdated and the data stream fails.

Is my understanding correct?  I am unsure how realistic the scenario is. 
I think that when running on k8s most users will use the container-logs integration to collect their pod logs instead of `nginx access log` as the `access.log` is streamed to stdout when running as container. Same applies for redis server logs. So in that case there is a migration path for the breaking changes. 

Concerning metrics (let's say nginx metrics or redis metrics) I tested it and does not seem that the processor add meta data by default.
Is there something I am missing?

**Comment by ruflin** [comment]
The example you mentioned is correct. For the metrics use case, I'm surprised the k8s metadata is not there because I would assume we need this data too for correlation. 

For nginx logs use case. Ideally even if the container-logs integration is used, logs would be shipping to `nginx.access` dataset and not a generic data stream. The way I would expect it to work is that if lets say a user configured condition based autodiscovery, if the container is nginx the logs are shipped to the nginx.access datastream and also processed. We don't support this from the Fleet UI yet but I expect this to work in standalone mode. In this scenario the conflict happens.

In 6.3 we introduce `host.name` but Logstash used `host` as a keyword. It created a lot of expected but also many unexpected issues which were hunting us for a long time. The problem with `keyword` to `object` is that there is no workaround with alias or similar except an ingest pipeline. Lets take the case where our test cluster was shipping data to `logs-generic-default` and things broke during the migration from 7.16 to 8.0. Were the logs collected in the "ideal" way? Likely no but it caused issues and there is no real workaround except deleting the data or add an ingest pipeline to the data stream.

On my end I have second thoughts if we should do this change in 8.0 the way we planned it so far. Could we find some names where we don't need to convert keyword to object? What alternative solutions do we have? Is there a way that 7.16 and 8.0 can work in parallel? 

I know we all agreed on the change a few weeks ago but I think we should revisit.

**Comment by MichaelKatsoulis** [comment]
>The example you mentioned is correct. For the metrics use case, I'm surprised the k8s metadata is not there because I would assume we need this data too for correlation.

This happened for nginx and redis metrics because the input was created by the agent after enabling the integration in the fleet ui, without any use of dynamic providers. So no way to know that it is running on k8s so as to add the meta data. In case we start supporting conditions for dynamic auto discovery in the UI and the input is enabled because of a condition matching like `kubernetes.pod.name == nginx` then I suppose that the k8s metadata will be added indeed.


>For nginx logs use case. Ideally even if the container-logs integration is used, logs would be shipping to nginx.access dataset and not a generic data stream. The way I would expect it to work is that if lets say a user configured condition based autodiscovery, if the container is nginx the logs are shipped to the nginx.access datastream and also processed. We don't support this from the Fleet UI yet but I expect this to work in standalone mode. In this scenario the conflict happens.

The `container-logs` integrations is a generic one so I don't know how it could direct logs to different indices based on the pod nature (nginx, redis etc).
If due to auto discovery the nginx integration is enabled and we want the nginx `access log` data stream to take care of the access logs then it gets a bit complicated. User needs to specify the log path of access logs. That defaults to `/var/log/nginx/access.log` for nginx but as we are on k8s , that files are not accessible by agent unless we do some volume mounting. Instead those logs together with the error logs are streamed in the stdout and stderror. Then they are collected by k8s logging driver and written in the `/var/log/containers/*${kubernetes.container.id}.log`. If the user specifies this dynamic path at the data stream level then it is possible for the `access log` data stream to collect the logs. The only issue I see is that the access log data stream will process both access and error logs. The same applies for the `error logs` data stream.

**Comment by ChrsMark** [comment]
I agree with what @MichaelKatsoulis mentions here. Only one small correction that we can disdinguish the access from error logs by using the `stream` option (see https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-container.html#_stream) . It was available in container input, not sure if it is in filestream too. But again as Mike said, we will need to explicitly define a "template" just for nginx like:

```
- name: nginx
  type: nginx/logs
  use_output: default
  data_stream:
    namespace: default
  condition: ${kubernetes.labels.app} == 'nginx'
  streams:
    - data_stream:
        dataset: nginx.access
        type: logs
        stream: stdout
        symlinks: true
        paths:
              - /var/log/containers/*${kubernetes.container.id}.log
     - data_stream:
        dataset: nginx.error
        type: logs
        stream: stderr
        symlinks: true
        paths:
              - /var/log/containers/*${kubernetes.container.id}.log
```
This is how the Agent's inputs work right now when based on dynamic variables and conditions. Not many things to do here. 

Regarding the change in `namespace.name`, since it is causing so many issues (in Infra UI too) I'm +1 in reverting it if there is no other way by passing it. However I'm wondering why this simple change in a major (the only chance for us to perform such changes) is causing so many issues. Does this mean that we are locked to not change any fields in the future? This change is not that much crucial for k8s part however it would improve the experience and this is why we introduced it.

**Comment by MichaelKatsoulis** [comment]
If the mappings  of metadata in a data stream index are not created by the any `fields.yml` file does it mean that they are created on the fly by the type of the data written into them? 

If this is the case and every day for each data stream a new index is created(daily indices) like `.ds-metrics-nginx.stubstatus-default-2021.11.15-000001`  doesn't that mean that when elastic-agent version 8.0 starts collecting the new k8s metadata, it will set the correct mapping to the next days index?

**Comment by ruflin** [comment]
@MichaelKatsoulis Assuming we have daily indices and it is dynamic, correct it will adjust. But it also means you can't have both data types sent in parallel and after upgrade need to wait until the next day to have things working again.

@ChrsMark You are hinting at the main issue: There is no way to bypassing this yet. It would be nice if for example Elasticsearch would offer a way for such a migration. Or we figure out better ways to apply to migration to all data that is incoming. 

At the moment I'm also leaning in the direction of reverting the change unfortunately. But we should do it at one point as otherwise we are stuck with these scenarios. So even if we revert, lets continue the discussion on how we can make these changes possible in the future as otherwise it never happens.

**Comment by MichaelKatsoulis** [comment]
After discussions we reached to the decision to revert this change for now as it creates some important issues. We will try to find another way to make this change happen

**Comment by ChrsMark** [comment]
@MichaelKatsoulis what are the plans for this? Shall we close it or we still want to invest time on figuring out how this could work in the long run?
