### ISSUE TITLE
kubernetes.volume.fs.used.pct  is long type instead of scaled_float

### ISSUE THREAD

**Issue by MichaelKatsoulis** [elastic/integrations#2287]
Kubernetes volume integration field `kubernetes.volume.fs.used.pct` type is set as `long` in the package while it is [documented](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-kubernetes.html) to be `scaled_float`. 

The value is a percentage between 0-1 and Long type leads to rounding it to always 0.

**Comment by kaiyan-sheng** [comment]
This will be a breaking change of the current Kibana index pattern for users. Maybe instead of changing the type, we duplicate the field? cc @jsoriano

**Comment by jsoriano** [comment]
> This will be a breaking change of the current Kibana index pattern for users. Maybe instead of changing the type, we duplicate the field?

Not sure how this will work with index patterns managed by Fleet. Probably the best option is to try it, if it causes issues, I guess we will have to duplicate it, yes.
I wouldn't be so worried about old data, because it will be all zeros, so only check if upgrading to a package with a different field causes issues with the index pattern.

**Comment by jsoriano** [comment]
> The data view (index pattern) has a weird behaviour. Although it does not mention any type conflict it updates the type of the field from long to empty!

Weird indeed, I guess this doesn't happen if the new package is installed on a fresh installation? Not sure if this is made by the update process or it is a consequence of having mixed data in these indexes.

@ruflin wdyt, could this type change not be a breaking change? It would be quite inconvenient to need to duplicate this field when the old version is broken.

**Comment by MichaelKatsoulis** [comment]
> Weird indeed, I guess this doesn't happen if the new package is installed on a fresh installation? Not sure if this is made by the update process or it is a consequence of having mixed data in these indexes.

It does not happen if the new package is installed on a fresh installation. Then it is `scaled_float`.

**Comment by ruflin** [comment]
I'm pulling in @joshdover and team here. I know there has been few changes over the past iterations on index patterns / data views and not sure what the expected current behaviour is.

**Comment by MichaelKatsoulis** [comment]
My understanding is that:
1. While the kubernetes volume integration is in the old version, there is an index created for that data stream (.ds-metrics-kubernetes.volume-default-2021.12.02-000001) with a mapping that sets the type of `used.pct` to `long`
2. There is also the data_stream (metrics-kubernetes.volume-default) that has an index template with a mapping that also sets the type of `used.pct` to `long`
3. At the moment the integration is updated, a new index is created (ds-metrics-kubernetes.volume-default-2021.12.02-000002) with a mapping that sets the type of `used.pct` to `scaled_float`
4. The data stream has now two backing indices but its index template gets the mapping from the newest one (I guess this is what is happening) because the `used.pct` is now `scaled_float`
5. The data view of metrics-* gets confused because the type of a field changed but does not alert for a conflict. But it leaves the field type empty
6. The old data (added before the updated) are still 0. The new data(after the update) are now correct and searchable. I tested it

Besides the data view I cannot see any other issue.

**Comment by joshdover** [comment]
> Besides the data view I cannot see any other issue.

I think your analysis here is correct and follows my understanding of how these work as well.

Data views will use the [Field Capabilities API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-field-caps.html) to retrieve the field types of all matching indices in the index pattern. When there are multiple types matching the same field name in the index pattern, Kibana will attempt to resolve them [0] to the same type if they're compatible and can be used interchangeabley within the UI.

In this case, `scaled_float` and `long` are considered the same field type from Kibana's perspective (a number) [1]. So dashboards and visualizations are still possible, however the field type in the data view UI is unspecified for some reason [2]. @mattkime may be able to comment on the behavior in the UI here, though I'm not sure what the expected behavior would be.

[0] The type resolution logic from the field caps API happens in: https://github.com/elastic/kibana/blob/d1774fe48081879c2377a52f6b6ba93f12a4b6c6/src/plugins/data_views/server/fetcher/lib/field_capabilities/field_caps_response.ts#L71
[1] `scaled_float` and `long` are considered the same field type in: https://github.com/elastic/kibana/blob/d1774fe48081879c2377a52f6b6ba93f12a4b6c6/packages/kbn-field-types/src/kbn_field_types_factory.ts#L30-L46
[2] Logic for displaying the field type in the UI is in: https://github.com/elastic/kibana/blob/d1774fe48081879c2377a52f6b6ba93f12a4b6c6/src/plugins/data_view_management/public/components/edit_index_pattern/indexed_fields_table/indexed_fields_table.tsx#L71-L82

**Comment by joshdover** [comment]
I've confirmed this UI bug and produces a simple repro here: https://github.com/elastic/kibana/issues/120918

**Comment by MichaelKatsoulis** [comment]
Thanks a lot @joshdover for your help and time!
> Data views will use the Field Capabilities API 
The API in this case returns 
```
{
            "name": "kubernetes.volume.fs.used.pct",
            "type": "number",
            "esTypes": [
                "scaled_float",
                "long"
            ],
            "searchable": true,
            "aggregatable": true,
            "readFromDocValues": true,
            "metadata_field": false
        },
```
If `scaled_float` and `long` are considered the same field type from Kibana's perspective and if we assume that the order of the type array always follows the newest to oldest , Kibana could just pick the newest. In this case `scaled_float`.

**Comment by MichaelKatsoulis** [comment]
After https://github.com/elastic/kibana/pull/121004 was merged I tested how the possible conflict looks like in the data view. Both types are shown now. I think after this I can go on and implement the bug fix. @ruflin Do you agree? 
![double_type](https://user-images.githubusercontent.com/26270880/146544517-0a9a1364-8917-4eb3-b8ab-d670bdef4cc9.png)

**Comment by ruflin** [comment]
Yes, SGTM. @joshdover I assume on package upgrade, this will trigger an data stream rollover?

**Comment by joshdover** [comment]
@ruflin That's correct
