### ISSUE TITLE
Package READMEs are hard to navigate

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#260]
There is a lot of information contained in some packages' README files and navigating them is hard. I think this can be better for users with some changes.

- Add a table of contents after the overview paragraph that links to the sub-headings.
- Collapse the field documentation by default.

Every package that has a lot of fields or a lot of dataset suffers from this problem.

**Comment by ruflin** [comment]
There is an opportunity to also help solve this in the UI. @hbharding I think we will need our index on the left side rather soonish. 

@ph FYI

**Comment by mtojek** [comment]
I understand we have two choices:

1. Encode statically table of contents in every README.md file, so it's presented also in Github.

2. Leave it to Kibana UI to render it in runtime.

If we decide to go with 2., we can transfer this issue to the Kibana repository

**Comment by dedemorton** [comment]
While you're looking at this, wanted to point out that writers have similar concerns with the layout and content of the readme files. Our thoughts are captured here (based on an older version of the UI, but still valid): https://github.com/elastic/integrations-dev/issues/119#issuecomment-653254760

Let's work in concert on this to improve the overall layout and flow of the content.

**Comment by ruflin** [comment]
@mtojek Both options work for me. Having it in the README gives more control to the creator of the packages, having it in Kibana is more magical. I'm starting to wonder if both is actually useful. Have it at the top in the README but when you are navigation also on the left ...

**Comment by dedemorton** [comment]
@ruflin The files are quite long, so I would recommend having a "sticky" TOC in Kibana that doesn't disappear when you scroll the page. Assuming you do provide a TOC in Kibana, duplicating the TOC at the top of the file might be a little annoying to Kibana users because it would take up valuable space. It wouldn't hurt to try it out, though, and do some user testing.

**Comment by jamiehynds** [comment]
@dedemorton Our users are often unfamiliar with the steps to configure their source devices/applications to generate and transmit events to Elastic. How do you feel about adding a section to the Package READMEs that provides some guidance for each integration? Doesn't have to be a step-by-step guide, just some high-level steps and links to vendor documentation. 

If you take our Cisco readme as an example, it dives straight into the datasets we support and field mappings, but doesn't provide any guidance for configuring syslog on Cisco devices or where to send those logs to (a file, Elastic agent?).

We just added steps to our GSuite docs as users were getting stuck. It involves some research/maintenance on our side, but really helpful for users:

<img width="617" alt="GSuite Doc" src="https://user-images.githubusercontent.com/62879768/91964291-dce80000-ed06-11ea-8e44-115f699ed121.png">

**Comment by dedemorton** [comment]
@jamiehynds This seems like vital information, but it's definitely difficult to write, test, and maintain over time. We need to acknowledge that this takes more work and allocate resources accordingly. 

It's hard to strike the right balance. I like how you've provided links because step-by-step instructions about someone else's technology are impossible to maintain. But deep linking into another company's website is also risky, especially given that external doc links are currently not validated by our doc build. (I've had an issue open about that for awhile, but the infra folks have a lot of fish to fry.)  Another approach is to describe the requirements in text and provide a link to the top-level docs where users can search for details. This approach assumes that the user has some basic familiarity with the service or system they want to monitor. It's less helpful to users, but easier to maintain over time. 

Incidentally, I would put this content under a "Prerequisites" section or have a more descriptive title.
