### ISSUE TITLE
[8.0-rc2]: Unable to install `Cisco logs` integration.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/integrations#2606]
**Kibana version:**  8.0 rc-2 BC-2 Kibana Cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
BUILD: 49157
COMMIT: 01d4a6a088cae588e542623a47054bc76cfb2a6d
```

**Preconditions:**
1. 8.0 rc-2 BC-2 Kibana Cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Integrations tab and search Cisco logs integration
3. Observe user didn't get any link to navigate to Cisco integration.

**Expected Result:**
User should be able to install `Cisco logs` integration.

**Screenshot:**
![9](https://user-images.githubusercontent.com/77374876/151306766-24958123-49bb-4d42-9988-c14e364567f8.JPG)

**Note:**
- User gets `available as an integration` link on 7.17:
![10](https://user-images.githubusercontent.com/77374876/151306792-6fd03e0b-9810-410c-99ff-d1d4069bde5f.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @fearful-symmetry

**Comment by fearful-symmetry** [comment]
Not sure why I'm being pinged here, I've never touched the cisco code? @P1llus I think might know what's happening here.

**Comment by andrewkroh** [comment]
There is no `cisco` integration available in 8.0 because it was deprecated 7.x and replaced by product specific integration such as 

- cisco_asa
- cisco_duo
- cisco_ftd
- cisco_ios

**Comment by andrewkroh** [comment]
@elastic/unified-integration Would this be in the purview of your team? Is there a way to direct users toward multiple integrations?

**Comment by samratbhadra-qasource** [comment]
Hi @fearful-symmetry 
We have tested this issue on the latest  8.0.0 GA BC1 self-managed build and found that the issue is still **reproducible**. Please find below the testing details:

- Unable to install Cisco logs integration.

**Screenshot:**
![Screenshot (3)](https://user-images.githubusercontent.com/84007952/152497977-e28cab85-0689-416f-a470-18cc1b6ea557.png)

**Build details:**
VERSION:8.0.0 GA BC1
BUILD: 49192
COMMIT: 57ca5e139a33dd2eed927ce98d8231a1f217cd15
ARTIFACT: https://staging.elastic.co/8.0.0-da04e908/summary-8.0.0.html

Thanks!

**Comment by amolnater-qasource** [comment]
Hi Team
As per comment at https://github.com/elastic/integrations/issues/2606#issuecomment-1023604199 , Cisco integration is now deprecated.
Further we are no longer able to install Cisco logs integration.
We will be marking this as expected and will be deprecating any testcases related to Cisco integration.

Hence we are **closing** this issue.
Thanks
