### ISSUE TITLE
Avoiding hard-coded documentation links in the integration readmes 

### ISSUE THREAD

**Issue by lcawl** [elastic/integrations#2652]
There are currently about 15 hard-coded links to the Elastic documentation in the */_dev/build/docs/README* files.  As we add more integrations, however, that list will grow and as we move to the new documentation system, those URLs will need to be updated.

Given that we already have some content substitution in the README source files, such as the following in the [Apache integration readme](https://github.com/elastic/integrations/blob/main/packages/apache/_dev/build/docs/README.md):
> {{event "status"}}
{{fields "status"}}

... Can we do something similar to obfuscate the documentation links?

In the Elasticsearch API specifications, we're accomplishing this with a very simple list of keywords and URLS (https://github.com/elastic/elasticsearch-specification/blob/main/specification/_doc_ids/table.csv). We use the keywords in the source files and when the output is generated, it replaces the keyword with the full URL.  If we did something similar here, at the point where the package is built and the finalized README is generated, it would mean we could have a single source of truth for the doc URLs, which is easier to maintain.

**Comment by mrodm** [comment]
While working in this issue, I was wondering whether or not a new validation rule should be added into package-spec to avoid these links to elastic.co guides (for instance checking there are no https://www.elastic.co/guide/* links) and use the mechanism proposed in elastic/elastic-package#938.

This validation rule could show just a warning message or be stricter and raise an error when there is any `https://www.elastic.co/guide/*` link in `_dev/build/docs/*.md` files.

@ecosystem WDYT ?

**Comment by mrodm** [comment]
Tasks involved in this issue:
- [ ] Update elastic-package to include a new function to render links in README files https://github.com/elastic/elastic-package/pull/938
- [ ] Update README in integrations using links like https://www.elasti.co/guide/*
- [ ] Add a new validation rule in package-spec to check about the presence of these links in `_dev/build/docs/*.md` files ?

**Comment by mrodm** [comment]
First approach to support this feature can be checked at elastic/elastic-package#948

With this approach, there is a common file shared by all the packages that contains all the link definitions. The format of this file follows YAML syntax, Example of this file:
```yaml
links:
  key_1: url_1
  key_2: url_2
```

In elastic/integrations#4068, it is introduced this feature and shows all the changes it would be needed:
- Update all docs files to use the new `url` function in markdown
- Add YAML file with all the URLs at the root of the repository
    - In this file, just links from https://www.elastic.co/guide/* are added

Pros:
- All the links to Elastic guides are defined in the same file and shared by all the packages
- The path of this file could be customized using ELASTIC_PACKAGE_LINKS_FILE_PATH env var.

Cons:
- Any change in links files would require to publish a new version of the packages to take effect the changes
    - Should it require any automation to trigger new PRs for those? Or just wait until the owners decide.
- A PR that has been checked in its own branch successfully, when it is merged to main branch it could fail because some link could have been changed in main and its docs have not been updated accordingly.
    - Consequence, even it is in main branch, package will not be released/published since build process failed.
- If no validation rule is added to package-spec, Readme files could still being writing elastic URLs in markdown files.

I wanted to raise here these pros and cons to check whether or not to continue with this approach.

@elastic/ecosystem WDYT ? any other suggestion that it could be taken here to achieve this?

**Comment by mtojek** [comment]
> Any change in links files would require to publish a new version of the packages to take effect the changes
Should it require any automation to trigger new PRs for those? Or just wait until the owners decide.

Actually, it's consistent with ECS dependency. Whenever a package owner wants to update ECS fields, they need to manually bump up the dependency in `build.yml`. Agree, this is also something we should automate :)

> A PR that has been checked in its own branch successfully, when it is merged to main branch it could fail because some link could have been changed in main and its docs have not been updated accordingly.

Acknowledged risk. In the past, we enabled a forced rebase before merging a PR, but it was problematic for long-hanging PRs.

> If no validation rule is added to package-spec, Readme files could still being writing elastic URLs in markdown files.

Not sure if we should forbid it as maybe somebody would like to simply link it in the Markdown. I don't have a strong point about it.

Frankly speaking, I think that the approach you presented in the PR is the best possible we can offer. We should rather fix the other problem, and use dynamic versioning for packages (a feature idea?).

**Comment by mrodm** [comment]
Thanks for your comments @mtojek!

It looks like that the concerns I had can be assumed. Taking that into account, I think we can continue with that PR to add this feature. Afterwards, I would continue updating the integrations repository too, adding the new file and updating READMEs files if needed.

About the validation rule in the package-spec, if there is no inconvenient, it can be skipped for now. Later, it can be checked how READMEs in packages (regarding documentation links) and that shared file (`links_table.yml`) evolve without that rule.

**Comment by mrodm** [comment]
A new file has been added at the root of the repository with all the links found to Elastic documentation guides in the packages: [links_table.yml](https://github.com/elastic/integrations/blob/main/links_table.yml)

All the documentation in the current packages have been updated to use this the new "url" placeholder to render links.

It has also been added documentation on how to use this new placeholder [here](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md#documentation-guidelines) and [here](https://github.com/elastic/elastic-package/blob/main/docs/howto/add_package_readme.md#placeholders)
