### ISSUE TITLE
Network Packet Capture - Process Monitoring

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#2720]
Our Network Packet Capture integration includes an optional process field under advanced options, which allows a user to specify which processes to monitor (similar to [Packetbeat](https://www.elastic.co/guide/en/beats/packetbeat/current/configuration-processes.html)). 

- Could we include a 'select all' option here to ensure a user has visibility of all processes, rather than manually specifying each process. 
- When a user includes just one process to monitor, it seems to pick up all processes. Presumably this is a bug?   
- There is no guidance regarding the expected format of the processes, is it a path to the process or just the process name? Do they separate process names using a comma? Are wildcards and/or regex supported? Can we add some guidance to the 'processes' setting to ensure users understand the expected format.

**Comment by efd6** [comment]
Looking at the information flow in this configuration it looks to me that all processes are used to enrich network events.

The process option [feeds into to the `cmdline_grep` packetbeat config option](https://github.com/elastic/integrations/blob/f694e39d94dbcac19ba547cba6916e44c2e42321/packages/network_traffic/data_stream/tls/agent/stream/tls.yml.hbs#L3-L10) which is used to determine how process naming is handled.

When there is a `cmdline_grep` string is present, any contiguous substring match of the command line of a candidate process with the `cmdline_grep` string means that the name of the candidate process [will be changed to the configured process name](https://github.com/elastic/beats/blob/9cf957b12f93956d2fa49428bdb01a7943989d20/packetbeat/procs/procs.go#L280-L287).

Essentially for each data-stream the intention appears to be to set up a name rewrite. For example rewrite "nc" => "NetCat". The approach does not look sound to me since the `cmd_grep` string can occur anywhere in the command line, so for example if you were to use "nc" as the process option, this would cause a rewrite of the first process found with "nc" anywhere in the command line for example on a mac, anything managed by lau*nc*hd (you can see a work around for this in the tests [here](https://github.com/elastic/beats/blob/9cf957b12f93956d2fa49428bdb01a7943989d20/packetbeat/procs/procs_test.go#L86) where a trailing space is added). It seems to me that it would be appropriate to use regexes here since then you can anchor the match to relevant parts of the command line (the start in most cases).

The current model appears to assume that only one application will be using any one protocol since only one rewrite rule can be set per data-stream. To be generalised there would need to be an array of rewrite pairs.

Using regexes doesn't solve a deeper issue though; what to do when multiple contradictory rewrites are possible? At the moment it is first match wins, which doesn't lend itself to reproducible behaviour between configs; adding another data-stream could inadvertently modify the rewrite behaviour of a working data-stream. This could be mitigated by only matching the base of the first command line argument, or the process name already obtained via elastic/go-sysinfo but overwritten if there are args ([here](https://github.com/elastic/beats/blob/9cf957b12f93956d2fa49428bdb01a7943989d20/packetbeat/procs/procs.go#L319-L323)) (though just using that value would probably be more sensible).

(I don't quite see how the desired process display name is set in the package — [it looks like it isn't](https://github.com/elastic/integrations/blob/f694e39d94dbcac19ba547cba6916e44c2e42321/packages/network_traffic/manifest.yml#L21-L33); what I would expect to happen with the current code is that if there is a match with the `cmdline_grep` string that the process name would be zeroed out which would be less than ideal).

**Comment by efd6** [comment]
@andrewkroh and @adriansr Do you have suggestions for how this should be addressed?

ISTM that doing name rewrites is probably not a good thing to do in the general case and could be deprecated (or at least advised against) in packetbeat and removed from the package. Fixing the process name handling to only overwrite the name from comm on linux when it could be bumping up against the /proc/n/comm size limit would help with getting more meaningful names in place of doing rewrites (we currently use this more careful approach in the auditbeat system/socket module). Removing the option of doing the rewrites simplyfies the configuration and avoids the documentation issue, and the problems that I raise above.

**Comment by efd6** [comment]
This is solved by the changes made to network traffic for the GA release and outlined in the deprecation proposal. @jamiehynds, are you happy to close it?

**Comment by jamiehynds** [comment]
Sounds good, thanks @efd6
