### ISSUE TITLE
ECS 8.2 Meta Issue

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/integrations#2777]
This issue acts as a meta issue that tracks changes being made for all integration packages that require changes for ECS 8.2.

### Packages Requiring Changes

| Package         | PR Link | Notes |
|-----------------|---------|-------|
| cef             | #2804 |       |
| checkpoint      | #2803 |       |
| fortinet        | #2800 |       |
| mimecast | #2841 |  |
| panw_cortex_xdr | #2799 |       |
| sophos          | #2798 |       |
| auth0 |   | Currently at ECS 1.12, being updated to 8.2 by Marius |
| symantec_endpoint |   | Currently at ECS 1.12, being updated to 8.2 by Marius |

#### Part 1/4 (PR: #2778)

- 1password
- akamai
- atlassian_bitbucket
- atlassian_confluence
- atlassian_jira
- auditd
- barracuda
- bluecoat
- carbonblack_edr
- cisco_asa
- cisco_duo
- cisco_ftd
- cisco_ios
- cisco_meraki
- cisco_nexus
- cisco_secure_endpoint
- cisco_umbrella

#### Part 2/4 (PR: #2779)

- cloudflare
- crowdstrike
- cyberarkpas
- cylance
- f5
- fireeye
- gcp
- github
- google_workspace
- hashicorp_vault
- http_endpoint
- httpjson
- imperva
- infoblox
- iptables
- juniper_junos
- juniper_netscreen
- juniper_srx
- keycloak

#### Part 3/4 (PR: #2780)

- mattermost
- microsoft_defender_endpoint
- microsoft_dhcp
- microsoft_sqlserver
- netflow
- netscout
- network_traffic
- o365
- okta
- osquery
- panw
- pfsense
- proofpoint
- pulse_connect_secure
- qnap_nas
- radware
- santa
- snort
- snyk
- sonicwall
- squid
- suricata

#### Part 4/4 (PR: #2781)

- tcp
- tenable_sc
- ti_abusech
- ti_anomali
- ti_cybersixgill
- ti_misp
- ti_otx
- ti_threatq
- tomcat
- udp
- winlog
- zeek
- zerofox
- zoom
- zscaler_zia
- zscaler_zpa

**Comment by andrewkroh** [comment]
The PRs are ready, but we are waiting until we get closer to the ECS 8.2 official release to occur (at stack release time) to merge them. We don't want to publish them until ECS 8.2 is officially released and docs are available. And we don't want to merge them now because that would block any fixes or enhancements from being releasable. So we'll merge them the week of the official 8.2 release so that they are ready to promote to the production registry shortly after 8.2 stack is released.
