### ISSUE TITLE
[CI] Only run tests for affected packages in PR builds

### ISSUE THREAD

**Issue by ycombinator** [elastic/integrations#296]
As the number of packages in this repository grows, and with the introduction of system tests, the amount of time taken by CI builds will start growing. We have seen this happening in the Beats CI.

One way we addressed the problem in Beats was to check if exactly one module was affected by a PR. If so, we would only run the tests for that module. See https://github.com/elastic/beats/pull/18592.

We can play a similar game for PR CI jobs in this repo (integrations). In PR CI jobs, we should check which packages are changed by that PR. Then we should only run tests for those packages.

In fact, as the tests so far (pipeline and system) are defined at the datastream level, we might want to take this a step further: check not just which packages have changed by a PR but also which datastreams have changed within those packages, and then only run tests for those packages' datastreams.

**Comment by mtojek** [comment]
I spent some time researching this topic and reviewing the Integration repo. I identified a couple of action items (defined below). It's super easy to introduce this feature if we stick to the Magefile (use `git diff`). The drawback of this solution is that we introduce more tangled (and conditional) build logic, which is something we wouldn't like to do.

So here is the plan...

Beats repo uses [getGitMatchingGroup](https://github.com/elastic/apm-pipeline-library/blob/721115cf0fdb2b5a4e1cb6a576bfbb7035d14485/vars/getGitMatchingGroup.groovy#L38-L58), which determines if the module has changed in the PR and should be considered in tests.

I think we should proceed with a similar solution and we don't have any issue with long running tests so far. I will try to prepare the Magefile and Jenkinsfile for this issue first. Let me follow the approach:

1. Resolve: https://github.com/elastic/elastic-package/issues/151
2. Resolve: deprecate and remove testing/environments - use `elastic-package stack up`,

Now we can extract all package-related steps from the Magefile and use it to build/call other sources (dev scripts, licenser, mod tidy)....

3. Extract package-related steps to be called directly from the Jenkinsfile.
4. Parallelize elastic-package tests. Ideally we should dynamically create parallel stages with Jenkins. I hope it's possible to grab results from multiple stages. We may need to install elastic-package there and 

This is the moment to run tests conditionally...

5. Add logic to the Jenkinsfile to run package tests on following triggers.

For single integrations:
- package code has been updated
- new package appeared

For all integrations:
- a dependency has been added (`go.mod`)
- ENV variable to run the entire test set

Events that won't trigger tests:
- Elastic stack has been updated (the Integrations repo doesn't track Docker images)

We should preserve consistency with the Integrations docs, so that we won't introduce changes that are not covered by our package guides. 

@ycombinator I'm looking forward to your opinion about the plan.

**Comment by ycombinator** [comment]
I'm good with steps 1, 2, and 3. I'm not sure if they are strictly necessary for this issue but I may be missing something and it seems like a good time as any to do some cleanup before we introduce more complexity into the Magefile and Jenkinsfile.

As for step 4, there is a separate issue for this (https://github.com/elastic/integrations/issues/297). This one seems fair complex to me (and you outlined some of the reasons for the complexity as well) so, if possible, I would try to keep this step out of scope for this issue here. In the Beats repo, for PR builds, we are able to run tests specific to a module without also having parallelization between tests. So I'm hoping we can do the same here first and then later tackle #297. 

> For single integrations:
> * package code has been updated
> * new package appeared
> For all integrations:
> * a dependency has been added (go.mod)
> * ENV variable to run the entire test set

Just want to make sure I'm following this correctly. I'm reading this as "if package code has been updated _or_ new package appeared, then run tests only for the affected packages". Similarly, "if a dependency has been added or a special ENV variable has been set, then run tests for all integrations". Also, all of the above will be true only for PR builds, right? It won't be applicable to `master` branch builds, right, as those should always run all packages' tests (at least until https://github.com/elastic/integrations/issues/323 is implemented)?

> Events that won't trigger tests:
> * Elastic stack has been updated (the Integrations repo doesn't track Docker images)

Hmmm, I'm not sure about this. In principle it seems to me that we should re-test all packages if, say, Kibana's version was bumped up in the Elastic Stack. But I think this will happen because when Kibana's version is bumped up in the Elastic Stack, we'll get a new release of `elastic-package`, right? And that would result in a dependency bump in `go.mod` in the integrations repo, which would trigger tests for all packages, yes?

> We should preserve consistency with the Integrations docs, so that we won't introduce changes that are not covered by our package guides.

I didn't follow this. Could you elaborate or maybe provide an example? Sorry.

**Comment by mtojek** [comment]
>I'm good with steps 1, 2, and 3. I'm not sure if they are strictly necessary for this issue but I may be missing something and it seems like a good time as any to do some cleanup before we introduce more complexity into the Magefile and Jenkinsfile.

Without steps 1, 2, 3 it won't be possible to easily introduce the feature (only run tests for affected packages) without introducing the logic to the Magefile, which is something I prefer not to do.

> As for step 4, there is a separate issue for this (#297). This one seems fair complex to me (and you outlined some of the reasons for the complexity as well) so, if possible, I would try to keep this step out of scope for this issue here. In the Beats repo, for PR builds, we are able to run tests specific to a module without also having parallelization between tests. So I'm hoping we can do the same here first and then later tackle #297.

Right, I've put it on the list to present when is the best moment to touch this (to show that this item also depends on other fist action items. We can delegate it to the original issue.

> Just want to make sure I'm following this correctly. I'm reading this as "if package code has been updated or new package appeared, then run tests only for the affected packages". Similarly, "if a dependency has been added or a special ENV variable has been set, then run tests for all integrations". Also, all of the above will be true only for PR builds, right? It won't be applicable to master branch builds, right, as those should always run all packages' tests (at least until #323 is implemented)?

Correct. I will add the information about the master branch.

> Hmmm, I'm not sure about this. In principle it seems to me that we should re-test all packages if, say, Kibana's version was bumped up in the Elastic Stack. But I think this will happen because when Kibana's version is bumped up in the Elastic Stack, we'll get a new release of elastic-package, right? And that would result in a dependency bump in go.mod in the integrations repo, which would trigger tests for all packages, yes?

Yes, but it's just one use case. We depend on SNAPSHOT builds, so in case a new snapshot Docker image will be pushed, it won't trigger all tests for PRs. I think we can accept this risk as we run all tests for the master branch.

> I didn't follow this. Could you elaborate or maybe provide an example? Sorry.

Sorry for not writing it clearly. I referred to the CONTRIBUTING guide mainly (https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md). It uses `mage` commands I'd like to replace with direct `elastic-package` calls.

**Comment by ycombinator** [comment]
Thanks for the responses, @mtojek. My main concern is trying to do to many changes at once. So I would try and put up separate PRs for steps 1, 2, 3 each, if possible. Then I'd prefer to keep #297 out of scope and tackle it later, if possible. If not, then let's tackle it now but in a separate PR. Finally, we can tackle step 5 in its own PR.

Everything else is clear now. Thanks for explaining!

**Comment by mtojek** [comment]
> My main concern is trying to do to many changes at once. So I would try and put up separate PRs for steps 1, 2, 3 each, if possible. Then I'd prefer to keep #297 out of scope and tackle it later, if possible. If not, then let's tackle it now but in a separate PR. Finally, we can tackle step 5 in its own PR.

Yes, that's the plan :) I wouldn't like to accumulate many changes in a single long-hanging PR.

Thank you for the discussion!

**Comment by ruflin** [comment]
Could we treat the system and endpoint package as "special" by having it run always? Lets assume someone accidentally removes the system package. I assume CI would go green as no tests have to be run?

**Comment by ycombinator** [comment]
Note that this is only for PR builds. For `master` builds, all packages' tests will be run.

**Comment by ruflin** [comment]
@ycombinator Yes. I would still run these 2 always.

**Comment by mtojek** [comment]
Do you think we should postpone this feature in favor of parallel test execution (on different Jenkins nodes)? I'm asking because at this moment it doesn't matter which issue we select (all preparation works are done/merged).

**Comment by mtojek** [comment]
I think I can come back this issue now.
