### ISSUE TITLE
[cassandra] [Logs Cassandra] System Logs dashboard is broken

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#3031]
Loading "[Logs Cassandra] System Logs" fails on 8.x (tested 8.2.0-SNAPSHOT). Details on the problem can be found in #3023.

> Error encountered while loading saved dashboard: Could not find reference for kibanaSavedObjectMeta.searchSourceJSON.filter[0].meta.index

<img width="290" alt="Screen Shot 2022-04-07 at 12 06 16" src="https://user-images.githubusercontent.com/4565752/162248016-866e333c-fe2c-4caf-a8fe-7862c28e213f.png">

**Comment by ShubhangiCrest02** [comment]
For Cassandra system logs dashboard issue
-------------
The integration was built on the elastic-stack snapshot version which is not the stable one. That's why some of the dashboards are not loaded.
We are able to fix the issue by re-created the dashboard and visualization again on the stable version.
We have tested the fix with all Elastic Stack (7.15,7.16,7.17.2,8.0,8.1 and 8.2.0) and Dashboard is rendering correctly 
We have also loaded a few sample documents to test.

We have raised PR: fix for Cassandra system logs dashboard: https://github.com/elastic/integrations/pull/3287

![Capture](https://user-images.githubusercontent.com/103563586/167159768-57729800-ca4a-46bf-b6b9-d8fa86774747.PNG)
