### ISSUE TITLE
[Okta] Exported fields not being parsed

### ISSUE THREAD

**Issue by akfav** [elastic/integrations#3292]
Fields for the `okta.request.ip_chain.*` object are listed as exported fields but are not currently not being parsed.  The following fields should be parsed: 
```
"request": {
        "ipChain": [
            {
                "geographicalContext": {
                    "city": "Dublin",
                    "country": "United States",
                    "geolocation": {
                        "lat": 37.7201,
                        "lon": -121.919
                    },
                    "postalCode": "94568",
                    "state": "California"
                },
                "ip": "67.43.156.12",
                "source": null,
                "version": "V4"
            }
        ]
    }
    ```

**Comment by efd6** [comment]
@akfav For the majority of cases, most of this information will be found in the `client.geo.*` fields (not the post code nor the Okta `IpAddress.source` field). The Okta docs [explain](https://developer.okta.com/docs/reference/api/system-log/#request-object) that it hold intervening proxy details. Retaining this data outside the original message is a little problematic since its an array of structured data, and so would have to be either type nested or flattened. How is the data intended to be used?

**Comment by akfav** [comment]
hi @efd6 the client I am working with is specifically interested in the parsing of the post code. I believe they would like to have it parsed to include in reports and visualizations.

**Comment by efd6** [comment]
OK, so that sounds like it should be fine to map as a `flattened` rather than as a `nested`. Are they OK with that? This would provide them with the data for reports and visualisations, but not for full search functionality.

**Comment by akfav** [comment]
That would be great! thank you @efd6
