### ISSUE TITLE
[vSphere] Special Character in Password for vSphere SDK causes YAML parse error

### ISSUE THREAD

**Issue by kpollich** [elastic/integrations#3429]
When adding a policy for the vSphere integration, an SDK password containing a special symbol throws the following error.

![image](https://user-images.githubusercontent.com/6766512/170265325-43538b76-c158-46fb-8954-2d3019078ff3.png)

This appears to be the same issue as https://github.com/elastic/integrations/issues/3388, and we'd need to add a `!!str` to the package manifest for the password variable declaration, which I believe is here: https://github.com/elastic/integrations/blob/main/packages/vsphere/manifest.yml#L60-L67

**Comment by ishleenk17** [comment]
@kpollich @joshdover : Considering we will be seeing this issue across all integrations. 
What's the consensus on the fix here ?
Is it being handled in Kibana or are we handling it at integrations level ?

**Comment by ishleenk17** [comment]
I have tried out multiple password combinations with special characters, but I am not seeing the issue. 
hello"hel@"hu'lk'hu : Password that I tried. 

Is there a special scenario for which the issue is seen ? @kpollich . 
I have reached out to the support engineer as well who had raised the SDH to get more info on the same

**Comment by kpollich** [comment]
Here's a password where I was able to force a YML parse error, though not the original one reported here: 

'>my:password"-test

**Comment by ishleenk17** [comment]
This issue is being fixed at the Fleet side with https://github.com/elastic/kibana/issues/127268
