### ISSUE TITLE
Support for Tenant Logs in Azure integration

### ISSUE THREAD

**Issue by andresrc** [elastic/integrations#3460]
- We expect that `SignInLogs`, `NonInteractiveUserSignInLogs`, `ServicePrincipalSignInLogs`, `ManagedIdentitySignInLogs`, `ADFSSignInLogs` can be shipped to `logs-azure.signinlogs-default`
- We expect that `AuditLogs`  can be shipped to `logs-azure.auditlogs-default`
- We need sample log files for `ProvisioningLogs`, `RiskyUsers`, `UserRiskEvents` to do simple validation to make sure that they can be ingested into `logs-azure.platformlogs-default`

**Comment by zmoog** [comment]
The new log categories are ingested in two new dedicated data streams in the Azure Active Directory integration (instead of using one generic data stream `logs-azure.platformlogs-default`):

- `logs-azure.identityprotectionlogs-default`
- `logs-azure.provisioninglogs-default`


The "identityprotectionlogs" data stream will support the `RiskyUsers` and `UserRiskEvents` log categories. The "provisioninglogs" will support the `ProvisioningLogs` log category.

Both data streams come with a simple dashboard to visualize the data. 

Implemented with https://github.com/elastic/integrations/pull/4149
