### ISSUE TITLE
Remove package granularity for Kubernetes from the integrations UI search 

### ISSUE THREAD

**Issue by mlunadia** [elastic/integrations#3481]
After [introducing granularity](https://github.com/elastic/integrations/pull/1018) for all the components of Kubernetes to be searchable on the integrations UI, we have received different feedback that the amount of choices makes it confusing to users especially those that don't understand the intricacies of K8s.

![image](https://user-images.githubusercontent.com/39376769/172549813-c590e7c7-7a2a-4b07-9404-805735f83306.png)

We will remove the search granularity that breaks down the Kubernetes package into all the different components it integrates with.

- [kubelet](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/)
- [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics)
- [apiserver](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)
- [controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/)
- [scheduler](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/)
- [proxy](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/)

Users should still be able to have granular control of which services they want to integrate with by using the toggle buttons whilst the Kubernetes integration is added or after by editing it.

![image](https://user-images.githubusercontent.com/39376769/172550849-c0b35a92-fbed-4230-b865-b70f04d1c7f5.png)

**Acceptance criteria**
Users should not be blocked from having granular control by having to choose the Kubernetes integration only.

**Comment by mlunadia** [comment]
@jen-huang @kaiyan-sheng  I see you were active in the issue we're planning to reverse. Do you mind having a quick look and sharing any context or objections regarding removing the granular aspect for search?
cc: @ruflin

**Comment by jen-huang** [comment]
I assume we will not want to change the package in order to revert this (aka collapsing all `policy_templates` back into a single one). Instead, we should simply change the Kibana code that shows one tile per `policy_templates`. This is easy enough to do, but it will change it for _all_ packages that export granular integrations: not only K8, but AWS as well.

On the other hand, if we do want to keep granular tiles around for AWS but not for K8, then we will have to change the K8 package. The tradeoff here is that:

- If user already has K8 package installed, it will still show all the granular tiles until they upgrade to the non-granular package
- When the user upgrades, their existing K8 policies will not be able to be automatically upgraded due to the significant change in package manifest

cc @mukeshelastic @akshay-saraswat @kpollich

**Comment by mlunadia** [comment]
thanks @jen-huang the granularity on AWS makes sense as these are infrastructure entities which users will be looking to monitor (eg. AWS EC2, AWS lambda, etc.). For the Kubernetes use case breaking it down into components is adding confusion to users. 

Thanks for pointing out the trade offs as this is very important to know. I'll confer with @gizas to understand best and also will look into quantifying the number of active integrations for each of those K8s components.

**Comment by MichaelKatsoulis** [comment]
As Jen described, updating the kubernetes package to collapse the `policy_template` will make the upgrading procedure quite tricky(tested that).

The simplest solution for now (we can call this an experimental phase) for removing the Kubernetes integration granularity is to achieve this in FleetUI.

The [filteredList](https://github.com/elastic/kibana/blob/0b2fee08d544b9251baa8f36c7b1bf81b9e9a0f5/x-pack/plugins/fleet/public/applications/integrations/sections/epm/components/package_list_grid.tsx#L96) returned in every search can be further filtered to remove integrations that have `name:kubernetes`  and `id!=epr:kubernetes`. 

A quick code did the trick 
```
for (let i = filteredList.length - 1; i >= 0; i--) {
        if (filteredList[i].name === "kubernetes" && filteredList[i].id !== "epr:kubernetes") {
          filteredList.splice(i, 1);
        }
      }
```

that way UI only shows the superset Kubernetes integration
<img width="1372" alt="Screenshot 2022-07-06 at 5 00 36 PM" src="https://user-images.githubusercontent.com/26270880/177572107-cc114df3-cc03-4499-9992-09f0f4d7d80c.png">

And the upgrade process does not break.

<img width="1219" alt="Screenshot 2022-07-06 at 5 04 42 PM" src="https://user-images.githubusercontent.com/26270880/177572686-69f155ba-b849-4c66-8e59-3f8d190a1e6c.png">
<img width="1574" alt="Screenshot 2022-07-06 at 5 04 37 PM" src="https://user-images.githubusercontent.com/26270880/177572748-bec2c1b1-8155-4ef3-90da-928584026464.png">

@mlunadia WDYT ?
@joshdover Do you have any objection on this kind of solution?
 I know it is hacky but I believe we should experiment first on how users may react to such a change before implementing more permanent solutions within the package.

**Comment by gizas** [comment]
Just from curiosity although you filter the rest of integrations if you use the old link hadcoded will still work?
Also if for eg. we add the Prometheus integration with tag kubernetes, the prometheus will still show with above filter?

**Comment by MichaelKatsoulis** [comment]
> Another UI options would be to show a "stacked" card for the Kubernetes package. 

@jen-huang This sounds like a good solution although I don't know how it looks like.

>  What do you think is the correct long-term structure for the Kubernetes package?

My instinct says that Kubernetes integration is one thing and all the rest are implemented details. I haven't seen in any of our competitors to offer separate integrations for k8s monitoring.

**Comment by joshdover** [comment]
> We would like to experiment and mitigate risk before changing the package but don't see @MichaelKatsoulis proposal as a long-term fix but an experiment. However, we are keen on making sure this is acceptable and trackable so the temporary doesn't become permanent.

I'm generally ok with this type of approach as long as:
1. This experiment is needed to validate an approach before we invest time in something _or_ we already have enough evidence that the current approach is a big problem
2. We commit to following up on the long-term fix

It seems to me that we're actually pretty sure that a single tile is the way to go for the k8s integration. If we want to move ahead on this workaround anyway because the long-term fix will take too long, that could be fine too, but we need to be conscious about the technical debt the UI team is being asked to take on (in addition to other requests from other package developers). If we take this on now, I'd want us to start working on defining how upgrade paths for breaking package changes like this are going to work quite shortly.

Alternatively, we could instead make sure the main overall policy template is sorted ahead of the other policy templates. I think this could make sense for all multi-policy template packages and not be k8s specific (thus no UI debt). Would that be a good enough improvement to give us time to do the long-term fix for the k8s package?

Related, @jen-huang we probably should keep track of a meta issue of package-specific hacks we have in Fleet to follow up on. Thinking about things like the APM limitation on Logstash output, packages excluded from the new onboarding UX, etc.

**Comment by MichaelKatsoulis** [comment]
> Alternatively, we could instead make sure the main overall policy template is sorted ahead of the other policy templates.

@joshdover by that you mean that them main policy template (Kubernetes in our example) will be shown first in the long list of policies? If yes, imho I don't think this makes it much  less confusing for a client.

Regarding the long term solution I can see 2 options:
1. We update k8s package to put all integrations under same policy_template, which constitutes a breaking change as it makes the upgrading procedure not straight forward any more
2. We introduce in the package policy_templates a new variable (hide_template?) alongside `name`,`title`,`description` and when set to true Kibana will skip the flattening in https://github.com/elastic/kibana/blob/e3ea3fd02b31d30cee43a2d00059d5b9c7743e42/x-pack/plugins/fleet/public/applications/integrations/sections/epm/screens/home/available_packages.tsx#L162.

**Comment by MichaelKatsoulis** [comment]
As long as there is no strong objection I suggest we move forward with filtering out multiple Kubernetes integrations in Kibana for 8.4 and then we can start discussing for the permanent solution.
cc @joshdover , @mlunadia
