### ISSUE TITLE
[docs] Add an overview page for integrations grouped in packages

### ISSUE THREAD

**Issue by dedemorton** [elastic/integrations#3685]
We now have quite a few integrations that are grouped into packages, but there is no high level docs page that we can link to because the grouping appears in the navigation only (it is not an active link):

![image](https://user-images.githubusercontent.com/14206422/178377064-ed2ead65-5160-4aad-88e8-6f045600ae18.png)

This breaks our current implementation in the Metricbeat and Filebeat docs  where we include shared text to point users to the relevant integrations documentation. 

```
.Prefer to use {agent} for this use case?
****
Refer to the
https://docs.elastic.co/en/integrations/{modulename}[Elastic Integrations documentation].

[%collapsible]
.Learn more
====
{agent} is a single, unified way to add monitoring for logs, metrics, and
other types of data to a host. It can also protect hosts from security threats,
query data from operating systems, forward data from remote services or
hardware, and more. Refer to the documentation for a detailed
{fleet-guide}/beats-agent-comparison.html[comparison of {beats} and {agent}]. 

====

****
```

We can override `modulename` to change the link path, but we can't easily provide links to all the integrations. To work around this problem, we're linking to the first integration in the group (see https://github.com/elastic/beats/pull/32279). This isn't ideal, especially right now, because the navigation does not synchronize properly (known bug). It's difficult for the user to see the related integrations.

The best way forward is probably to make the TOC group an active link to a page that contains links to all the integrations included in the package. IMO it would be better to generate this page. Then we would have persistent pages for linking.

I think it's possible that the pages will be useful for other reasons...for example, if you want to point AWS users to all the integrations that are available.

**Comment by bmorelli25** [comment]
Thanks for opening this issue!

> The best way forward is probably to make the TOC group an active link to a page that contains links to all the integrations included in the package.

I agree that this approach makes sense. This is currently possible in our new documentation system. There is one limitation that I've already pointed out to the next-docs team. By design, `EuiSideNav` doesn't show arrow indicators for content with children. From the [EUI docs](https://elastic.github.io/eui/#/navigation/side-nav#nested-item-options):

  _Arrow indicators will show only if the item has children but does not have an interaction itself. The component will then handle the toggling of the displayed children as well._

This limitation results in it not being immediately clear that our "buckets" of integrations are, well, buckets:

<img width="1490" alt="Screen Shot 2022-07-11 at 1 26 58 PM" src="https://user-images.githubusercontent.com/5618806/178379014-b77ca1df-497a-4f7e-8caa-891fda7a1307.png">

> IMO it would be better to generate this page. Then we would have persistent pages for linking.

I don't see this being possible any time soon. Right now the nav and any "buckets" within the nav are all generated by hand. There is nothing that currently exists (AFAIK) in the integration manifest files that link related integrations from different packages together.

As I type, I'm realizing that we could use the nav file to generate these overviews. Iterate over the pages within each bucket and auto-generate a description and link based on the contents of each bucket. The nav files are just JSON, so that would be possible. Neat idea.

**Comment by dedemorton** [comment]
>As I type, I'm realizing that we could use the nav file to generate these overviews. Iterate over the pages within each bucket and auto-generate a description and link based on the contents of each bucket.

Yah, that's what I was thinking. Trying to maintain links on overview pages manually is a fool's errand.  :-)

>This limitation results in it not being immediately clear that our "buckets" of integrations are, well, buckets.  It does sound like the next-docs team will fix this though.

IMO we shouldn't let this stop us from moving forward. Presentation/design issues shouldn't change how we structure the content, no?

I guess the next step is to find someone who can write code that iterates through the JSON and generates overview pages.

**Comment by bmorelli25** [comment]
> IMO we shouldn't let this stop us from moving forward. Presentation/design issues shouldn't change how we structure the content, no?

Good point.

> I guess the next step is to find someone who can write code that iterates through the JSON and generates overview pages.

Yeah. I gave it a try, and this isn't something I can accomplish in a reasonable amount of time.

**Comment by colleenmcginnis** [comment]
We did this. ✅
