### ISSUE TITLE
Create package for Salesforce integration

### ISSUE THREAD

**Issue by akshay-saraswat** [elastic/integrations#3940]
We must migrate Salesforce filebeat module to agent-based integration so that we boost agent/fleet adoption and are ready for any decision related to beats future.

cc: @pmeresanu85 @rameshelastic 

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

**Comment by yug-elastic** [comment]
List of backlog items as suggested by @agithomas and discussed with the team:

- System tests with actual Salesforce instance containerized (Currently, the system tests use the observability/stream image due to the limitations mentioned [here](https://github.com/elastic/integrations/pull/4261#discussion_r993356958))

CC: @milanparmar-crest @lalit-satapathy
