### ISSUE TITLE
[Windows] Migrate security events to System package

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#399]
Our initial Windows Events package shipped in 7.10, which includes security, sysmon and PowerShell events. As per discussions [here](https://github.com/elastic/integrations-dev/issues/357), we are going to include security events in the system module. 

We need to create a 7.11 transition experience for windows packages users to ensure they no longer get security events from the windows package and need to upgrade to the 7.11 system package.

**Comment by leehinman** [comment]
@jamiehynds @fearful-symmetry I've been thinking about the upgrade experience for the user.

Right now both `system` and `windows` packages have a condition of `kibana.version: `^7.10.0'`, so that means they should work with anything older than 7.10 and any 7.10.X series but not 7.11 or greater.

So if we update both `system` and `windows` package at the same time to have  condition of `^7.11.0`, then the new packages should only work on 7.11.  Also if we make sure the visualization in the system package work with the old data_streams then any data collected in 7.10 would still be visualized correctly.

I also think we need a notification on the `windows` package mentioning that System, Security & Application event logs are provided by the `system` package.

Can you think of anything else that we need to cover for the transition?

**Comment by jamiehynds** [comment]
@leehinman sounds like a great solution. For users collecting security events via the 7.10 Windows package, there would be no manual steps required as those events will now be enabled in the system package and their 7.10 visualisations will still be populated. Correct?

Totally agree the windows package description should mention that system, security and application logs are provided by the system package. We'll also need to include some guidance around custom windows events there too.

**Comment by fearful-symmetry** [comment]
> So if we update both system and windows package at the same time to have condition of ^7.11.0, then the new packages should only work on 7.11. Also if we make sure the visualization in the system package work with the old data_streams then any data collected in 7.10 would still be visualized correctly.

This is sort of what I've been thinking as well. I've fixed the visualizations so they should work with older data. Just need to update `kibana.version`.

>  For users collecting security events via the 7.10 Windows package, there would be no manual steps required as those events will now be enabled in the system package and their 7.10 visualisations will still be populated. Correct?

Unless I'm missing something, yes.

> Totally agree the windows package description should mention that system, security and application logs are provided by the system package. 

+1
