### ISSUE TITLE
[cisco_umbrella] Pipeline errors while parsing audit logs

### ISSUE THREAD

**Issue by bm11100** [elastic/integrations#3996]
The ingest processor for the Cisco Umbrella Elastic Agent integration does not correctly parse the audit logs. 

Errors - 
`cannot access method/field [toLowerCase] from a null def reference`
`Unmatched quote`

![image](https://user-images.githubusercontent.com/56412096/183806821-5e4638cd-048a-41fc-8651-4f02ea651279.png)

Also, in the bucket list profile configuration it says the below - this is not true, mine did not work until i removed the forward slash. 
> Forward slash at the end required for Cisco Managed S3.

![image](https://user-images.githubusercontent.com/56412096/183806364-fce9aafd-3dca-4d80-9472-11b070ca3085.png)

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 1.2.1
- Operating System: Windows Server 2019
- Steps to Reproduce:  
1. Set up Umbrella integration
2. Use the Cisco Managed S3 bucket
3. Enable audit logging
![image](https://user-images.githubusercontent.com/56412096/183805461-79f57b09-78fc-42ac-8f21-79307c4dceab.png)

**Comment by efd6** [comment]
@andrewkroh I don't think this is a pipeline error. The inputs to the pipeline are invalid, so the things that I am following up are whether this is due to data being held in S3 or whether the awss3 input is not correctly handling the data that is there.

**Comment by jamiehynds** [comment]
Hey @bm11100 - are you still having issues with the Umbrella audit logs or can this issue be closed?

**Comment by bn-jmynsberge** [comment]
This issue is still present in 1.22.0.  The final column contains multilines.  Therefore the messages are sent as follows:

1. 1578700280 | 8/9/2022 21:10 | steven@x.com | Steven Barris | users | create | x.x.x.x |   | email: brent@x.com
2. role: Full Admin
3. roleId: 1
...

**Comment by efd6** [comment]
@bn-jmynsberge Can you provide an un-interpreted example of this for testing? That is, an attached file exactly as the entry appears in the blob store (obviously sanitized, but otherwise unaltered).

**Comment by bn-jmynsberge** [comment]
Here are sample logs from a few different orgs. 
[umbrella_auditlogs.zip](https://github.com/elastic/integrations/files/14774042/umbrella_auditlogs.zip)

**Comment by efd6** [comment]
Thanks, that's an unfortunate design decision. They are valid RFC 4180 format (almost*), but the literal new lines are causing a problem. I can't inject those into tests successfully, but we have tests that use `\n` as escaped LF. If I add a `gsub` processor into the start of the ingest pipeline to interpret these into real LF, the pipeline does work as expected, so the `csv` processor is not at fault.

The s3 input allows specification of the line separator though the integration does not currently make that available. If the files that you do actually conform to the RFC (this may be the case and the transfer to those files on a mac resulted in conversion to unix line endings), then adding that option and using it with `carriage_return_line_feed` would fix the problem. If they are not, then the problem is more difficult to solve. Can you take a look an completely unmodified blobs from the s3 bucket and check whether they are LF line terminated or CRLF line terminated?

`*` The almost comes from the fact that the lines are LF terminated, but the RFC requires CRLF.
```
   1.  Each record is located on a separate line, delimited by a line
       break (CRLF).  For example:

       aaa,bbb,ccc CRLF
       zzz,yyy,xxx CRLF
```

**Comment by bn-jmynsberge** [comment]
The admin logs do not have any value to us currently and can be dropped or even handled as a separate dataset.

I am on Macos and modified most of the files but I don't think I overwrote the line endings.  When I view the raw files they are also LF terminated:

"1762607491","2024-03-25 07:54:47","ops@opendns.com","lastSuccessfulUpdate: 1711266616 CRLF
lastValidatedAt: 1711345176 CRLF
modifiedAt: 2024-03-25 05:39:36 CRLF
","lastSuccessfulUpdate: 1711353285 CRLF
lastValidatedAt: 1711353287 CRLF
modifiedAt: 2024-03-25 07:54:47 CRLF
" LF

Here is an unmodified raw file:
[2024-03-25-07-50-ade8.csv.gz](https://github.com/elastic/integrations/files/14790380/2024-03-25-07-50-ade8.csv.gz)

**Comment by andrewkroh** [comment]
With the aws-s3 input supporting the [multiline parser](https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html), maybe that is a tool that could be applied to group each csv line in one event?
