### ISSUE TITLE
[Cloudflare] Growing Delay in Logpull after network/other issues

### ISSUE THREAD

**Issue by thijsvanloef** [elastic/integrations#4088]
Hi,

Last week we noticed an issue with the Cloudflare Integration within Elastic. After experiencing some network issues between GCP & Cloudflare, we noticed that all of our logs were delayed by 20 minutes. Even if the interval was set to 1m, we only received the data after 20 minutes. The difference between the most recent Cloudflare Logs served by the API and those imported by the Cloudflare integration was 15m. Restarting the integration made it worse. 

Now we have looked at the values for a start and stop parameters:
- `url.params.start`
- `url.params.end`

And it seems like these depend on each other, meaning that if you miss 1 "interval" it will be permanently delayed by the missed interval. As stated before, restarting the agent/integration does not fix this issue and will only worsen it. The only way we could solve this issue was to manually set the `url.params.end` to a bigger value than the interval. 

A possible solution would be to change the logic of line [#34](https://github.com/elastic/integrations/blob/176203b234e1e5f552b70500f855648a62b9147d/packages/cloudflare/data_stream/logpull/agent/stream/httpjson.yml.hbs#L34) of the `httpjson.yml.hbs` file. If you change the logic to use the `minimum(enddate + 2X interval)` or `(now - interval)`  it will (after some time) automatically catch up to the most recent date-interval in case of an outage/issue.

**Comment by jamiehynds** [comment]
Hi @thijsvanloef - thanks for reporting this issue with the Log Pull integration. Based on Cloudflare's recommendation, we are currently working on a new Log Push integration (https://github.com/elastic/integrations/pull/3643) which will address the behaviour you're seeing. Cloudflare advise SIEM vendors and users, to rely on Log Push to ingest events, rather than Log Pull. 

The new integration will support ingest via S3 Bucket (recommended) or streaming directly to Elastic Agent. The integration is currently going to some final reviews, but expected to be available very soon. Once available, we'll be recommending that users adopt this new integration over the current Log Pull integration.
