### ISSUE TITLE
[elastic_agent] `agent.*` fields are not mapped

### ISSUE THREAD

**Issue by joshdover** [elastic/integrations#4191]
The ECS `agent.*` fields from the elastic_agent integration are not indexed so they cannot be used for filtering

**Comment by jsoriano** [comment]
For the matter of this integration we could add these fields there if they are known beforehand. Pinging @elastic/elastic-agent-control-plane as owners for this.

In a more general sense, some of these fields are always populated, and we are not always providing a mapping. Related discussions:
* https://github.com/elastic/package-spec/issues/199
* [internal] https://github.com/elastic/ingest-dev/issues/1041

This was not detected by CI because of https://github.com/elastic/elastic-package/issues/147.

**Comment by jen-huang** [comment]
@AndersonQ Hi Anderson, Julien says you could look at this, so assigning to you.
