### ISSUE TITLE
Azure integration doc fixes 

### ISSUE THREAD

**Issue by alaudazzi** [elastic/integrations#4210]
This issue tracks the feedback received during a UX session where the customer found gaps in the Azure docs. 

@zmoog @dedemorton @bmorelli25 @ollyhowell 

The required doc fixes might be easier than we expect. 
I'm happy to make those changes, if you can assist with the technical details.
In particular, we need to update the section [Settings](https://docs.elastic.co/integrations/azure/activitylogs#settings) to be more explicit on how to use these three settings:

**Eventhub** = Needs to specify that this is the main eventhub name. Do we need to add an error message when they don’t specify the main eventhub name? In Azure, this appears as Event Hubs Namespace. “Event hubs where logs are saved”
**Consumer Group** = Used if you dump all Azure logs into one event hub, then broken out into subgroups. Need more information on this. How does Azure actually use this?
**Connection String** = Connection string for the event hub where the data is actually being stored.

This is some more feedback we collected during the UX session:
Azure Logs integration seems to encompass all the other Azure integrations, but you still have to install each separate Azure integration.
- For each Azure integration, Azure logs integration only works for one. For all other integrations, Azure Logs integration doesn’t work. 
- To get the proper pipeline and categorization, you have to install each separate Azure integration. 
- Azure Logs is used to just ingest Azure logs. This is confusing because the settings are misleading. 
- The Integrations Settings: There needs to be more information about connection strings and what you’re looking for. The event hub can contain other event hubs. The settings are looking for the main event hub, not the sub event hubs. 
These settings need help:
- These integrations are 1:1, not 1 for many. You can’t use this one agent to pull all logs.

CC @KOTungseth 

Relates to https://github.com/elastic/integrations/pull/3907, https://github.com/elastic/observability-docs/pull/2174

**Comment by zmoog** [comment]
Hey @alaudazzi, I agree the changes are not complex, and we can reap most of the benefits without a great effort. I [added some details](https://github.com/elastic/integrations/pull/4149/files#diff-795573d6bce88340e114ba8d18ad32068852486fb18dfd6825865f696c7d5064) in the PR that add the new tenant logs. But we should create a dedicated PR for the significant changes.

Here are a few comments on some of the topics you mentioned.

**Event hub**: this is the most confusing part. Users need to use the "event hub" name and not the "event hub namespace". But there's more: they should use different event hubs per log group for optimal performance and correctness.

**Consumer group**: the agent needs a consumer group name to fetch data from the event hub. Consumer groups are a mechanism we find in most, if not all, the Kafka-style data streaming systems like event hubs. Its purpose is to allow multiple groups of consumers to fetch data at their own pace. It's probably more accessible with an example.

For example, take an event hub called "Orders," where an online shopping website publishes an order every time a customer purchases a product: 

```text                                                   
                                                                                          
                                                                      ┌──────────────────┐
                                                            order:42  │    Logistics     │
                                                                ┌────▶│ <<application>>  │
       ┌──────────────────┐            ┌──────────────────┐     │     └──────────────────┘
       │   online store   │  order:42  │      Orders      │     │                         
       │   <<website>>    │───────────▶│  <<event hub>>   │─────┤                         
       └──────────────────┘            └──────────────────┘     │                         
                                                                │     ┌──────────────────┐
                                                                │     │    Accounting    │
                                                                └────▶│  <<accounting>>  │
                                                           order:42   └──────────────────┘
                                                                                                                                                           └──────────────────┘
```

The downstream application Logistics will connect to the event hub with a consumer group called "logistics," and the Accounting app will connect using a consumer group called "accounting". Each application will receive a copy of each message published to the event hub. 

If Accounting stops processing messages due to maintenance, Logistics can continue. When Accounting is back online, it can resume processing orders where it left before the maintenance. Consumer groups are like a bookmark that says: "this is the last message I fetched when I stopped."

**Feedback session**: the integration named "Azure" should probably have the name "Azure Logs" because it's what it does actually: right now, it focuses on logs only.

**Comment by ollyhowell** [comment]
Thanks for raising this @alaudazzi and volunteering to help write/edit the changes!
We also have an imminent 'learn how to update Integration docs' session planned for when Brandon is back, with folks from Security already signed up - will post in #docs but this will be helpful for anyone interested in the process.

**Comment by alaudazzi** [comment]
@zmoog and I had a great chat on integrations doc! Thank you so much for your time and collaboration!

Here is what we agreed:
- As the customer suggested, explicit instructions on how to use the settings `Eventhub`, `Consumer Groups`, and `Connection String` are known as doc gaps and need to be addressed
- We should also clarify how Azure integrations and data streams actually interact, as the way they are displayed on the Azure Integrations landing page might be confusing
- Maurizio and I are going to work on this together and we should be able to publish the doc fixes in a couple of weeks.
