### ISSUE TITLE
Barracuda Essential Integration

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#4428]
https://discuss.elastic.co/t/request-barracuda-essentials-integration/312828

**Comment by agithomas** [comment]
https://discuss.elastic.co/t/barracuda-rmm-integration/312826

**Comment by WildDogOne** [comment]
I may be able to help with the Barracuda Essentials integration, looks straight forward enough.
But since I don't have barracuda, you would need to collect some syslog packages and attach them to the issue

The Barracuda RMM is a whole different topic, because delivery is via rest API, so I would need to have access to a test system to get this to work.
