### ISSUE TITLE
Istio metrics and dashboards

### ISSUE THREAD

**Issue by gsantoro** [elastic/integrations#4678]
Review the implementation of Istiod_metrics datastream under the Istio Integration according to this [comment](https://github.com/elastic/integrations/pull/4253#discussion_r1026296675).

Related PRs
- https://github.com/elastic/integrations/pull/4253

Related issues
- https://github.com/elastic/integrations/issues/3552

Make sure that the following Criteria are met before releasing to GA:
- [Metricbeat Module / Dataset release checklist](https://github.com/elastic/beats/blob/master/.github/ISSUE_TEMPLATE/module-checklist.md)

Checklist for GA:
* [x] Supported versions are documented
* [ ] Supported operating systems are documented (if applicable)
* [x] Integration tests exist
* [x] System tests exist
* [x] Automated checks that all fields are documented
* [x] Documentation
* [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [x] Dashboards exists (if applicable)
* [ ] Kibana Home Tutorial (if applicable)
  * Open PR against Kibana repo with tutorial. Examples can be found [here](https://github.com/elastic/kibana/tree/master/src/legacy/core_plugins/kibana/server/tutorials). 404 on this link
* [x] Test log files exist for the grok patterns (from Filebeat)
* [x] Generated output for at least 1 log file exists (from Filebeat) 
* [x] Example `data.json` exists and an automated way to generate it exists (`go test -data`) (from Metricbeat)
* [x] Test environment in Docker exist for integration tests (from Metricbeat)
* [x] Rewrite Dashboards from TSVB to Lens [PR](https://github.com/elastic/integrations/pull/5268)

**Comment by gsantoro** [comment]
[Comment](https://github.com/elastic/integrations/pull/4253#discussion_r1026296675) has been addressed with release 0.2.2 and [PR](https://github.com/elastic/integrations/pull/4924)

**Comment by gsantoro** [comment]
Notes on checklist for GA:
- [x] integration and system tests
  - [x] pipelines tests for access_logs datastream
  - [x] system tests for istiod_metrics and proxy_metrics datastream with docker-compose
- [x] dashboard exists
  - [x] dashboard are valid and can be loaded. Checks done by `elastic-package test asset` via jenkins
- [x] Automated checks that all fields are documented
  - [x] all fields in sample_event.json are verified by `elastic-package test static`. [doc](https://github.com/elastic/elastic-package#static-tests)
- [x] documentation in the README
- [x] instead of data.json, we have sample_event.json (one per data stream)
- [x] support version is documented in the readme. Istio 1.14.3

The previou checklist should cover all the checks from beats from this [doc](https://github.com/elastic/beats/blob/master/.github/ISSUE_TEMPLATE/module-checklist.md)

**Comment by gsantoro** [comment]
More checks specific to integrations:
- [x] beats module in GA?
  - [x] istio has a beats module but it doesn't use it for either logs (it uses filestream input) or metrics (it uses prometheus/collector module/metricset)
  - [x] integrations in Beta since Sep 12, 2022
- [x] Have all the data sets been migrated to Integrations as data streams ?
  - [x] Yes. Since with Istio 1.14.3 we don't need as many different datastream. Components like Galley, Citadel, Pilot have been merged into Istiod. The migrated datastream are Proxy and Istiod, which are the only ones necessary. There was no previous module for Istio under filebeat, there is now an access_logs datastream in the integration
- [x] Data stream specific checks
  - [x] All metrics and logs are visible in Kibana UI
  - [x] User can give proper inputs for each stream from the UI (streams.yml.hbs file)
  - [x] Fields.yml, ecs.yml, base-fields.yml presence
  - [x] Data stream dashboards have been imported properly to integrations. Dashboards should not be with snapshot versions of stack
  - [x] pipeline tests (when applicable)
  - [x] System Tests, generation of sample_event.json
  - [x] documentation: fileds, events
- [ ] versions of service
  - [ ] Upgrade to latest version of Istio. Test it and check for errors or new fields
- [ ] kibana version compatiblity (check with all kibana versions that we are supporting)
- [x] Verify Code Owners

**Comment by gsantoro** [comment]
Some optional todo:
- upgrade the integration to Istio 1.16.1
- add new datastream for Istiod service logs. Istiod expose logs which are different from the access logs gathered from Proxy sidecar containers.

**Comment by gizas** [comment]
We have an open PR that summarises best Practises for Dashboards/ Visualisations [here](https://github.com/elastic/integrations/pull/5130#issuecomment-1422599438)

Long story short, the best practise is to transform our visualisations to Lens.

There are specific cases that TSVB can still have features that are not supported in Lens, but those should be considered per individual case. Lets always consider what the main outcome of each dashboard should be and what is the goal we want to achieve. (Relevant [doc](https://docs.google.com/document/d/1uyyFGx6xA5Kvl8c-ZdvXdvBGrHTylxU9F69TGqfzdmw/edit#heading=h.okqsnsmh5edl) - go to section `Use Lens if possible`)

For cloudnative team we had to change existing gauges and either replace them with Pie charts or with bar charts. We chose bar charts (with ad-hoc dataviews) because we wanted to depict the latest status of cluster (see relevant discussion [here](https://github.com/elastic/observability-dev/issues/2318#issuecomment-1313822439))

@gsantoro to answer your question regarding replacement of TSVB gauges, I would try either bar charts or Pie charts (after 8.6) that support latest value filter. We also have another [story](https://github.com/elastic/integrations/issues/5005) in our backlog to investigate  Pie charts and if is possible to use them in Kubernetes General Overview Dashboards. So it will be a win-win if you can use them here as well

**Comment by gizas** [comment]
@gsantoro Reminder to include in new version of dashboards https://github.com/elastic/integrations/issues/4978

**Comment by gsantoro** [comment]
@gizas are you saying that I should do the dashboards update and #4978  in the same PR?

**Comment by gizas** [comment]
Yes, the addition is a small one, why to open 2 prs only for a filter?

**Comment by gsantoro** [comment]
I'm happy to do that but at the same time I have seen some pushback when a PR covers more than a single topic.

**Comment by gizas** [comment]
> I'm happy to do that but at the same time I have seen some pushback when a PR covers more than a single topic.

:) From who ? And I dont think that those two things can be considered as different topics
