### ISSUE TITLE
okta: add configuration options to allow users to make use of httpjson keep-alive options

### ISSUE THREAD

**Issue by efd6** [elastic/integrations#4844]
elastic/beats#34014 will be adding configuration options to httpjson to allow users to specify the behaviour of http keep-alives. This configuration should be made available to integrations that make use of httpjson to perform API requests. A customer has requested that the okta package provide this option to reduce API limit impacts due to the current behaviour that does not allow keep-alives.

Depends: elastic/beats#34014
Depends: elastic/beats#34299
Depends: elastic/beats#34743

**Comment by jamiehynds** [comment]
@efd6 do you think we could get this option added to the Okta integration as part of the 8.8 cycle? For Okta in particular, is there any downsides to enabling the option by default to ensure users don't think rate limits imposed by Okta?

**Comment by andrewkroh** [comment]
I think we should make HTTP keepalives enabled in our integrations. That's the optimal behavior IMO. I know that with the httpjson input we did not want to change the behavior because we didn't know who/what would be affected, but with Okta (and other httpjson based integrations) we know how it's being used and we want to optimize the OOTB experience.

**Comment by efd6** [comment]
Are we never going to be in a situation where resource constraints make this problematic? Would a default enabled be OK or do you specifically want it always enabled?

**Comment by andrewkroh** [comment]
I was thinking keep-alives on by default, but still toggle-able.

**Comment by efd6** [comment]
No worries, I'll invert the default that I have.
