### ISSUE TITLE
[Mimecast] timezone for dlp, ttp_ip, ttp_url, ttp_ap all

### ISSUE THREAD

**Issue by oliver-creed** [elastic/integrations#4906]
the timezone in format for these http streams is set to +0700, i believe this is causing our issue as our logs hours 7 hours delayed when using utc time zone for servers. can this at least be configurable ?

`template execution: evaluated template "[{\"to\": \"2022-12-29T10:45:45+0700\", \"from\":\"2022-12-29T10:40:45+0700\"}]"
`

**Comment by oliver-creed** [comment]
a workaround of switching the servers to use +0700, isn't feasible as it breaks other integrations such as Lastpass. If it has to be hard coded. i think it should be set to UTC?

**Comment by kcreddy** [comment]
> template execution: evaluated template "[{\"to\": \"2022-12-29T10:45:45+0700\", \"from\":\"2022-12-29T10:40:45+0700\"}]" 

Hi @oliver-creed, could you confirm the server time (along with timezone) when this log happened?
Just wanted to see the difference between the `to` and `from` parameters vs. the server timezone.

**Comment by oliver-creed** [comment]
Hi @kcreddy  the server is in utc timezone with and the utc time was 2022-12-29T10:40:45+0000, the +0700 is hard coded in the mimecast integration http input

**Comment by oliver-creed** [comment]
There is the same bug with the Github integration, using a hardcoded value of "+0700", i think this should at least be setable by the  user.

**Comment by oliver-creed** [comment]
@kcreddy - The pull request doesn't fix the bug, as now() gets the local time of the server, so it would not be utc -0700 if the pull request was implemented, if the servers timezone is set to utc. its less of the value being set wrong more of it being set to anything but utc or not being able to configure it.

to me possible fixes are set the integration to get Now local time and normalize to utc and set the timezone to +0000 or use Now() and make the timezone configurable via templeting if possible

**Comment by kcreddy** [comment]
Hey @oliver-creed 
We believe the issue is coming from wrong formatting of the date in `formatDate` function.
What is referred as `+0700` or `-0700` isn't a hardcoded timezone value, but the format of the timezone that Go expects as a numeric timezone format so that it can correctly interpret timestamp value.

For more info: 
[formatDate httpjson input](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-httpjson.html#:~:text=formatDate%3A%20formats%20a,America/New_York%22%20%5D%5D.)

https://pkg.go.dev/time#Date:~:text=Numeric%20time%20zone%20offsets%20format%20as%20follows%3A

**Comment by oliver-creed** [comment]
ah i see, thank you for explaining

**Comment by oliver-creed** [comment]
ah i see!, thank you for explaining, fyi i believe the github integration has the same issue
