### ISSUE TITLE
[Kubernetes] Bug: Kubernetes integration appears to generate multiple tag instances of `Kubernetes` when tagging the assets

### ISSUE THREAD

**Issue by formgeist** [elastic/integrations#4969]
**Kibana version**:

main (8.7.0)

**Description of the problem including expected versus actual behavior**:

When installing the Kubernetes integration, you also install a number of pre-built assets (dashboards, visualizations, etc.) that come with the integration package. When the user navigates to the Dashboards list, multiple of the same tags appear in the tags list. This is a fresh cluster and instance, so no tags were created before installing the integration.

<img width="1356" alt="CleanShot 2022-12-19 at 21 41 51@2x" src="https://user-images.githubusercontent.com/4104278/208521159-b800c1bd-787d-4c99-b6d5-3e1ed85ac06a.png">

**Steps to reproduce**:
 1. Fresh cluster and instance, go to Integrations and install the Kubernetes integration
 2. Once installed, navigate to Dashboard app and look at the list tags to filter the dashboards by.
 3. The list will present duplicates of `Kubernetes` and `Managed` tags.

**Comment by ruflin** [comment]
I'm surprised it is even possible to create the same tag multiple times. I assume somehow these are different Saved objects with different ids. @kpollich Is this an issue specific to the k8s integration or something that should be handled on the Fleet side?

**Comment by kpollich** [comment]
Fleet's asset tagging logic lives here: https://github.com/elastic/kibana/blob/e297cc3061b2b5dfde54284b53a7882ddec4492f/x-pack/plugins/fleet/server/services/epm/kibana/assets/tag_assets.ts

We add by default the `Managed` tag and a tag matching the integration's `title` field to all assets created for a given integration.

**Comment by kpollich** [comment]
@ruflin I'm not sure I understand if there's a meaningful difference between exporting a YML file (or YML field) of tags versus exporting JSON files representing tags from an integration. Here's the integrations I found using tags today for context on what folks are doing today: 

- https://github.com/elastic/integrations/tree/main/packages/kubernetes/kibana/tag
- https://github.com/elastic/integrations/tree/main/packages/gcp/kibana/tag
- https://github.com/elastic/integrations/tree/main/packages/ti_otx/kibana/tag
- https://github.com/elastic/integrations/tree/main/packages/ti_misp/kibana/tag
- https://github.com/elastic/integrations/tree/main/packages/ti_util/kibana/tag
- https://github.com/elastic/integrations/tree/main/packages/ti_cif3/kibana/tag
- https://github.com/elastic/integrations/tree/main/packages/ti_abusech/kibana/tag
- https://github.com/elastic/integrations/tree/main/packages/ti_threatq/kibana/tag
- https://github.com/elastic/integrations/tree/main/packages/ti_cybersixgill/kibana/tag
- https://github.com/elastic/integrations/tree/main/packages/ti_anomali/kibana/tag

Seems like maybe there's a breakdown in knowledge around what tags Fleet generates automatically vs when an integration should include "custom" tags.

**Comment by MichaelKatsoulis** [comment]
I can confirm that for Kubernetes dashboards, the `Kubernetes` and `Managed` tags are added by default in the dashboards. So we did not know that and we had duplicated the tags.

**Comment by ruflin** [comment]
The difference between shipping it as a saved object vs a config option is that Fleet could control the management of tags better. My core assumption is, the same tag (name) should only exist once. It seems that is not something that Kibana restricts, tags with the same name can be created multiple times.

Lets assume we have 2 integrations that add a tag "cloud". My expected behaviour would be that when I filter on "Cloud", I get all the "cloud" dashboards. But because one integration can't necessarily use the tag of the other integration, we will end up with 2 tags "cloud" and the user does not have a single tag to filter.

If there would be a config option `tags: [cloud]` it would be Fleet that ensures a tag only exists once and as soon as all packages / dashboards are removed that use this tag, it is also cleaned up.

> Seems like maybe there's a breakdown in knowledge around what tags Fleet generates automatically vs when an integration should include "custom" tags.

Agree.

**Comment by kpollich** [comment]
Filed https://github.com/elastic/integrations/pull/4979 to add some developer-facing docs about the autogenerated `_meta` property for assets as well as the Kibana SO tags Fleet creates.

**Comment by MichaelKatsoulis** [comment]
Interesting finding is that the duplication has happened due to the dashboard development process.
If we don't specify any tag in the dashboards yaml then the dashboards take as default the `integration_name` and `managed` tags. So far so good.

After updating the dashboards on Kibana and then using `elastic-package export dashboards` to get the dashboards locally in order to commit the changes, the assets returned from the command include the tags as well. 
This means that next time we upload the dashboards to Kibana they get the tags from the dashboards yamls (returned from elastic package tool), plus the defaults added by Fleet. 
So then we have the same tags two times. 
And if we export them again the tool will return the duplicated tags. So next time we upload them we will have 3 times the same tags and so on. 

This needs to be fixed.
cc @ruflin , @gizas

**Comment by ruflin** [comment]
> And if we export them again the tool will return the duplicated tags. So next time we upload them we will have 3 times the same tags and so on.

@elastic/ecosystem This is something we should address as otherwise we keep having more and more duplicated tags by accident.

**Comment by jsoriano** [comment]
@MichaelKatsoulis @ruflin could you please create an issue in `elastic-package` repo describing the issue with `elastic-package export` and the expected behavior?

**Comment by MichaelKatsoulis** [comment]
> could you please create an issue in elastic-package repo describing the issue with elastic-package export and the expected behavior?

Will do that

**Comment by MichaelKatsoulis** [comment]
@formgeist  this issue is addressed by https://github.com/elastic/integrations/pull/4972 and fixed on Kubernetes integration side. There is still an issue open in ecosystem team to fix the root cause.
Should we close this one? The title refers to Kubernetes integration generating multiple tags, which  is fixed

**Comment by formgeist** [comment]
@MichaelKatsoulis Yes, we can close this one - thanks for the fix!
