### ISSUE TITLE
Migrate Kubernetes integration

### ISSUE THREAD

**Issue by masci** [elastic/integrations#511]
# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows [development guidelines](https://github.com/elastic/integrations/tree/master/doc/development/guidelines)
- [x] Supported versions of the monitoring target are documented
- [x] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist https://github.com/elastic/integrations/pull/569
- [x] Documentation exists
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to: `kibana.version: ">=7.11.0"`

Migration Assessment: https://github.com/elastic/obs-dc-team/blob/master/migration/packages/kubernetes.md

**Comment by ChrsMark** [comment]
Just to note that the testing/CI support for this is not yet landed: https://github.com/elastic/elastic-package/issues/89

**Comment by pguan-phl** [comment]
Not sure if it's proper to post it here, just want to mention that I see this `there's a complete example manifest available in <<TODO: link to the proper page here>> document.` in the Kubernetes integration page (v 7.10.1), and in the [README](https://github.com/elastic/integrations/blob/master/packages/kubernetes/docs/README.md)
Guess it's too minor to have a separate ticket, so I'm just reporting here.

Also BTW, can I ask is v8.0.0 the minimal version to use this integration? Cause I see this 8.0.0-SNAPSHOT from this file: https://github.com/elastic/integrations/blob/master/testing/environments/kubernetes/agent.yml . I'm asking because my es-stack is v7.10.1 and I don't have a clue whether to downgrade to use elastic-agent:7.x or upgrade the whole stack.

**Comment by ChrsMark** [comment]
@pguan-phl thank's for reporting this one! I have updated the package at https://github.com/elastic/integrations/pull/528 to point to the current manifest file.

Regarding versions, you can use an `elastic-agent:7.x` if you want since the testing files you pointed are just for testing/reference and are not tightly coupled with specific versions.

**Comment by ChrsMark** [comment]
Tested manually combining [latest version of package](https://github.com/elastic/integrations/pull/680) and [Elastic-Agent-Standalone](https://github.com/elastic/beats/pull/23679). After https://github.com/elastic/integrations/pull/680 is merged I think we can consider migration as done, close this issue keep track of further improvements/work at https://github.com/elastic/integrations/issues/601, @masci are you ok with this?

**Comment by masci** [comment]
Agree, if you tested #680 let's close this when it gets merged. Thanks @ChrsMark !
