### ISSUE TITLE
[ AWS ] Cloudwatch Logs duplicated fields.

### ISSUE THREAD

**Issue by leandrojmp** [elastic/integrations#5114]
Hello,

I'm using a couple of AWS integrations to consume only the Cloudwatch Logs for a couple of log groups and noticed that some information is being saved in two fields with similar names.

The fields are:

- `aws.cloudwatch.ingestion_time`
- `aws.cloudwatch.log_group`
- `aws.cloudwatch.log_stream`

Which are also being saved as the following fields:

- `awscloudwatch.ingestion_time`
- `awscloudwatch.log_group`
- `awscloudwatch.log_stream`

![erro-aws-integration](https://user-images.githubusercontent.com/322886/214874866-11f69d95-7ebd-41c8-b50a-f1d6b3541576.png)

Where I can change that? I couldn't find an ingest pipeline that create those fields.

**Comment by legoguy1000** [comment]
`awscloudwatch.*` fields are created by the cloud watch input not by the ingest pipelines

**Comment by leandrojmp** [comment]
@legoguy1000 Yeah, I saw it later, but if this is not a bug it should be removed using an Ingest pipeline.

According to this [PR](https://github.com/elastic/beats/pull/31488) on the Filebeat repository the `awscloudwatch.*` fields should not exist, I would assume that this is how the Elastic Agent should behave as well.

Not sure if the `filebeat` part of Elastic Agent uses the same code as the stand-alone Filebeat, but it seems that it does not.

**Comment by legoguy1000** [comment]
It should buy looks like it was only in 8.2+. What version of the agent are u using?

**Comment by leandrojmp** [comment]
@legoguy1000 I'm on `8.5.1`.

What is werid is that the PR mentioned in the previous comment should rename `awscloudwatch.*` fields to `aws.cloudwatch.*` fields, but I'm getting both.

**Comment by legoguy1000** [comment]
Looks like it was just added, not replaced. https://github.com/elastic/beats/blob/v8.5.1/x-pack/filebeat/input/awscloudwatch/processor.go#L63.

**Comment by leandrojmp** [comment]
Oh, makes sense, I just looked at the name of the PR and assumed that the fields were being renamed, not duplicated.

Not sure if it is intentional or not, but I will add a processor to remove the duplicated field until Elastic fix this or decides it is not an issue.

**Comment by aspacca** [comment]
hello @leandrojmp
the introduction of `aws.cloudwatch.*` payload was meant to unify the specific AWS sources metadata across different elastic ingestion products (ie: Elastic Agent, Filebeat, Elastic Serverless Forwarder, etc).

Not dropping the old `awscloudwatch.*` one was intentional, since there might be users relying on them: the entry in the changelog specify that's a duplication https://github.com/elastic/beats/commit/c0b3d5bf10d73c6febf2e1c8cd128399fb2133b4#diff-867eb8a32d99eda9bb244b7b86d7abd0031618bae71d0276fe139fe697c3063dR54 :)

The older one were marked as deprecated as well: https://github.com/elastic/beats/commit/c0b3d5bf10d73c6febf2e1c8cd128399fb2133b4#diff-0078d1ec55d764408e26baf72301ef6d64ad871b081a95bb148fbbfd4b52c421R2038

We'll reserve to totally remove them in future releases.

**Comment by leandrojmp** [comment]
Thanks @aspacca, I will remove it until it is removed by the agent on a future release.

**Comment by leandrojmp** [comment]
hello again @aspacca,

just opened another issue related to this because the `aws` field should be a json object, currently the `aws.cloudwatch` is a field where the dot is part of the name and this can lead to confusion as it is expected that a dot would mean another level in the nested object.
