### ISSUE TITLE
[Snyk] Support Dynamic Retrieval of Audit Logs for All Orgs

### ISSUE THREAD

**Issue by SpencerLN** [elastic/integrations#5360]
Currently, the Snyk audit logs integration only ingests data for a single Snyk org, as specified by the `var.audit_id` field. In our case, we have ~30 Snyk orgs that we want to ingest the audit logs for. Instead of needing to configure the integration 30 times, it would be ideal if we could have the integration call the `GET /orgs` API and then dynamically retrieve audit logs from all of the orgs that the user has access to.

If the dynamic approach isn't feasible, providing a field that accepts a list of org IDs to retrieve audit logs for would still be significantly better than the current implementation.

**Comment by P1llus** [comment]
Based on some initial thought, we could modify the snyk audit datastream with the following:

1. Add a UI toggle button to "collect from all related organizations" and default it to false (current behavior)
2. In the .yml.hbs file, we add a if condition bracket around the existing httpjson config.
3. We add a second httpjson config, that is almost the same as the above, but which uses chains (and orgId is not a required parameter anymore). We create another if bracket around this one, so that it uses only one or the other based on the UI toggle.
4. The only modification neede for the second httpjson config, is a chain call to : https://snyk.docs.apiary.io/#reference/organizations/the-snyk-organization-for-a-request/list-all-the-organizations-a-user-belongs-to

Then iterate over the `orgs:` array, and make the exact same httpjson request for each item in the array, with the orgId added to the URL :)

**Comment by jamiehynds** [comment]
@chemamartinez mind if I assign to you to tackle as you work on the Snyk API migration?

**Comment by chemamartinez** [comment]
Sure! I'll take a look at this at the time we tackle the API migration. I'll keep you posted.

**Comment by efd6** [comment]
In principle this is doable, and I have CEL code now for both the new audit_logs and issues endpoints that could be made to use the set of [orgs](https://apidocs.snyk.io/?version=2024-04-29#get-/orgs) that a user has access to. What I am concerned about here is how we handle state retention over reboots. Essentially we will need to retain a cursor state for each of the orgs. These states are updated on each successful request to the API for that org. The question becomes how to we ensure that stale states (orgs that no longer exist or no longer exist from the perspective of the user) do not persist indefinitely in the cursor store. I think this is achievable, but it needs thought.

**Comment by jamiehynds** [comment]
@SpencerLN the Snyk integration has been updated to 1.25.0 and includes support for dynamic retrieval of audit logs for all orgs, if you want to test it out.
