### ISSUE TITLE
Cisco FTD Component Template Maps `cisco.ftd.security` as `flattened`

### ISSUE THREAD

**Issue by MakoWish** [elastic/integrations#5769]
I have never noticed this in the past, but we have a security investigation under way, and we need to aggregate our FTD logs by a few of the sub-fields under `cisco.ftd.security`. Unfortunately, this field is mapped as `flattened`, and this is preventing any aggregations from happening. 

I just tried in our DEV system to change from `flattened` to explicitly-mapped fields for `cisco.ftd.security.*`, rolled the data stream over, and it does unfortunately break older indices with the previous `flattened` mapping. 👎 

```
illegal_argument_exception
error fetching [cisco.ftd.security.first_packet_second]: Field [cisco.ftd.security.first_packet_second] of type [flattened] doesn't 
support formats.
```

I guess the only non-breaking option would be to parse those out to a different field? Would love to hear some thoughts on this. 

Eric

**Comment by LaZyDK** [comment]
This has been discussed before in [issue 2621](https://github.com/elastic/integrations/issues/2621)

**Comment by MakoWish** [comment]
Yeah, that issue was closed, but I feel this still needs a resolution. The OP's situation is exactly what we are facing. 

Eric

**Comment by MakoWish** [comment]
Yeah, that issue has been closed, but I feel this still needs to be resolved. We are facing the same issue as the OP on that one. 

Eric

**Comment by LaZyDK** [comment]
Hey @MakoWish 
With these changes, most of the fields in cisco.ftd.security is mapped to an ECS field. #6322
Do you really need that the field `cisco.ftd.security.first_packet_second`?

**Comment by MakoWish** [comment]
@LaZyDK, 

I missed that you replied here. We would just like the ability to aggregate fields under `cisco.ftd.security.*`, but it is flattened, so we are unable to do that. What version of the integration are those fields supposed to be mapped out to ECS? I see it was merged two weeks ago.

**Comment by jamiehynds** [comment]
This flattened field continues to come up, and based on user feedback the following fields could be explicitly mapped. Adding to our internal planning board for discussion. 

cisco.​ftd.​security.​ac_policy
cisco.​ftd.​security.​access_control_rule_action
cisco.​ftd.​security.​access_control_rule_name
cisco.​ftd.​security.​application_protocol
cisco.​ftd.​security.​client
cisco.​ftd.​security.​client_version
cisco.​ftd.​security.​connection_duration
cisco.​ftd.​security.​dns_query
cisco.​ftd.​security.​dns_record_type
cisco.​ftd.​security.​dns_response_type
cisco.​ftd.​security.​dns_ttl
cisco.​ftd.​security.​dst_ip
cisco.​ftd.​security.​dst_port
cisco.​ftd.​security.​egress_interface
cisco.​ftd.​security.​egress_zone
cisco.​ftd.​security.​first_packet_second
cisco.​ftd.​security.​http_referer
cisco.​ftd.​security.​http_response
cisco.​ftd.​security.​icmp_code
cisco.​ftd.​security.​icmp_type
cisco.​ftd.​security.​ingress_interface
cisco.​ftd.​security.​ingress_zone
cisco.​ftd.​security.​initiator_bytes
cisco.​ftd.​security.​initiator_packets
cisco.​ftd.​security.​nap_policy
cisco.​ftd.​security.​original_client_src_ip
cisco.​ftd.​security.​prefilter_policy
cisco.​ftd.​security.​protocol
cisco.​ftd.​security.​referenced_host
cisco.​ftd.​security.​responder_bytes
cisco.​ftd.​security.​responder_packets
cisco.​ftd.​security.​src_ip
cisco.​ftd.​security.​src_port
cisco.​ftd.​security.​tunnel_or_prefilter_rule
cisco.​ftd.​security.​url
cisco.​ftd.​security.​url_reputation
cisco.​ftd.​security.​user_agent
cisco.​ftd.​security.​web_application

**Comment by P1llus** [comment]
@MakoWish Indeed it has been discussed before, the reason it has to stay flattened is because it also includes an unknown amount of fields, often undocumented (and I believe also custom fields?), so there is no other choice than to keep it flattened.

That does not mean that the user experience could be better, and for the customers I speak to which are in situations like this (there is a very small amount of integrations in this situation), is to utilize the `@custom` pipeline and field mapping component templates to move the fields you want out of the flattened object, which also allows you to map it to the correct type.

Initially the first step would be to provide better documentation in the integration specifically for this field, so that any user can easily do the correct actions to retrieve the fields they want.

On the topic of changing it from flattened breaking older indices, this would always happen for any index as long as the specific field has changed its type, its not possible to change types on old indices in general, and you cannot aggregate or fetch the same field when some indices that are hit on the choosen time range has a different field type.

I don't see any issue with providing a good general list of fields we want to move out of flattened, we do that with for example crowdstrike today. If the list mentioned by @jamiehynds above is good, and you don't see any missing, we could try to rename those out of the flattened object and into a specific mapping (we might lack good sample values for the fields to determine type though, would you be able to assist with some of the fields?)

**Comment by MakoWish** [comment]
Hi @P1llus ,

I pulled 1,000 documents where `cisco.ftd.security` exists, and I deduplicated all the sub-fields. Here is what I came up with:

ac_policy
access_control_rule_action
access_control_rule_name
access_control_rule_reason
application_protocol
client
client_version
connection_duration
dns_query
dns_record_type
dns_response_type
dns_ttl
dst_ip
dst_port
egress_interface
egress_zone
file_action
file_count
file_direction
file_name
file_policy
file_sandbox_status
file_sha256
file_size
file_type
first_packet_second
http_referer
http_response
icmp_code
icmp_type
ingress_interface
ingress_zone
initiator_bytes
initiator_packets
nap_policy
prefilter_policy
protocol
referenced_host
responder_bytes
responder_packets
sha_disposition
spero_disposition
src_ip
src_port
ssl_actual_action
ssl_certificate
ssl_expected_action
ssl_flow_status
ssl_policy
ssl_rule_name
ssl_server_cert_status
ssl_server_name
ssl_session_id
ssl_ticket_id
ssl_version
sslurl_category
tunnel_or_prefilter_rule
uri
url
url_category
url_reputation
user
user_agent
web_application

**Comment by P1llus** [comment]
Thats great @MakoWish , much appreciated! Any idea about some field value examples? Its mostly to understand what sort of logic is needed for a field. If its a number but should be a string etc, or if "url" includes the whole domain and Uri and so on.

That gives us the best mapping experience and we can map them to correct ECS fields easier.

**Comment by MakoWish** [comment]
Updated with some sample values and suggested field types.
