### ISSUE TITLE
Shard error when event.created field is mapped as a keyword

### ISSUE THREAD

**Issue by chemamartinez** [elastic/integrations#5952]
### Description

When an integration doesn't have any mapping for the field `event.created`, it is defined as `keyword` instead of `date`. This leads to a shard failure when navigating through the general Discover.

![image](https://user-images.githubusercontent.com/29475387/233619211-424a8687-1c1d-4ebb-98bf-4cfc640beadf.png)

This issue appeared at https://github.com/elastic/integrations/pull/5890 while moving the Journald integration to an input package, and was solved by mapping the field in the integration itself. However, this raises some questions:

- Do we have or should we include any system test that can detect this sort of issue?
- Would it be a better approach to map the field globally? an example of this is `event.ingested`.
<img width="686" alt="image" src="https://user-images.githubusercontent.com/29475387/233621541-2254dcbe-9195-4bd6-997b-f7dca6c593b1.png">

- Could this affect to other fields?

### Related issues

- https://github.com/elastic/integrations/issues/5869
- https://github.com/elastic/integrations/issues/2286

**Comment by P1llus** [comment]
I wonder if event.ingested is added globally (or using the final pipeline), if event.created is always there, then I don't see why we would need to map it in each integration, so I totally agree on that approach. Looking at both open and closed issues, there are several cases in which this cases problems.

Another issue is indeed that the CI does not catch this, since the error does not seem to be returned to beats when the data is created, but rather on search time when hitting the shards?

**Comment by kcreddy** [comment]
> I wonder if event.ingested is added globally (or using the final pipeline)

Its added inside the final pipeline as per [this](https://github.com/elastic/kibana/blob/main/x-pack/plugins/fleet/server/constants/fleet_es_assets.ts/#L99)

**Comment by ebeahan** [comment]
> Do we have or should we include any system test that can detect this sort of issue?

`elastic-package` does detect undefined fields. For example, I deleted a field in the Crowdstrike integration and ran the tests:

```
--- Test results for package: crowdstrike - START ---
FAILURE DETAILS:
crowdstrike/fdr test-fdr.log:
[0] field "crowdstrike.AgentTimeOffset" is undefined
```

However I deleted several externally defined fields (`external: ecs`) and didn't see failures reported. Is this a known limitation?

**Comment by efd6** [comment]
@ebeahan Depending on what you remove you will see complaints or not; the test images run packages like system that will have already provided field definitions, so they will mask missing field definitions in a tested package. For example, I just deleted a bunch from Crowdstrike (dss through to host in the field/ecs.yml). This was the result:
```
crowdstrike/fdr test-fdr.log:
[0] field "dns.question.name" is undefined
[1] field "dns.question.registered_domain" is undefined
[2] field "dns.question.subdomain" is undefined
[3] field "dns.question.top_level_domain" is undefined
[4] field "dns.question.type" is undefined
[5] field "dns.type" is undefined
[6] field "ecs.version" is undefined
[7] field "file.device" is undefined
[8] field "file.directory" is undefined
[9] field "file.extension" is undefined
[10] field "file.hash.sha256" is undefined
[11] field "file.inode" is undefined
[12] field "file.name" is undefined
[13] field "file.path" is undefined
[14] field "file.size" is undefined
[15] field "file.type" is undefined
```
Note that `host.*` is not undefined because the Elastic Agent and System packages define them, but they don't define anything in e.g. `file.*`.

**Comment by andrewkroh** [comment]
> When an integration doesn't have any mapping for the field event.created, it is defined as keyword instead of date

`event.created` is now covered by the ecs@mappings component template (added to all data streams). So this field should always get a mapping to `date` as of 8.13.0.
