### ISSUE TITLE
[Tenable IO] Several Bugs in Experimental Integration

### ISSUE THREAD

**Issue by MakoWish** [elastic/integrations#6147]
## Type of Issue

Bugs

## Descriptions

1. The Tenable IO integration currently comprises three datasets: asset, plugin, and vulnerability. Each of these datasets currently leverage the [Fingerprint processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/fingerprint-processor.html) to create the document's `_id` field. With standard indices, this would allow an existing document to be updated/overwritten, but with Data Streams, documents cannot be updated/overwritten. This is causing updated documents to fail at ingest, so as assets, plugins, or vulnerabilities are updated in Tenable, those updates will never be reflected in Elastic. 
2. The `@timestamp` field is also being set by the Tenable object's creation time. This is causing all documents' timestamps to be marked as the time the object was created, so regardless of an object being updated, you may have to look back months or years in Elastic to observe the object. For instance, if an object was created three years ago in Tenable, you will need to set Kibana's time window back three years to see that object.
3. The `host.name` and `host.hostname` fields seem to be used backward, and duplicates are being created with uppercase and lowercase versions of each. 
4. `host.domain` is being set as the hostname instead of the domain name.
5. Host names are being added to `related.ip`, and IP addresses are being added to `related.hosts`
6. Beats agents and other Integrations keep the standard ":" separators for MAC addresses, but this Integration is replacing ":" with "-". 

## Proposals

1. The Fingerprint processor should be removed to allow updated documents to be ingested as new documents. This will also require modifying the existing dashboards to leverage "last value" or "top hit" aggregations to reflect the current state of each document, as well is utilizing "unique count" instead of just a simple "count". 
2. The `@timestamp` field should just be the time the document was ingested, so the use of the Tenable object's creation as `@timestamp` should be removed from the Ingest Pipeline. 
3. Change the setting of `host.name` to be the basic host name like "Server1" and `host.hostname` to be the FQDN if available. Standardize the case on `host.name` and `host.hostname`. 
4. Change the setting of `host.domain` to use the actual domain instead of the host name. 
5. Remove `append` processors assigning host names to `related.ip` and IP addresses to `related.hosts`
6. Remove the gsub processors that are replacing ":" separators with "-" separators.

**Comment by efd6** [comment]
Query/comments mapped to you proposals:

1. Can we use the update timestamps in tenable document if it exists, falling back to the creation timestamp?
2. If we can use update timestamps that would be preferable, ingest time is subject to system effects that make it difficult to correlate across clusters if necessary.
3. There are guidelines for [`host.name`](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-name) (lowercased FQDN) and [`host.hostname`](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-hostname) (leave as is since we don't know better than the provider).
4. Probably the `registered_domain` processor should be used; care is required to correctly handle domains.
5. Ensuring only IPs end up in `related.ip` can be done with something like this:
    ```
    - foreach:
        description: Ensure related.ip type
        field: related.ip
        processor:
            convert:
                type: ip
                field: "_ingest._value"
                on_failure:
                  - append:
                      field: _failed_ips
                      value: "{{_ingest._value}}"
        ignore_missing: true
    - script:
        lang: painless
        source: ctx.related.ip.removeAll(ctx["_failed_ips"]);
        if: ctx.related?.ip != null && ctx["_failed_ips"] != null;
    - remove:
        field: _failed_ips
        if: ctx._failed_ips != null
    ```
    The `related.hosts` may contain IPs since an IP address is a host identifier, so this can be left as is.
6. The `gsub` processor for the HW address is required for [ECS compliance](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-mac).
