### ISSUE TITLE
M365 Defender Broken Assets with change from m365_defender.event -> m365_defender.incident

### ISSUE THREAD

**Issue by brentcox820** [elastic/integrations#6192]
Elastic Agent integration for M365 Defender Assets are broken as the field names have changed since microsoft changed the field from Event to incident. 

The previous ticket updated the alerts but it did not create the new assets so they are all still using the **m365_defender.event.severity** instead of m365_defender.event.severity

All Assets and searches are using the  m365_defender.event data set and needs to be updated. 

This is using the most recent 1.8 version of the integration. 

![image](https://github.com/elastic/integrations/assets/67185325/3fd4d3f5-1131-40a1-80b4-277104f20566)

![image](https://github.com/elastic/integrations/assets/67185325/4ae7538b-836e-4bd2-a0cd-83c9c47888ae)

**Comment by efd6** [comment]
@brentcox820 Are you able to provide some example event inputs for testing? Also can you clarify this

> The previous ticket updated the alerts but it did not create the new assets so they are all still using the m365_defender.event.severity instead of m365_defender.event.severity

Do you mean "they are all still using the m365_defender.event.severity instead of m365_defender.*incident*.severity"?

I'm a little concerned about changing the terms in the dashboards since that would break the dashboards for historical data. Is there a reason that we could not rename the m365_defender.incident group to be m365_defender.event instead? This would leave the dashboards unaltered and allow comparison between new and historical date ranges.

**Comment by P1llus** [comment]
I am a bit unsure if this is not simply a misunderstanding. The m365 Defender Integration has 3 datastreams:
1. Log (which is the old one).
2. Incident (Which is the replacement for Log, which uses Graph API).
3. Event, which is the raw event streams from Event Hub.

Are you sure there is just not some confusion around this?
