### ISSUE TITLE
[Apache Tomcat] Add ThreadPool Metrics datastream

### ISSUE THREAD

**Issue by milan-elastic** [elastic/integrations#6387]
Provide the support of **Threadpool** metrics to existing [Apache tomcat integration](https://github.com/elastic/integrations/tree/main/packages/apache_tomcat). 

# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [x] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md)
- [x] Supported versions of the monitoring target are documented
- [x] Supported operating systems are documented (if applicable)
- [x] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [x] Documentation exists, [useful guidelines](https://github.com/elastic/integrations/blob/main/docs/documentation_guidelines.md) to follow
- [x] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [x] At least a manual test with ES / Kibana / Agent has been performed.
- [x] Required Kibana version set to: 8.8.0
- [x] TSDB enablement for the data stream

### Dashboards changes

- [x] Dashboards exists
- [x] Screenshots added or updated
- [x] Datastream filters added to visualizations

### Metric dataset changes

_This entry is currently only recommended. It will be mandatory once we provide better support for it._

- [x] Sample event (`sample_event.json`) exists

### Meta issue

- #5200 

### Related PR

- #6609

**Comment by harnish-elastic** [comment]
Based on @agithomas suggestions, we have created the horizontal and vertical stacked bar charts. Please refer the below screenshots
![horizontal stacked](https://github.com/elastic/integrations/assets/118714680/98fa7a38-3d02-4ea6-b8dc-348bbf547733)
![vertical stacked](https://github.com/elastic/integrations/assets/118714680/42ebde1d-c910-439b-a8c0-accd8bdb3264)

However user might be confused because of the y-axis. As per screenshots the values are under 1GB but the Y-axis is going to 2.50GB and user needs to always hover the chart to see the actual value at particular time.

As per the proposed chart, user can able to see the exact range in Y-axis and user can have idea related to what the actual values are present in particular time. Please refer the below screenshot.
![mixed axis](https://github.com/elastic/integrations/assets/118714680/fbdcba26-1d27-4673-9374-7537878cb046)

Based on discussion with @agithomas and @SubhrataK, we are going with the proposed chart which has the line graphs for max, init and commited, and the bar graph for the Used memory.

**Comment by harnish-elastic** [comment]
As discussed with the @SubhrataK, instead of creating gauge chart for connection count, we can capture connection count over time for better visibilities. Hence we are going with the suggested line and area chart.

Proposed: ![gauge](https://github.com/elastic/integrations/assets/118714680/97083508-d8a4-40f4-a32b-2a5d2796caf4)

Suggested: ![line and area](https://github.com/elastic/integrations/assets/118714680/ec598b23-792c-4433-88aa-f70497effc45)

**Comment by harnish-elastic** [comment]
[PR](https://github.com/elastic/integrations/pull/6609) is approved and merged.
