### ISSUE TITLE
Support StatsD Input in Elastic Agent

### ISSUE THREAD

**Issue by masci** [elastic/integrations#639]
# Integration release checklist

This checklist is intended for integrations maintainers to ensure consistency
when creating or updating a Package, Module or Dataset for an Integration.

### All changes

- [ ] Change follows the [contributing guidelines](https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md)
- [ ] Supported versions of the monitoring target are documented
- [ ] Supported operating systems are documented (if applicable)
- [ ] Integration or [System tests](https://github.com/elastic/elastic-package/blob/master/docs/howto/system_testing.md) exist
- [ ] Documentation exists
- [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
- [ ] At least a manual test with ES / Kibana / Agent has been performed.
- [ ] Required Kibana version set to:

**Comment by TPXP** [comment]
Hello,

This would help us a lot!
We're trying to use the Elastic Agent on our stack to get data from Traefik servers. Ideally, we'd like to leverage Traefik uptime checks to generate metrics and generate alerts if some servers are down. The `health` metric is too broad in this case, since it only tells global metrics.

Traefik v2 is able to send per-service metrics to a StatsD server, as explained in [their documentation](https://doc.traefik.io/traefik/observability/metrics/statsd/). If we could configure the agent running on the machine to listen to those events that would be great!

In the meantime, I guess we'll just configure the statsd module manually 😢

**Comment by TPXP** [comment]
Update in case anyone ends up trying to use StatsD for Traefik metric collection: Since StatsD does not have metric labels, you can't know which service metrics belong to, which is a problem for us.

The Prometheus exporter is much more complete, and has an Elastic Agent integration. We used it in the end to collect service metrics from Traefik and it works great!

In case you have a service that only exports metrics to a StatsD server, you can always spin a metricbeat on a separate instance and make all your servers send StatsD metrics to it. You'd have to maintain it, but at least it's only one server.
