### ISSUE TITLE
[zscaler_zia] Integration - Web Log ECS fields 

### ISSUE THREAD

**Issue by Androulakakis** [elastic/integrations#6403]
Hello,

The "Zscaler response format (v2)" NSS output feed section in: 
https://github.com/elastic/integrations/tree/main/packages/zscaler_zia 
is not up to date with the latest ingest pipeline in: https://github.com/elastic/integrations/blob/main/packages/zscaler_zia/data_stream/web/elasticsearch/ingest_pipeline/default.yml
Additional fields are added to the pipeline like "ehost", "cintip" and others that are not included in the NSS feed output guide. 

Regarding the pipeline.

**Suggested changes**:

Since "ehost" is essentially the destination domain, it would be best to map it on "destination.domain"
- rename:
      field: json.ehost
      ~~target_field: zscaler_zia.web.encoded_host~~
      target_field: destination.domain
      ignore_missing: true

- rename:
      field: json.filetype
      ~~target_field: zscaler_zia.web.file.type~~
      target_field: file.type
      ignore_missing: true  

- rename:
      field: json.devicehostname
      ~~target_field: zscaler_zia.web.device.hostname~~
      target_field: host.name
      ignore_missing: true

Furthermore, I believe you've mixed up the public with private IP addresses here.
Shouldn't source.nat.ip be the public and source.ip be the private IP address?
https://help.zscaler.com/zia/nss-feed-output-format-web-logs
- convert:
     ~~field: json.cip~~
      target_field: source.nat.ip
      if: ctx.json?.cip != ctx.json?.cintip
      type: ip
      ignore_missing: true
- convert:
      ~~field: json.cintip~~
      target_field: source.ip
      type: ip
      ignore_missing: true

**Suggested additions** (fields useful for detection and security investigations):

| NSS output field  | ECS field |
| ------------- | ------------- |
| %s{bamd5}  | hash.md5  |
| %s{filename}  | file.name  |
| %s{filesubtype}  | file.extension  |
| %d{clt_sport}  |  client.port  |
| %s{upload_fileclass} | zscaler_zia.web.file.class  |
| %s{upload_filetype}  | zscaler_zia.web.file.type  |
| %s{upload_filename} | zscaler_zia.web.file.name  |
| %s{upload_filesubtype} | zscaler_zia.web.file.sub  |

**Comment by piyush-elastic** [comment]
@Androulakakis thanks for you suggestions regarding ECS mapping for `field: json.devicehostname` , but in other data streams we have already mapped that to `host.hostname` , so to maintain the consistency we have mapped that to `host.hostname`.

**Comment by piyush-elastic** [comment]
@Androulakakis regarding your next comment `Furthermore, I believe you've mixed up the public with private IP addresses here.
Shouldn't source.nat.ip be the public and source.ip be the private IP address?
` - We mapped these fields into `source.nat.ip` and `source.ip` accordingly since the `cip` field includes the private IP (Internal IP) and the `cintip` field contains the public IP. Additionally, when any internal IP address is exposed, both fields do not have the same value. As per given description in attached table on same link you have mentioned. Let me know your thoughts on this.
![Screenshot 2023-06-23 142849](https://github.com/elastic/integrations/assets/124337008/85cdf5d3-66b2-4bc2-91f1-64d5dfd5f1fb)

**Comment by Androulakakis** [comment]
Hello @piyush-elastic , correct when the internal is exposed (nated) to the internet the fields have different values. 
source.ip will have the private IP and source.nat.ip the public IP.
Thank you for your actions.
