### ISSUE TITLE
[O11y][AWS VPC] Lens Migration

### ISSUE THREAD

**Issue by harnish-elastic** [elastic/integrations#6452]
Manually migrate AWS `VPC` visualizations to the lens in the current Kibana version `8.8.1` itself. 

## Preparation of data for testing
- [x] Use sample_event.json / setup live instance using docker / mock data using a mock server to populate dashboards 

## Migration stats
<html>
<body>
<google-sheets-html-origin>

AWS Billing Dashboards | Before Migration |   |   |   | After Migration |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
  | Maps | Search | Lens | Visualization | Maps | Search | Lens | Visualization
[Logs AWS] VPC Flow Log Overview | 1 | 1 | 0 | 3 | 1 | 1 | 3 | 0

</body>
</html>

## Dashboard : [AWS VPC] Dashboards 
  - [ ] Migrate 3 visualization to the lens.
    - https://github.com/elastic/integrations/pull/6962

## Verification and Validation
  - [x] Verification of functionality remains the same after migration in Kibana
  - [x] Verification of data count of after-migrated visualization with before-migrated visualization in Kibana
  - [x] Verification of Dashboards is not distorted in the supported Kibana version 8.8.1

**Comment by kush-elastic** [comment]
Hi @drewdaemon / @kaiyan-sheng,

While migrating the input control for the `VPC Flow Log Overview` dashboard, found that the input control is using the `aws.s3.bucket.name` field. The issue here is the field is mapped with the `logs-*` index while it is actually present in the `metrics-*` index. Please refer to the below screenshot.
![image](https://github.com/elastic/integrations/assets/89848966/f02e5ea8-e9c0-4f43-b36c-fd27cd97e9c0)

Also found that the dashboard is using all the `logs-*` index related fields. Let me know what should we do in this case!

**Comment by kaiyan-sheng** [comment]
Hmmm good catch, I think `aws.s3.bucket.name` should be added into `logs-*`. Because these vpc flow logs are be ingested using aws-s3 input, which stores S3 bucket name into the document: https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/s3_objects.go#L343-L353 
But I don't see these fields in VPC data stream and also we seem to be missing some config options too. I just create a github issue for this bug: https://github.com/elastic/integrations/issues/6481

**Comment by harnish-elastic** [comment]
> Hmmm good catch, I think `aws.s3.bucket.name` should be added into `logs-*`. Because these vpc flow logs are be ingested using aws-s3 input, which stores S3 bucket name into the document: https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/awss3/s3_objects.go#L343-L353 But I don't see these fields in VPC data stream and also we seem to be missing some config options too. I just create a github issue for this bug: #6481

Hi @kaiyan-sheng, Could you please provide any updates on this issue: #6481? Due to this issue, we are blocked on AWS VPC Lens Migration.
