### ISSUE TITLE
[aws] add explicit mappings for `aws.dimensions.*` fields in metrics integrations

### ISSUE THREAD

**Issue by tommyers-elastic** [elastic/integrations#6601]
metric dimensions are increasingly important as we migrate metrics integrations to TSDS (time series data streams). 

We must not only mark specific fields as metric dimensions, but we must also be mindful of the number of individual dimension fields in the metric document (ES has a hard limit on the number of allowed dimensions). 

many (all?) AWS datastreams include a `aws.dimensions.*` mapping e.g. https://github.com/elastic/integrations/blob/main/packages/aws/data_stream/ebs/fields/package-fields.yml#L12. in addition to these wildcard mappings, we should explicitly name each dimension field we are using to group by e.g. . https://github.com/elastic/integrations/blob/main/packages/aws/data_stream/ebs/fields/fields.yml#L4-L10. this also allows us to specify the individual dimensions for TSDS.

**Comment by tetianakravchenko** [comment]
@tommyers-elastic FYI: cloudwatch data_stream also include `aws.dimensions.*` - https://github.com/elastic/integrations/blob/main/packages/aws/data_stream/cloudwatch_metrics/fields/fields.yml#L4-L8. Also this data_stream include `aws.dimensions.*` twice - in `package-fields.yml` https://github.com/elastic/integrations/blob/main/packages/aws/data_stream/cloudwatch_metrics/fields/package-fields.yml#L12-L15 and in `fields.yml` https://github.com/elastic/integrations/blob/main/packages/aws/data_stream/cloudwatch_metrics/fields/fields.yml#L4-L8.

If possible it would be great to clean up duplicated fields

**Comment by kaiyan-sheng** [comment]
`cloudwatch_metrics` data stream includes `aws.dimensions.*` and I'm keeping it in the `package-fields.yml` file because this data stream is the generic input data stream that can be used to ingest any metrics from CloudWatch. With the flexibility of collecting all metrics, we cannot list all dimension keys from all namespaces supported by AWS CloudWatch. Also we don't have a dashboard for this data stream because of the same reason.
