### ISSUE TITLE
[Linux Integration]: References to text that cant be changed for Linux integration on Kibana UI

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/integrations#668]
Package Version 3.3 

**Changes that wont fix**

-  On Linux Integration detail page, table content having rows with system.* wont be changed and would remain as system entries  due to [elastic/package-spec#51](https://github.com/elastic/package-spec/issues/51), because currently two different groupings are needed for the linux metrics, so one of them is called system metrics.

![image](https://user-images.githubusercontent.com/72375798/107003276-83eb2f00-67b2-11eb-9ea8-1afb2758cb17.png)

- On Edit/Add Linux Integration page, heading Collect system metrics from Linux instances is correct and expected one.

![image](https://user-images.githubusercontent.com/72375798/107003172-5d2cf880-67b2-11eb-95a1-b4e0428199b0.png)

cc @fearful-symmetry  @EricDavisX 

Note: We are just creating this ticket for our test content to match the product for now.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by EricDavisX** [comment]
this was logged to track the expectation that these names are set due to existing field names, and we cannot change them even tho the 'system' citation within the Linux integration is a little confusing.  It is just so we can have it for 'known issues' docs reason.  And, if we can update / track this when we ever change them it would be helpful.  No action expected until changes for some future release come.

**Comment by EricDavisX** [comment]
@fearful-symmetry fyi on above.

**Comment by fearful-symmetry** [comment]
Yah, changing the field names would be a breaking change, so it has to stay the way it is for now, since it's a holdover from pre-fleet metricbeat.
