### ISSUE TITLE
Links in the dashboards from elastic agent integration are not working in a multi space environment

### ISSUE THREAD

**Issue by daverick** [elastic/integrations#6691]
Hi,

elastic agent integration (version 1.8.0)
Elastic Stack 8.8.1

The navigation panel in the dashboards is using markdown with links like `/app/dashboards#/view/elastic_agent-1a4e7280-6b5e-11ed-98de-67bdecd21824`.

If the integration is installed in a specific space, theses links do not works, as these links are resolved to the default space
Others integrations are using links like ` #/view/elastic_agent-1a4e7280-6b5e-11ed-98de-67bdecd21824` to reference the dashboard in the current space.

**Comment by daverick** [comment]
@P1llus

**Comment by matthiasledergerber** [comment]
We have the same issue. Running Elastic-Stack 8.8.1. Suspect this issue occurred after 8.8.0.

Related (further down): [Integration Issue](https://discuss.elastic.co/t/kibana-fleet-high-cpu-load-on-elasticsearch-when-adding-integrations/336729/4)
![image](https://github.com/elastic/integrations/assets/22050363/5cc4f448-dd29-4c03-955e-b4895b32d22d)


Related: [Multiple issues - Fleet integrations across multiple spaces confuses Kibana/Fleet](https://github.com/elastic/integrations/issues/3434)

**Comment by P1llus** [comment]
For the navigational panel, we will look into modifying the markdown links and see if they work for all the usecases, thanks for letting us know!

**Comment by P1llus** [comment]
I tested this myself @nicpenning, however it worked just fine. Are you sure it was on the newest version of the elastic_agent package?

A new PR is coming now to fix some links that might not work on non-default spaces, but except that it should be fine.
If the saved objects do not have the elastic_agent prefix, they were not installed by fleet but rather copied over manually from another space perhaps?

**Comment by BenB196** [comment]
@P1llus I see https://github.com/elastic/integrations/pull/7471 marks this as closed, but the actual changes listed in that PR don't don't the dashboard links (only appears to clean up some new lines). I think a push to that branch might've been missed.

**Comment by nicpenning** [comment]
> I tested this myself @nicpenning, however it worked just fine. Are you sure it was on the newest version of the elastic_agent package?
> 
> A new PR is coming now to fix some links that might not work on non-default spaces, but except that it should be fine. If the saved objects do not have the elastic_agent prefix, they were not installed by fleet but rather copied over manually from another space perhaps?

We didn't copy this dashboard to any space. Out of the box in the default space this is broken. What version of the integration is this fixed?

**Comment by P1llus** [comment]
@BenB196 Yeah sorry about that, certain resources was not included in that PR, as there are certain issues between 8.9 and 8.10 dashboards.

Will update this again soon when I have an update.

**Comment by P1llus** [comment]
> > I tested this myself @nicpenning, however it worked just fine. Are you sure it was on the newest version of the elastic_agent package?
> > A new PR is coming now to fix some links that might not work on non-default spaces, but except that it should be fine. If the saved objects do not have the elastic_agent prefix, they were not installed by fleet but rather copied over manually from another space perhaps?
> 
> We didn't copy this dashboard to any space. Out of the box in the default space this is broken. What version of the integration is this fixed?

There should not be any way for fleet to create assets that is not prefixed with their related integration, so when you mentioned that they are missing the prefix then that would be the only conclusion I could draw, did you check that the elastic agent integration is up2date on the integration page?

**Comment by P1llus** [comment]
Added the updated hyperlinks now @BenB196 , that should be all to allow the links to work if the integration had been installed outside of the default space.

**Comment by nicpenning** [comment]
Looks like we were at 1.10.1, upgraded to 1.11.2 and the problem persists.

Also, this is another example of where the Assets tab is blank:
![image](https://github.com/elastic/integrations/assets/5582679/a31252c2-d725-4628-9475-53b09fded8d2)

**Comment by nicpenning** [comment]
All of the dashboards work, it appears that the navigation is what isn't working.

But this may be a separate issue to what is posted here.

Overview URL : /app/dashboards#/view/ee9d27e9-cd2a-413b-af37-5712b8c2ea4
Overview Shortcut Link : /app/dashboards#/dashboard/elastic_agent-a148dc70-6b3c-11ed-98de-67bdecd21824

**Comment by nicpenning** [comment]
Interesting!

Here you can see that the dashboards were modified yesterday when I upgraded:
![image](https://github.com/elastic/integrations/assets/5582679/d1dfb7d3-c7f8-4cde-b452-962c1e1cb9e2)

When I click on the Overview from this saved object page I get taken to the Overview page which works.

However, the links are still broken there. Here is the raw content in the visualization:

```
**Navigation**

**Agent Health**  

**[Overview](#/dashboard/elastic_agent-a148dc70-6b3c-11ed-98de-67bdecd21824)**  
[Agent Info](#/dashboard/elastic_agent-0600ffa0-6b5e-11ed-98de-67bdecd21824)  
[Agent Metrics](#/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395)  
[Integrations](#/dashboard/elastic_agent-1a4e7280-6b5e-11ed-98de-67bdecd21824)  
[Input Metrics](#/dashboard/elastic_agent-a8192f90-cd3f-11ed-869d-e7dc1b551cd2)  

**Overview**

This dashboard gives an overview of the current overall state and health of all Agents and their related enabled Integrations.

```

I tried reinstalling the Elastic Agent integration but that did not make a difference.

I then tried removing the Elastic Agent integration, however the saved objects persisted. But when I proceeded to install the integration, it shows that all 10 dashboard objects were updated (6 seconds ago). I wonder if there is an error trying to import those. 

The next step is that I manually remove the saved objects because the Uninstall feature of the integration did not remove the saved objects.

After installing the integration the 10 Dashboards were imported, and they still do not work. The URL for the main dashboard changed from:
`/app/dashboards#/view/9ea2d5db-818b-4897-90d4-b8cc39e62f53?_g=h@2294574`
to
`/app/dashboards#/view/8c37ed58-e37f-4958-b937-87b8a7306f17?_g=h@2294574`

Perhaps the Elastic Agent Integration is not the way to rebuild this?

**Comment by nicpenning** [comment]
So it seems that the install for the Integration is not giving it the correct static ID but making a new one every time.

```
{
  "id": "8c37ed58-e37f-4958-b937-87b8a7306f17",
  "type": "dashboard",
  "namespaces": [
    "default"
  ],
  "originId": "elastic_agent-a148dc70-6b3c-11ed-98de-67bdecd21824",
```

**Comment by matthiasledergerber** [comment]
Elastic-Stack 8.10.0 with multiple Kibana Spaces. The Dashboards do work. but when i klick on the link inside a predefied Dashboard i get 404. It seems as the integrated links in the predefined dashboards are broken. For me its the Network Packet Capture Integration. Already tried to reinstall the integration. it works but the dashboard links lead to 404

Here I am inside the DNS Part and i want to jump to DHCP -> 404
![image](https://github.com/elastic/integrations/assets/22050363/d06df4db-2948-4b31-9f76-f604aa596141)

**Comment by nicpenning** [comment]
I am with Matthias here on this one. 

I upgraded to the latest version of the Elastic Agent integration (1.13.0) and yes all the dashboards exist and work when navigating directly to them.

However, all of the table of contents links take you to the 404 page. I have even removed the dashboards entirely and then reinstalled the integration.

This is in the latest Table of contents:
```
**Navigation**

**Agent Health**  

**[Overview](#/dashboard/elastic_agent-a148dc70-6b3c-11ed-98de-67bdecd21824)**  
[Agent Info](#/dashboard/elastic_agent-0600ffa0-6b5e-11ed-98de-67bdecd21824)  
[Agent Metrics](#/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395)  
[Integrations](#/dashboard/elastic_agent-1a4e7280-6b5e-11ed-98de-67bdecd21824)  
[Input Metrics](#/dashboard/elastic_agent-a8192f90-cd3f-11ed-869d-e7dc1b551cd2)  

**Overview**

This dashboard gives an overview of the current overall state and health of all Agents and their related enabled Integrations.
```

Which is probably correct, but my previous statement is some odd behavior where the new dashboards are not getting static IDs but rather dynamic ones which tells me there must be some dashboards with those IDs that exist somewhere else and instead of writing over them they are getting created with new IDs.

If I find the time, I will look to see if other spaces have these Dashboard IDs (not just names) that are outdated and need to be removed.
