### ISSUE TITLE
Populate event.module and event.dataset fields

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#678]
Following on from [this issue](https://github.com/elastic/security-team/issues/780), to discuss the impact of packages on the Security App, we identified that our integrations do not populate event.module and event.dataset by default. 

The Security App relies heavily on these fields to populate overview pages, detection rules and more. Impact on other solutions hasn't been assessed, but could possibly be affected.

I propose that we continue to populate the `event.module` and `event.dataset` fields to ensure backwards compatibility with Beats and minimise impact on our UI/detection rules. 

@mukeshelastic @sorantis any objections to populating these fields across all integrations, and not limiting to security integrations?

**Comment by andresrc** [comment]
I think that this information, with the new index strategy is provided in the `data_stream` fields. I think there was a conversation about whether we should populate both sets fo fields or not, but I don't remember. @ruflin can you provide some info?

**Comment by ruflin** [comment]
Using `data_stream.dataset` to run queries on is much more efficient then using `event.dataset` as it is a constant_keyword. It is ok to keep both around during the 7.x cycle to keep compatibility. But we should make sure the "clean up" things for 8.0 to not have duplicated fields around. It would be nice to already now to switch over because of the performance benefits.

**Comment by andrewkroh** [comment]
We should consider some alternatives that don't require us to update the new packages with fields the lead to less performant queries. Some ideas:

- Take an inventory of what relies on `event.module`/`event.dataset` today. Then update those apps to work with both data_stream and event fields. This may not be optimal from a query perspective b/c you still incur the cost of searching for `event.module`.

- Update legacy data producers to populate `data_stream.dataset`. For example, have Beats create `data_stream.dataset` as a `keyword` rather than `constant_keyword` due to the existing indexing model and populate it with the event.dataset value. Even if we did this there would probably still be user managed data sources (or old archived data) that aren't updated so we might still need the first bullet point to ensure those aren't broken.

**Comment by andrewkroh** [comment]
I found that in July 2020 in https://github.com/elastic/beats/pull/20076 Elastic Agent started adding `event.dataset` to all events. Nothing that I found declares this field in a mapping so this means that it's getting its keyword type assignment dynamically.

If we can make `event.dataset` and alias pointing to `data_stream.dataset` then queries can benefit from the `constant_keyword`. The downside is that `event.dataset` won't appear in `_source`, but most parts of Kibana are moving away from using the `_source` field by using the Fields API.

That would leave us with needing a solution for things that currently depend on `event.module`.

**Comment by andrewkroh** [comment]
To resolve this packages added constant_keyword `event.module` and `event.dataset` fields with a value specified in their mappings. The existing `event.dataset` from elastic/beats#20076 was not removed so that field will be `_source` too for now.
