### ISSUE TITLE
[Azure] [container_registry] Incorrect `azure.timegrain` field value

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#7162]
container_registry:
```
"azure": {
      "subscription_id": "0e073ec1-c22f-4488-adde-da35ed609ccd",
      "timegrain": "PT5M",
      "resource": {
        "name": "XXX",
        "id": "/subscriptions/XXXX/resourceGroups/XXX/providers/Microsoft.ContainerRegistry/registries/XXX",
        "type": "Microsoft.ContainerRegistry/registries",
        "tags": {
          "sometag": "somevalue"
        },
        "group": "XXX"
      },
      "namespace": "Microsoft.ContainerRegistry/registries",
      "container_registry": {
        "storage_used": {
          "avg": 0
        }
      }
    }
  },
```
correct timegrain value for `storage_used` metric should be `1H` - https://github.com/elastic/integrations/blob/main/packages/azure_metrics/data_stream/container_registry/agent/stream/stream.yml.hbs#L47-L49, bu it is a `5M` for some reason

this metric is actually reported, but in unexpected way:
it reported with delay 1h, each 5min:
<img width="2551" alt="Screenshot 2023-07-26 at 14 32 26" src="https://github.com/elastic/integrations/assets/28299531/8cbf564c-b40b-48da-9df6-67b2eb6d7e35">

It seems to be wrong 

cc @tommyers-elastic @zmoog

**Comment by tommyers-elastic** [comment]
yeh this looks like a bug somewhere, we'll look into it.

**Comment by zmoog** [comment]
@tetianakravchenko, I am running some tests on this case to understand better what's going on. 

First, the behavior of getting PT1H metrics every 5 minutes with 1 hour of delay is, unfortunately, a side effect of how the metricset works. It's an issue because it collects more metrics than needed but is less problematic.

Second, the `azure.container_registry.storage_used.avg` field with a `PT5M` timegrain is wrong, and we should fix it as soon as possible. However, I tried to reproduce this issue with the Agent integration version 1.0.24 and stack 8.10-SNAPSHOT, but I am getting the metrics with the expected `PT1H` time grain:

![CleanShot 2023-08-28 at 01 53 33@2x](https://github.com/elastic/integrations/assets/25941/d538de0d-ee20-4ac0-8cab-6d3cced690dc)

Can you share more about your settings (integration options, Agent, and stack versions)?

**Comment by tetianakravchenko** [comment]
I actually indeed can't reproduce it now 😕 tested with stack version 8.8.2 and 8.9.1
<img width="1601" alt="Screenshot 2023-09-01 at 12 07 59" src="https://github.com/elastic/integrations/assets/28299531/7b1c8853-8ee6-4b44-8381-15f746972240">

Sorry, it could be my mistake somehow.

> First, the behavior of getting PT1H metrics every 5 minutes with 1 hour of delay is, unfortunately, a side effect of how the metricset works. It's an issue because it collects more metrics than needed but is less problematic.

should I create a dedicated issue for this one? or it is fine to keep this issue for that?

**Comment by zmoog** [comment]
> > First, the behavior of getting PT1H metrics every 5 minutes with 1 hour of delay is, unfortunately, a side effect of how the metricset works. It's an issue because it collects more metrics than needed but is less problematic.
> 
> should I create a dedicated issue for this one? or it is fine to keep this issue for that?

I would create a different issue for this problem for two reasons:

- The two problems are not related;
- The one-hour delay with more values than needed is wrong but less critical than reporting the incorrect time grain.


> Also with this might be another issue (tested and reproduced on stack 8.9.1):

This is a different angle to the same problem that's causing the one-hour delay on the metrics with PT1H time grain. 

What about creating an issue related to PT1H time grain problems? WDYT?

**Comment by zmoog** [comment]
> Sorry, it could be my mistake somehow. I couldn't find a screenshot of the document itself to proof that it was 5M

No worries, I trust your checks even if you can't find a screenshot. I just need your help to reproduce the issue.

**Comment by tetianakravchenko** [comment]
@zmoog I've created this issue as a follow up for PT1H time grain problems - https://github.com/elastic/integrations/issues/7646
