### ISSUE TITLE
File Integrity Monitoring | User Information - Linux

### ISSUE THREAD

**Issue by narph** [elastic/integrations#7401]
Similar to Auditbeat's FIM module, our new FIM integration can monitor for file changes, but does not include the user information to capture who modified/accessed the file. This is a significant visibility gap for security analysts and a heavily requested enhancement request.

Research needs to be done to determine how we can capture user information within our FIM integration and any underlying changes required. Can the OS components we rely on today be leveraged or is an underlying change to how we gather FIM data needed?

Meta issue https://github.com/elastic/integrations/issues/3310

**Comment by norrietaylor** [comment]
Hello @chemamartinez 👋 

The Linux Platform team discussed this issue in a recent team meeting. Our discussion produced some additional information that you may find interesting and valuable. 

First, the crux of this issue is that we need to associate a file operation with a calling process. In Linux, the process is the entity that is operating on a file. As such, it is also the entity that is associated with an effective user. If you can determine the pid of the process, it becomes straightforward to get other helpful metadata, including that of the user. 

In our discussion, we focussed on three of the options you listed above for retrieving process information: fanotify, kprobes, and eBPF. 

### Fanotify
We do not recommend leveraging fanotify for this metadata. The reasons for this are primarily related to reliability. 

Fanotiy can operate in _notification_ or _permission_ mode. In _notification_ mode, the application would receive the pid but would need to scrape the /proc filesystem after an event for user metadata. This approach would introduce a race condition for short-lived processes in which the required metadata would be absent. To solve this problem, we could receive an event in _permission_ mode. Auditbeat would hold a lock on the file while we scraped /proc filesystem for the metadata in this situation. This technique is inherently a system stability risk as if, for some reason, Auditbeat is killed while it holds this lock, the entire filesystem can be blocked. Locking a production Linux host's file system can be a source of severe SDH issues. 

### eBPF
eBPF is a great candidate as it can instrument a kernel event in real-time and transmit a safe event to userspace containing much of the information we need without worrying about scraping /proc. 

While eBPF requires some C knowledge to write programs, this should be manageable and not involve a significant learning curve. Most eBPF tracing programs are relatively simple and easy to understand. In fact, many of the existing probes in https://github.com/elastic/ebpf could be used as they are. 

There are some limitations to eBPF that we should highlight. First, there is an instruction limit for eBPF programs, which means complex logic can be challenging to implement. Algorithms that involve elaborate filtering or string parsing are often better handled in userspace. Second, eBPF can be problematic to work with for older Linux kernels. Our team tends to require BTF support, which was introduced around 5.8. Practically, this means 5.10 kernels and newer are suited for eBPF tracing and telemetry. 

### Kprobes 
Kprobes are also a great candidate as they can transmit a safe event to userspace in real-time. Kprobes can be set up to use tracefs, meaning you are not operating directly in kernel space. This mitigates any stability concerns you have raised. 

When using tracefs you are bound to predefined `format` structures, which limits the data points you can instrument. They are also not a formal API, which means they can change as the kernel is updated. This limitation means kprobes and tracefs are less flexible than eBPF.

The advantage of this approach is that much older kernels are supported. 

### Recommendation 
Our general recommendation would be to enable Auditbeat to make a runtime decision based on the kernel version to use a kprobe or eBPF implementation. Older kernels would use kprobes, and newer kernels would use eBPF. These two implementations could be developed serially, prioritizing kernel support that would satisfy the most customers. 

Another issue to be aware of is https://github.com/elastic/security-team/issues/7471. In this issue, we also discuss enriching Auditbeat events with process-oriented metadata. Ideally, the same backend could serve both goals and be reusable for future requests.

**Comment by andrewkroh** [comment]
We have not decided on technology at this point. In order to have a better understanding of what data is required I'm listing the current event triggers and the data that is being reported.

## Event Triggers

- File or dir created (e.g. open, mkdir, symlink, link)
- File or dir renamed
- File or dir deleted
- File modified (written, truncated)
- Attributes modified (e.g chmod, chown, timestamps, and extended attributes)
- (fyi) Also at startup auditbeat can scan the filesystem to look for deltas since it last ran.

## Data

Apart from the inotify trigger, all of the data about the files is collected from userspace. For example, when it gets an inotify `IN_ATTRIB` event it will `stat` and `getxattr` to see what changed. We don't have to modify how this part works, but if there is an opportunity for the events to include specific information about what changed then could make FIM more efficient.

Auditbeat is reporting this file metadata with events:

- path
- target_path (for symlinks)
- inode
- owner uid
- owner gid
- size
- mtime
- ctime
- type (dir, file, symlink, etc)
- mode
- xattrs (specifically security.selinux and system.posix_acl_access)
- file content hashes

We want to add information about the process and user that triggered the file change event. I was thinking to add some minimal metadata that gives you some context, and enables you to pivot to process events via `entity_id` when you need more rich process data.

- process.name
- process.pid
- process.entity_id
- user.id
- user.name
- container.id

**Comment by pkoutsovasilis** [comment]
Hello also from my end :wave: Thank you for your messages and initial investigation @chemamartinez , @norrietaylor , and @andrewkroh. 

Having your comments in mind I have been investigating, in theory so far, how a kprobe-based solution could look like to match the existing inotify-based `Event Triggers`  mentioned above by @andrewkroh . Yesterday, I had a meeting with @nicholasberlin , @stanek-michal and @norrietaylor where we discussed my early thinking and we all deemed that this could be feasible. In a few words, I am thinking of scanning the directories that need to be monitored initially, extract the `inode` number of each one, and then through the appropriate kprobe-based events associate which ones of them affect files/folders that we want to monitor.

Of course there are certain open questions, as to how many of this kprobe-based events can we process and associate in a timely manner, portability of kprobe-based solution, etc. For that reason, I will start coding a PoC that builds on top of the theory and as a result we will be able to have more quantitative answers to such questions. 

The thinking so far is to make a separate backend for the FIM-module which is kprobe-based and is able to produce events that consist also the pid that caused each change. Then a processor can utilise the former to enrich the events accordingly before sending them out.

**Comment by norrietaylor** [comment]
@jamiehynds, perhaps we should discuss acceptance criteria and GA plan for this ticket?
