### ISSUE TITLE
CI: when working on a specific package, only that package's check stage isn't being run

### ISSUE THREAD

**Issue by ycombinator** [elastic/integrations#764]
I am working on a module->package migration for the `traefik` integration in https://github.com/elastic/integrations/pull/763.

Looking at the [CI pipeline for that PR](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-763/1/pipeline), I was expecting only the `traefik` package's `check` stage to be executed, thanks to this [enhancement](https://github.com/elastic/integrations/pull/474). But it looks like the `check` stage is being run for all packages.

**Comment by ycombinator** [comment]
cc: @mtojek

**Comment by mtojek** [comment]
A really quick fix is to rebase against the latest master :)

This is because of the way how `git-diff` behaves. To fix the issue, you have to adjust lines: https://github.com/elastic/integrations/blob/master/.ci/Jenkinsfile#L185
https://github.com/elastic/integrations/blob/master/.ci/Jenkinsfile#L179

... so that Jenkins considers only files belonging to the PR, not including files in the master branch.

**Comment by ycombinator** [comment]
Hmmm, rebasing on `master` did indeed fix the issue!

Does this mean every PR is going to have this issue unless they rebase on `master` first? If so, that still sounds like something we should try to fix, no?

**Comment by mtojek** [comment]
Let me see what can I do here
