### ISSUE TITLE
[Synthetics] Ensure Synthetics Estimator Dashboard using ad hoc data view

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/integrations#7755]
As discussed in [slack](https://elastic.slack.com/archives/C04R6THHZFH/p1694089562272889?thread_ts=1693906711.225509&cid=C04R6THHZFH) it would seem that the recently added _[Synthetics] Estimated Billing_ dashboard (in https://github.com/elastic/integrations/pull/6751) is not using ad hoc data views, which can cause problems with the data view selector.

![image](https://github.com/elastic/integrations/assets/70908889/5a15d583-c6c0-461d-94f8-0dfe3be5cbd5)

ACs:
- Ensure the Synthetics dashboard is using ad hoc data views

**Comment by timductive** [comment]
If the synthetics estimator package must be pre-installed on kibana then i would not tie any saved objects to that integration because they show up in a very obvious way to new users, they are confusing and create visual noise to users who don't necessarily understand what synthetics are. I would move this dashboard to a separate package that the user can choose to install when it is needed.

**Comment by ninoslavmiskovic** [comment]
I agree with @timductive this is also what I raised on slack. ➕

**Comment by teresaalvarezsoler** [comment]
+1 to Tim's suggestion. This is generating noise in the dashboard list page.
