### ISSUE TITLE
CODEOWNERS: error "Unknown owner on line 71: make sure the team @elastic/sec-cloudnative-integrations exists"

### ISSUE THREAD

**Issue by efd6** [elastic/integrations#7784]
The CODEOWNERS file is currently being complained about due to the cloud_defend integration entry. To reduce PR complaint noise, this should be resolved.
```
    Unknown owner on line 71: make sure the team @elastic/sec-cloudnative-integrations exists, is publicly visible, and has write access to the repository
    /packages/cloud_defend @elastic/sec-cloudnative-integrations
```

**Comment by bhapas** [comment]
@elastic/sec-cloudnative-integrations

**Comment by bhapas** [comment]
Introduced in https://github.com/elastic/integrations/pull/4680

**Comment by verofa** [comment]
Hi peeps,
The `sec-cloudnative-integrations` team was reorganised, and they have a new GitHub team (sec-linux-platform) assigned.
Therefore, any reference to the previous team in the configs need to get updated. @mjwolf will work on it (thank you very much!)

**Comment by mjwolf** [comment]
Hi @efd6, @bhapas,  I've created a PR to fix the team owner: https://github.com/elastic/integrations/pull/7921

Github is still showing the same error. The team exists (https://github.com/orgs/elastic/teams/sec-linux-platform), so I'm unsure is the problem now is that the team is not publicly visible (or if Elastic teams even should be publicly visible) or if the team doesn't have write access to the repo.

If the problem is with write access, could you add write access to this team?
