### ISSUE TITLE
7.11.2 - Integrations Cisco - Setting Log Level in policy not working

### ISSUE THREAD

**Issue by MarcusCaepio** [elastic/integrations#799]
Hi again,
for testing, I set the log level of the ASA logs to 1 in the policy settings. Agents noticed, that they need to update their config and did it. Although, I still get logs on log level info, so it seems, the parameter is not working.

Cheers,
Marcus

**Comment by andrewkroh** [comment]
Thanks for reporting this. That parameter is broken from what I see. The origin of the problem is that the package was created from the Beats module. And the Beat module treated the ingest pipeline as mutable and would rewrite the pipeline to contain whatever log_level parameter you specified. But this can't be supported in the same manner in Fleet because it doesn't allow pipelines to be tailored based on config since all policies share and write to the same ingest pipeline.

My preference is to remove the option and have users set the log level in the cisco devices (like `logging trap $severity_level`). Then there's less wasted CPU processing logs that are only going to be dropped by the ingest pipeline.

**Comment by andrewkroh** [comment]
PR: #1159
