### ISSUE TITLE
[Microsoft M365 Defender] Microsoft Defender process table not mapped correctly to ECS fields

### ISSUE THREAD

**Issue by Avesta-FA** [elastic/integrations#8524]
Microsoft M365 Defender integration version: 2.4.0
Hello,
We are currently ingesting the process table and the integration seems to have improper mapping for the process command line field.
An example of how it looks:

```
m365_defender.event.process.command_line	wmiprvse.exe -Embedding
process.args	[wmiprvse.exe, -Embedding]
process.args_count	2
process.command_line	svchost.exe -k DcomLaunch -p
process.name	WmiPrvSE.exe
process.parent.args	[svchost.exe, -k, DcomLaunch, -p]
process.parent.command_line	svchost.exe -k DcomLaunch -p
```

We can see that the command line has taken the value of the parent command line.
This is the case for ALL events.

**Comment by piyushw-crest** [comment]
Hi @Avesta-FA - Thanks for the feedback, we have tried ingesting below event log and observed that we have different values for `process.command_line` and `process.parent.command_line`. 

Can you please help us with few sample logs or `event.original` so that we can re-create the scenario.

`{"Tenant":"DefaultTenant","category":"AdvancedHunting-DeviceProcessEvents","operationName":"Publish","properties":{"Timestamp": "2023-07-19T14:02:19.4882081Z","DeviceId": "22bb10ffe3104214b20fc7de339a2b053e915e5c","DeviceName": "janeslaptop1.corporatedomain","ActionType": "ProcessCreated","FileName": "msedgewebview2.exe","FolderPath": "C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\114.0.1823.79\\msedgewebview2.exe","SHA1": "271eb137d3d8519cb42e5bccd690a3b9a3059f2a","SHA256": "075d1edc11548c9ebf7f238dea9393f26c5b83cd0362aa4cc24b1d8a6ebc6354","MD5": "b21b158fce974aa46125820ce6b42e9d","FileSize": 3653056,"ProcessVersionInfoCompanyName": "Microsoft Corporation","ProcessVersionInfoProductName": "Microsoft Edge WebView2","ProcessVersionInfoProductVersion": "114.0.1732.12","ProcessVersionInfoInternalFileName": "msedgewebview2_exe","ProcessVersionInfoOriginalFileName": "msedgewebview2.exe","ProcessVersionInfoFileDescription": "Microsoft Edge WebView2","ProcessId": 5498762,"ProcessCommandLine": "\"msedgewebview2.exe\" --type=renderer --noerrdialogs --user-data-dir=\"C:\\Users\\JANEBLOGGS\\AppData\\Local\\Microsoft\\Office\\16.0\\Wef\\webview2\\4ee9dcb0-735b-442e-945c-177c665efe6b_ADAL\\2\\EBWebView\" --webview-exe-name=MSOUTLOOK.EXE","ProcessIntegrityLevel": "Low","ProcessTokenElevation": "TokenElevationTypeDefault","ProcessCreationTime": "2023-07-19T14:02:19.4882081Z","AccountDomain": "corporatedomain","AccountName": "janebloggs","AccountSid": "S-1-5-21-57989841-2025429265-839522115-962270","AccountUpn": "janebloggs@corporate.com","AccountObjectId": "4ee9dcb0-735b-442e-945c-177c665efe6b","LogonId": 3654987,"InitiatingProcessAccountDomain": "corporatedomain","InitiatingProcessAccountName": "janebloggs","InitiatingProcessAccountSid": "S-1-5-21-57989841-2025429265-839522115-962270","InitiatingProcessAccountUpn": "janebloggs@corporate.com","InitiatingProcessAccountObjectId": "4ee9dcb0-735b-442e-945c-177c665efe6b","InitiatingProcessLogonId": 3654987,"InitiatingProcessIntegrityLevel": "Medium","InitiatingProcessTokenElevation": "TokenElevationTypeDefault","InitiatingProcessSHA1": "271eb137d3d8519cb42e5bccd690a3b9a3059f2a","InitiatingProcessSHA256": "075d1edc11548c9ebf7f238dea9393f26c5b83cd0362aa4cc24b1d8a6ebc6354","InitiatingProcessMD5": "b21b158fce974aa46125820ce6b42e9d","InitiatingProcessFileName": "msedgewebview2.exe","InitiatingProcessFileSize": 5498762,"InitiatingProcessVersionInfoCompanyName": "Microsoft Corporation","InitiatingProcessVersionInfoProductName": "Microsoft Edge WebView2","InitiatingProcessVersionInfoProductVersion": "114.0.1732.12","InitiatingProcessVersionInfoInternalFileName": "msedgewebview2_exe","InitiatingProcessVersionInfoOriginalFileName": "msedgewebview2.exe","InitiatingProcessVersionInfoFileDescription": "Microsoft Edge WebView2","InitiatingProcessId": 65485,"InitiatingProcessCommandLine": "\"msedgewebview2.exe\" --embedded-browser-webview=1 --webview-exe-name=MSOUTLOOK.EXE --webview-exe-version=16.0.15601.20706 --user-data-dir=\"C:\\Users\\USERNAME\\AppData\\Local\\Microsoft\\Office\\16.0\\Wef\\webview2\\1234dcb0-735b-442e-945c-e6c5df94062c_ADAL\\2\\EBWebView\" --noerrdialogs","InitiatingProcessCreationTime":null},"tenantId":"12345af3-bc0e-4f36-b08e-27759e912345","time":"2023-07-19T18:03:21.9948950Z"}`

![m365](https://github.com/elastic/integrations/assets/104125275/a45bdfa9-e9c9-45c6-8d16-b49aa065a44e)

**Comment by Avesta-FA** [comment]
Hello,

It seems that the previous issue of commandLine being the same as the parent field was fixed.

The above picture and log is correct the initiating is in the parent and the child is in the original.

Were you expecting different results?

**Comment by piyushw-crest** [comment]
@Avesta-FA  - apologies if we misunderstood, do you mean we have already supported and fixed this issue you had raised?

**Comment by Avesta-FA** [comment]
Yes the Process.Command_line no longer maps into the incorrect field as it did before.

**Comment by piyushw-crest** [comment]
Awesome - Thanks for the confirmation.

**Comment by jamiehynds** [comment]
Thanks for the feedback and confirmation that the issue is address @Avesta-FA. Closing as completed.
