### ISSUE TITLE
[elastic/integrations] [sophos][utm] host is not displayed in Security App, host.name field is missing

### ISSUE THREAD

**Issue by StefanSa** [elastic/integrations#8528]
Hi there @chemamartinez @jamiehynds  
In the latest version v3.7, an incorrect hostname `host.hostname` is given, correct would be `host.name`.
Due to this bug, the host is not displayed in the security app.
I have previously created a user pipeline that renames this field, so the utm host is displayed again in the security app.

Please fix the bug, thank you.
Stefan

**Comment by efd6** [comment]
@StefanSa I'm not convinced that this is completely correct. The sophos syslog format is approximately RFC5425 and that document describes the hostname field as [potentially holding a variety of values](https://datatracker.ietf.org/doc/html/rfc5424#section-6.2.4). While the RFC says that the field _can contain_ an FQDN of the host, in the test cases that we have, all the values of this field are hostname according to the [ECS definition of `host.hostname`](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-hostname) rather than an [FQDN as recommended by the ECS](https://www.elastic.co/guide/en/ecs/current/ecs-host.html#field-host-name). Do you have examples where the value held by the field is an FQDN?

Though it is not a bug, I think it's reasonable to duplicate the value of `host.hostname` into `host.name` if it help with real-world visibility.

**Comment by StefanSa** [comment]
@efd6 Dan,
Greetings to Down Under.
i can live with your objections regarding FQDN.
The decisive factor is that `Elastic Integration of the security and network category` is also `visible and can be handled (filter etc.) in the security app without any problems.`
As you have already suggested, this can be achieved by duplicating the `host.hostname` field to `host.name`.
