### ISSUE TITLE
Docs: Oracle Integration: Syntax for setting DSN in Policy in Fleet isn't clear.

### ISSUE THREAD

**Issue by abeaudin** [elastic/integrations#8607]
I've noticed this with the Oracle Integration along with another integration (but I forgot to make a note of it)
In our docs, we generally have the configuration for the integration in configuration file format (metricbeat) but not for the agent. What we seem to be missing is what that same configuration looks like in the agent.

<img width="1400" alt="Screenshot 2023-11-29 at 6 13 57 AM" src="https://github.com/elastic/integrations/assets/7717493/43c35bff-3b39-4b99-95b4-feb4fd02b614">

The specific example is that a customer of mine is running a proof of concept and to configure the oracle integration using the agent he found the metric beat docs (https://www.elastic.co/guide/en/beats/metricbeat/current/_host_setup.html) which stated:

```
The following two types of host configurations are supported:

DSN host configuration as URL:

hosts: ["user/pass@0.0.0.0:1521/ORCLPDB1.localdomain"]
hosts: ["user/password@0.0.0.0:1521/ORCLPDB1.localdomain as sysdba"]
DSN host configuration:

hosts: ['user="user" password="pass" connectString="0.0.0.0:1521/ORCLPDB1.localdomain"']
hosts: ['user="user" password="password" connectString="host:port/service_name" sysdba=true']
```
so he chose the fourth option and cut and pasted it into the Agent Integration. This was not what the agent integration expected.
In the agent integration, the hosts: tag was implied as was the square brackets for the array entry so an admin could enter an array of hosts: but each needed to be of the form:

```
user="user" password="password" connectString="host:port/service_name" sysdba=true
```

I looked for and didn't find specific guidance/docs on how to properly configure this and couldn't find it so experimented my way to the solution. 
I did find https://docs.elastic.co/integrations/oracle but it didn't speak to the UI or the multiple formats supported.

**Comment by agithomas** [comment]
In the [link](https://docs.elastic.co/integrations/oracle ) , the information of the Oracle DSN configuration can be found. 

Screenshot:  
<img width="742" alt="image" src="https://github.com/elastic/integrations/assets/101976829/6a0a2d90-46b7-4e0c-9aca-f9aee0004c96">


The documentation is very long and a user can easily miss to notice this information. So, I think,  it may be good to have a section named Configuration (Header 2 type? ) so that the link appears in the Left navigation easily and users won't miss to notice important details,.
