### ISSUE TITLE
Microsoft Exchange Server Integration

### ISSUE THREAD

**Issue by SubhrataK** [elastic/integrations#8937]

**Comment by SimonKoetting** [comment]
Hey @SubhrataK ,
I'm not sure what this issue was for, but in case it was to create an Exchange Server integration. I published one a month ago (#9197), currently in Technical Preview. Feel free to take a look into that integration and may add some additional stuff if wanted, or let me know if you think there is something missing.

**Comment by SubhrataK** [comment]
@SimonKoetting Yes this was for creating the Exchange Server Integration. Thanks for sharing, will close this one.

**Comment by SubhrataK** [comment]
The integration already exists: https://github.com/elastic/integrations/tree/main/packages/microsoft_exchange_server
