### ISSUE TITLE
Dashboard issues with the "[Logs o365] Audit Dashboard" as provided by integration "Microsoft 365" version 2.1.1

### ISSUE THREAD

**Issue by eriroley** [elastic/integrations#8970]
1) The panel size or font fort the "count" panel is poorly set (confirmed that I am at standard 100% zoom in Chrome)
![image](https://github.com/elastic/integrations/assets/20193894/a2bde11c-a9b5-40d3-a28d-5f8efb5a9997)

Also, there appears to be a missing filter in at least the "Top users by authentication outcome" panel
There's no way I should have over 3,000,000 events, with only 2411 events as shown in the previous screenshot
![image](https://github.com/elastic/integrations/assets/20193894/f635301a-3d1b-4167-921b-34d0a3de2198)
I suggest adding the following filter for that (and all other panels in this dashboard)
data_stream.dataset:"o365.audit" 
which then gives much more reasonable results
![image](https://github.com/elastic/integrations/assets/20193894/2e8e11a1-fa9f-4d29-a109-73106c19ebd3)

**Comment by jamiehynds** [comment]
Thanks for flagging this with us @eriroley. 

@chrisberkhout would you mind taking a look at this one, please?

**Comment by eriroley** [comment]
Similar workaround as in #8969 is possible - add a filter to the dashboard for data_stream.dataset: 0365.audit

**Comment by chrisberkhout** [comment]
@eriroley I opened #8983 to fix the missing filter.

The count panel font size initially looked good on my machine. It's not explicitly set in the dashboard config, so an issue there would be a general Lens visualization issue. I was able to reproduce the problem in your screenshot by changing my operating system display scaling factor from 1.0 to 2.0, as shown below.

As a workaround, adjusting your operating system display scaling settings may help. I believe the underlying issue is being addressed in https://github.com/elastic/kibana/issues/154414

---

Here's normal 1.0 scaling:
![Scale 1 0 Screenshot 2024-01-25 at 15-19-43 Elastic](https://github.com/elastic/integrations/assets/124641/3dee1853-781f-4c6b-ba2b-6833f146c4bb)

And here it is at 2.0 scaling:
![Scale 2 0 Screenshot 2024-01-25 at 15-19-27 Elastic](https://github.com/elastic/integrations/assets/124641/bf1c37d4-f99a-40bb-92a1-75a80cb0cdfb)

**Comment by eriroley** [comment]
Interesting - as you can see in this screenshot, my OS display is scaled to 100% as is my Chrome scaling, but the issue persists
![image](https://github.com/elastic/integrations/assets/20193894/b8439dae-a536-4e21-93bb-4023261b4735)

**Comment by chrisberkhout** [comment]
Okay, yes, that is interesting. I wonder if there are some other related settings, like "Accessibility > Text/Font size"?

Someone describes a similar issue on Windows 11 [here](https://www.reddit.com/r/Windows11/comments/t548kj/fontscaling_gone_large_despite_100_scaling/) that went away after increasing font size then setting it back to 100%.

**Comment by eriroley** [comment]
no change after changing the font size in accessibility, and then changing it back

**Comment by eriroley** [comment]
However, after changing the display scaling to 125% and then back to 100% it now shows correctly
and yes, I am on windows 11

**Comment by chrisberkhout** [comment]
Okay, great. Thanks for all the info. Hopefully when https://github.com/elastic/kibana/issues/154414 is resolved it'll work on higher settings as well.
