### ISSUE TITLE
[Apache HTTP Server] Validate GROK failures with remote login name (%l)

### ISSUE THREAD

**Issue by muthu-mps** [elastic/integrations#9144]
### Observations
The Apache HTTP Server integration documentation covers the supported GROK patterns with examples. But when we try to evaluate the example patterns we are observing GROK failure.
This happens because we are not currently parsing the remote login names.
#### GROK Pattern:
<img width="1087" alt="Screenshot 2024-02-14 at 10 57 19 AM" src="https://github.com/elastic/integrations/assets/101238137/79584502-de96-4e91-a00e-9ff7e2c9b21e">

#### Provided sample formats in the document
<img width="1329" alt="Screenshot 2024-02-14 at 10 57 21 AM" src="https://github.com/elastic/integrations/assets/101238137/9333c9e1-a3a5-4ac9-b83b-2be4732398ba">

### Next Steps
- The supported log formats in the document should be revisited and add these formats in the pipeline test scripts for validations.
- Update the GROK pattern to support remote login names if required.

**Comment by niraj-elastic** [comment]
@muthu-mps It seems that in current Grok pattern, a hyphen "-" has been added as a hardcoded value for the remote login names ("%l"). This aligns with the common practice in Apache log formats where the remote login name ("%l") is often represented by a hyphen "-" due to its unreliability, [but if `IdentityCheck` is on than Apache attempts to log the remote user's identity in the access log](https://httpd.apache.org/docs/2.0/logs.html#:~:text=Apache%20httpd%20will%20not%20even%20attempt%20to%20determine%20this%20information%20unless%20IdentityCheck%20is%20set%20to%20On). In this scenario, the "%l" format specifier would represent the remote logname of the client, typically as a string. So when the user identifier is available current grok pattern will fail, so it seems that Current grok is needed to be updated. I will do some further analysis and share details with you soon.

**Comment by niraj-elastic** [comment]
I have raised [PR](https://github.com/elastic/integrations/pull/9632) to fix the issue by updating grok pattern.

**Comment by niraj-elastic** [comment]
Closing this issue since the [PR](https://github.com/elastic/integrations/issues/9144) for fix is merged.
