### ISSUE TITLE
[BuildKite] Make Failed Builds Visible Again

### ISSUE THREAD

**Issue by nicpenning** [elastic/integrations#9357]
Since the move to Build Kite, community developers no longer have access to see why their builds fail when an Elastic member runs `/test`.

It would be very helpful if the developer of the integration can see what error messages have spawned so that they can be fixed instead of waiting on a response from an Elastic member to share the error details. This will decrease time to release if error messages on build can be revealed. The other solution is ensure all tests can be executed locally using `elastic-package`: https://github.com/elastic/elastic-package/issues/1721

**Comment by efd6** [comment]
This should be fixed. Please take a look at a recent build to confirm.

**Comment by nicpenning** [comment]
This has been resolved! I can see build information now, thank you! 🙏

**Comment by jsoriano** [comment]
Reopening, we had to revert the changes because we had problems triggering internal pipelines from the public pipeline. We will split the pipeline in two, a public one with the main validation stages, and a private one with the stages that trigger internal processes.

cc @mrodm

**Comment by nicpenning** [comment]
Thanks for the awareness, @jsoriano !

**Comment by mrodm** [comment]
> We will split the pipeline in two, a public one with the main validation stages, and a private one with the stages that trigger internal processes.

Following about this, there are some steps that need to be done in order to make public the pipeline in charge of testing/validating packages:
- [ ] Move publishing steps to a new pipeline (in dry run mode) https://github.com/elastic/integrations/pull/9553
- [ ] Update permissions for this new pipeline
- [ ] Enable publish step in that new pipeline and test to publish some package
- [ ] Copy these changes to all backport branches
- [ ] Update catalog-info settings to run this pipeline also for backport branches

**Comment by nicpenning** [comment]
Looks great!

**Comment by mrodm** [comment]
Perfect! Thanks for checking this out @nicpenning!
I'll close this issue then.

**Comment by nicpenning** [comment]
This is great, thank you for this implementation. It will help greatly for those in the community developing integrations.
