### ISSUE TITLE
[statsd_input] Test failure - observed hit count 6 did not match expected hit count 3

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#9584]
statsd_input has a failing system test under 8.13.

`observed hit count 6 did not match expected hit count 3`

https://buildkite.com/elastic/integrations/builds/10363

**Comment by aliabbas-elastic** [comment]
This may be due to the [issue](https://github.com/elastic/beats/pull/36925) that metrics were getting jumbled up. This was fixed and now the metrics would be received in [single](https://github.com/elastic/beats/pull/36925#:~:text=We%27ve%20updated%20the%20implementation%20to%20match%20the%20approach%20used%20in%20the%20statsd%20exporter.%20Now%2C%20each%20key%2Dvalue%20pair%20and%20its%20associated%20attributes%20are%20treated%20as%20individual%20events) documents. This would require the input to be `8.11.0` and then the CI would be happy. I'll raise a PR to do this.

**Comment by ritalwar** [comment]
@aliabbas-elastic Thank you for addressing this.

**Comment by andrewkroh** [comment]
> observed hit count 9 did not match expected hit count 6

**Comment by aliabbas-elastic** [comment]
> It's still failing, just with a different count.

Thanks @andrewkroh for reporting this. I have fixed the `hit_count` now but do not have access to buildkite. Is the CI green now for `statsd_input` so that I can close this issue now?

**Comment by andrewkroh** [comment]
I don't see the failure in the latest run. Closing.
