### ISSUE TITLE
[cisco_duo.admin] "field [message] not present as part of path [message]"

### ISSUE THREAD

**Issue by ethack** [elastic/integrations#9598]
The ingest pipeline can fail with this error.

```json
        {
          "processor_type": "remove",
          "status": "error",
          "if": {
            "condition": "ctx.cisco_duo?.admin?.flattened != null",
            "result": true
          },
          "error": {
            "root_cause": [
              {
                "type": "illegal_argument_exception",
                "reason": "field [message] not present as part of path [message]"
              }
            ],
            "type": "illegal_argument_exception",
            "reason": "field [message] not present as part of path [message]"
          }
        },
```

This happens because this step tries to remove the `message` field, which does not always exist.
https://github.com/elastic/integrations/blob/fe5fe99aeef9d116b3cb47c489538e7d863489f2/packages/cisco_duo/data_stream/admin/elasticsearch/ingest_pipeline/default.yml#L133-L137

---

A prior step renames `message` to `event.original`.
https://github.com/elastic/integrations/blob/fe5fe99aeef9d116b3cb47c489538e7d863489f2/packages/cisco_duo/data_stream/admin/elasticsearch/ingest_pipeline/default.yml#L7-L11

A later step will sometimes create a new `message` field. However, in our case this field is never being created due to `json.description` not existing.
https://github.com/elastic/integrations/blob/fe5fe99aeef9d116b3cb47c489538e7d863489f2/packages/cisco_duo/data_stream/admin/elasticsearch/ingest_pipeline/default.yml#L78-L82

For a fix, I suggest setting `ignore_missing` to `true`. This seems to fix the issue in our live pipeline.

```yaml
  - remove:
      field:
        - message
        - event.reason
      if: ctx.cisco_duo?.admin?.flattened != null
      ignore_missing: true
```

**Comment by efd6** [comment]
@ethack Can you provide an input document for testing? Looking at the pipeline logic, I do not see a way to get to the removal if there is no `json.description`:
- `cisco_duo.admin.flattened` is populated by [this processor](https://github.com/elastic/integrations/blob/3a4b1c37247d9839cb1090e78bf76fa816f8a4d6/packages/cisco_duo/data_stream/admin/elasticsearch/ingest_pipeline/default.yml#L83-L87) conditionally on the presence of `json.description`. It is never constructed elsewhere.
- `message` is populated by [this processor](https://github.com/elastic/integrations/blob/3a4b1c37247d9839cb1090e78bf76fa816f8a4d6/packages/cisco_duo/data_stream/admin/elasticsearch/ingest_pipeline/default.yml#L78-L82) under the same conditions.
- so if `cisco_duo.admin.flattened`, `message` must also exist, either from the that [this](https://github.com/elastic/integrations/blob/3a4b1c37247d9839cb1090e78bf76fa816f8a4d6/packages/cisco_duo/data_stream/admin/elasticsearch/ingest_pipeline/default.yml#L78-L82) or from the [`rename` here](https://github.com/elastic/integrations/blob/3a4b1c37247d9839cb1090e78bf76fa816f8a4d6/packages/cisco_duo/data_stream/admin/elasticsearch/ingest_pipeline/default.yml#L7-L11) failing to run because `event.original` already exists.

I don't doubt that you see the error, but I would like to see how that is actually happening.

**Comment by ethack** [comment]
I think I figured out what is happening in our situation. `cisco_duo.admin.flattened` exists on the incoming document. The reason is that certain events are being forwarded from a different Elastic cluster and have already been processed by the ingest pipeline on the other cluster. 

This scenario is deprecated in our environment, but still exists for some of the data and the error in my original post is only happening with the data forwarded from the other instance.

So I believe it is a double-parsing issue (which I can understand if your answer is `#wont-fix`) and the original solution of `ignore_missing: true` I posted does fix the issue in our environment. Another option that works is if I remove the  `cisco_duo` object from the sample document. This seems validate that double-parsing is the root cause.

<details>
<summary>
Here is a redacted sample input document just in case you decide to work on this further.
</summary>

```json
[
    {
        "_source": {
            "agent": {
                "hostname": "hostname1",
                "name": "hostname1",
                "id": "id1",
                "type": "filebeat",
                "ephemeral_id": "id2",
                "version": "7.17.4"
            },
            "elastic_agent": {
                "id": "id1",
                "version": "7.17.4",
                "snapshot": "false"
            },
            "cisco_duo": {
                "admin": {
                    "flattened": {
                        "uname": "jdoe",
                        "email": "jdoe@acme.corp",
                        "status": "Active",
                        "realname": "Doe, John"
                    },
                    "action_performed_on": "jdoe",
                    "action": "user_lockout_cleared",
                    "user": {
                        "name": "John Doe"
                    }
                }
            },
            "tags": [
                "forwarded",
                "cisco_duo-admin"
            ],
            "cloud": {
                "availability_zone": "us-east-2a",
                "image": {
                    "id": "ami1"
                },
                "instance": {
                    "id": "i-instance1"
                },
                "provider": "aws",
                "service": {
                    "name": "EC2"
                },
                "machine": {
                    "type": "c5.4xlarge"
                },
                "region": "us-east-2",
                "account": {
                    "id": "awsid1"
                }
            },
            "input": {
                "type": "httpjson"
            },
            "@timestamp": "2024-05-13T23:59:59.999Z",
            "ecs": {
                "version": "8.4.0"
            },
            "data_stream": {
                "namespace": "acme",
                "type": "logs",
                "dataset": "cisco_duo.admin"
            },
            "organization": {
                "name": "acme"
            },
            "@version": "1",
            "trunk_cluster": "true",
            "event": {
                "agent_id_status": "verified",
                "ingested": "2024-05-13T23:59:59Z",
                "original": "{\"tags\":[\"forwarded\",\"cisco_duo-admin\"],\"trunk_cluster\":\"true\",\"event\":{\"ingested\":\"2024-05-13T23:59:59Z\",\"kind\":\"event\",\"action\":\"user_lockout_cleared\",\"agent_id_status\":\"verified\",\"created\":\"2024-05-13T23:59:59.999Z\",\"dataset\":\"cisco_duo.admin\",\"outcome\":\"success\"},\"agent\":{\"type\":\"filebeat\",\"name\":\"hostname1\",\"hostname\":\"hostname1\",\"id\":\"id1\",\"ephemeral_id\":\"id2\",\"version\":\"7.17.4\"},\"data_stream\":{\"type\":\"logs\",\"namespace\":\"acme\",\"dataset\":\"cisco_duo.admin\"},\"ecs\":{\"version\":\"8.4.0\"},\"elastic_agent\":{\"id\":\"id1\",\"version\":\"7.17.4\",\"snapshot\":false},\"cisco_duo\":{\"admin\":{\"flattened\":{\"uname\":\"jdoe\",\"realname\":\"Doe, John\",\"status\":\"Active\",\"email\":\"jdoe@acme.corp\"},\"user\":{\"name\":\"John Doe\"},\"action\":\"user_lockout_cleared\",\"action_performed_on\":\"jdoe\"}},\"cloud\":{\"availability_zone\":\"us-east-2a\",\"service\":{\"name\":\"EC2\"},\"region\":\"us-east-2\",\"machine\":{\"type\":\"c5.4xlarge\"},\"image\":{\"id\":\"ami1\"},\"instance\":{\"id\":\"i-instance1\"},\"provider\":\"aws\",\"account\":{\"id\":\"awsid1\"}},\"@version\":\"1\",\"user\":{\"target\":{\"name\":\"jdoe\"},\"name\":\"John Doe\"},\"@timestamp\":\"2024-05-13T23:59:59.999Z\",\"input\":{\"type\":\"httpjson\"}}",
                "kind": "event",
                "created": "2024-05-13T23:59:59.999Z",
                "action": "user_lockout_cleared",
                "dataset": "cisco_duo.admin",
                "outcome": "success"
            },
            "user": {
                "name": "John Doe",
                "target": {
                    "name": "jdoe"
                }
            }
        }
    }
]
```

<details>

**Comment by efd6** [comment]
I'm inclined to think that this is not something that we should be expected to handle, but I want to raise it internally for discussion.

**Comment by efd6** [comment]
@ethack I'm assuming this is happening during a reindex. This should probably work, so I'll add the `ignore_missing: true`. The outcome of a reindex in this case may be confused though since what is happening here indicates that there will be fields in the resulting document that would not be present in the document if it had been constructed from on the original `message` or `event.original`. So it would be best if you could ensure that only those fields (and other relevant fields like `agent.*` and so on) are present from the source cluster.
