### ISSUE TITLE
[Anomali] Support ThreatStream API

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#9610]
Our Anomali integration currently relies on their Integrator SDK via an Elastic challenge. Based on user feedback, this can be a challenge to configure and maintain. 

Anomali Threatstream now provides the ability to share threat indicators via their TAXII service or a Direct API integration, both avoiding the need to deploy and rely on their integrator SDK. 

Research and collaboration with Anomali is needed to determine a path towards making our integration easier to configure and. maintain.

**Comment by chrisberkhout** [comment]
I think for our use case it will be easier to consume from the ThreatStream API directly rather than using TAXII feeds.

We can add a new data stream to the existing integration, deprecate the old one, and then remove it in the future.

I found some Anomali ThreatStream API documentation from 2023-03-29. The relevant endpoint seems to be `GET /api/v2/intelligence/`. The documentation is comprehensive and has good information regarding efficient pagination, delaying the retrieval of records until the become stable, and details of fields in the response.

A first pass comparison of fields available from the intelligence API endpoint and what we're currently receiving from the Elastic Extension via the integrator SDK suggests that the API provides a superset of what we're currently receiving. We'll be able to reuse the existing mappings and may be able to extend them. See the table below for details.

Authentication is with a username and API key in an Authorization header. It's not clear whether API credentials can be restricted to read-only functionality, which is all we'll need.

For ThreatStream OnPrem, the intelligence endpoint takes a `?remote_api=true` parameter to tell it to retrieve remote observables from ThreatStream Cloud. Fetching local and remote observables may require separate requests. We can assume this is not relevant if the endpoint base URL is `https://api.threatstream.com/`, but for OnPrem cases it may be worth fetching both local and remote observables.

API Attribute | Existing Attribute | Notes
-- | -- | --
asn |   | Not present in existing list
can_add_public_tags |   | Not present in existing list
confidence | confidence | Both lists contain this field
country | country | Both lists contain this field
created_ts |   | Not present in existing list
description |   | Not present in existing list
expiration_ts |   | Not present in existing list
feed_id | source_feed_id | Present but named differently in the existing list
id | id | Both lists contain this field
import_session_id |   | Not present in existing list
ip | srcip | Present but named differently in the existing list
is_anonymous |   | Not present in existing list
is_editable |   | Not present in existing list
is_public | classification | Present but named differently in the existing list (classification can be private/public)
itype | itype | Both lists contain this field
latitude | lat | Present but named differently in the existing list
longitude |   | Not present in existing list
meta.detail | detail | Present but named differently in the existing list
meta.detail2 | detail2 | Present but named differently in the existing list
meta.maltype | maltype | Present but named differently in the existing list
meta.registrant_* |   | Not present in existing list
meta.severity | severity | Both lists contain this field
modified_ts |   | Not present in existing list
org |   | Not present in existing list
owner_organization_id |   | Not present in existing list
rdns |   | Not present in existing list
retina_confidence |   | Not present in existing list
search_filter |   | Not present in existing list
sort |   | Not present in existing list
source | source | Both lists contain this field
source_created |   | Not present in existing list
source_modified |   | Not present in existing list
source_reported_confidence |   | Not present in existing list
status | state | Present but named differently in the existing list
subtype |   | Not present in existing list
tags |   | Not present in existing list
threatscore (deprecated) |   | Not present in existing list
threat_type |   | Not present in existing list
tlp |   | Not present in existing list
trusted_circle_ids | trusted_circle_ids | Both lists contain this field
type | value_type | Present but named differently in the existing list
update_id | update_id | Both lists contain this field
uuid |   | Not present in existing list
value | url | Present but named differently in the existing list
workgroups |   | Not present in existing list
added_at |   | Present only in the existing list
date_first |   | Present only in the existing list
date_last |   | Present only in the existing list
resource_uri |   | Present only in the existing list

**Comment by jamiehynds** [comment]
Thanks for digging into this one @chrisberkhout. 

Let's avoid deprecating the current data stream for now as we don't want to disrupt customers currently using the integration. However, we can make it clear without our docs (and Anomali docs) that the recommended approach is to use the direct API approach (assuming Anomali agree).

Given the the API provides a superset of fields, I presume we leave the current pipelines in place and re-use + expand those pipelines for the API integration - avoiding any breaking changes for existing users?

Regarding on-prem, if that adds complexity here, I'm ok with focusing on cloud for now and we can assess demand for on-prem thereafter.

**Comment by chrisberkhout** [comment]
> Regarding on-prem, if that adds complexity here, I'm ok with focusing on cloud for now and we can assess demand for on-prem thereafter.

Actually, I think on-prem is the simpler case, so that's the one I'm planning to start with. It's an extra parameter (`?remote_api=true`) to get remote/cloud data through the on-prem server. I'll defer that part unless it's trivial.

Looking at the existing, [SDK-based extension](https://github.com/elastic/filebeat-anomali-integrator-sdk), there's nothing to distinguish between these sources of data. I assume it would be getting the local intel and the remote data may or may not be included.

**Comment by chrisberkhout** [comment]
@narph That other ThreatStream integration that mentions "v3" is referring to the version of its integration. Its example [data](https://xsoar.pan.dev/docs/reference/integrations/anomali-threat-stream-v3#threatstream-search-intelligence) refers to API v2 endpoints such as `/api/v2/intelligence/355250247/`, so I think we are targeting the correct API version.
