### ISSUE TITLE
How do I add integration to the elastic stack? To make OpenCTI available in the list of integrations via Kibana?

### ISSUE THREAD

**Issue by SokolSec** [elastic/integrations#9973]
I didn't find any normal instructions anywhere. On the elk website, some kind of smeared and briefly described (for reference). Please help me to implement this issue

From what I did, I installed Open CTI and connected its elastic database, where indexes, data, and so on are spinning in the same number
![image](https://github.com/elastic/integrations/assets/94307667/5fd56504-efa0-421f-b770-5ec45f563607)
![image](https://github.com/elastic/integrations/assets/94307667/74d89828-9ed9-4237-b6e2-9ad9a69ed32b)

**Comment by andrewkroh** [comment]
The documentation for the OpenCTI integration can be found at https://docs.elastic.co/integrations/ti_opencti. Basically you setup an Elastic Agent, you apply the OpenCTI fleet integration to the agent, the agent will connect to opencti and pull in the data.

**Comment by SokolSec** [comment]
@andrewkroh Greetings! You didn't understand me a bit, I don't have an OpenCTI plugin in Kibana, how do I add it?
![image](https://github.com/elastic/integrations/assets/94307667/4748185e-0a4d-4bc3-919a-dea32183d92d)

**Comment by andrewkroh** [comment]
I couldn't reproduce that problem.

<img width="1003" alt="Screenshot 2024-06-05 at 14 46 26" src="https://github.com/elastic/integrations/assets/4565752/b30a7dc5-24bd-4af0-b596-b51411e13cc5">

Are you using the public Elastic Package Registry or do you have your [own package registry](https://www.elastic.co/guide/en/fleet/current/air-gapped.html#air-gapped-diy-epr-kibana) like what you would deploy in an air-gapped network? By default Kibana should be querying this service which for me is returning OpenCTI package version 2.1.0.

https://epr.elastic.co/search?package=ti_opencti&kibana.version=8.13.4

**Comment by SokolSec** [comment]
@andrewkroh 
![image](https://github.com/elastic/integrations/assets/94307667/96a3f512-b9d9-4cc2-82b0-8989fdeee72c)

Yes. Public Elastic Package Registry -> image: docker.elastic.co/kibana/kibana:8.13.4

**Comment by andrewkroh** [comment]
I can't think of any reason the package would not show up if you are on the default public registry. Perhaps the Fleet team has some troubleshooting steps or ideas on this.

**Comment by SokolSec** [comment]
@andrewkroh 
It's a strange situation, I agree! Maybe there are some variables in cabana that are responsible for enabling this integration? The fact is that OpenCTI, as you know, is included in the AWS category, and there is only this integration.... It's very strange. Is it possible to call the fleet team for help?

**Comment by SokolSec** [comment]
Kibana*

**Comment by kpollich** [comment]
Taking a look from the fleet/integrations side of things, I also can't reproduce: 
![image](https://github.com/elastic/integrations/assets/6766512/1f8cea96-205d-49d6-a9fa-3f69d4153b31)

Just checking if case sensitivity is an issue, and no dice there either: 
![image](https://github.com/elastic/integrations/assets/6766512/49005230-a9a1-490a-9cc6-32e01fd767c3)

> Maybe there are some variables in Kibana that are responsible for enabling this integration?

There are few things that can change the visibility of an integration in Kibana:
- The toggle on the bottom left to show beta integrations. Shouldn't impact Open CTI as it's a generally available integration
![image](https://github.com/elastic/integrations/assets/6766512/51c427e0-795a-428e-9edb-890971c68bff)
- The `kibana.version` constraint in an integration. If there's no published version of an integration that targets your Kibana version via its compatibility value, it won't show up in Kibana. This also doesn't apply to Open CTI as the most recent release targets 8.12.0: https://github.com/elastic/integrations/blob/1f780eeb453adb07244c4203e2376ab060f64d6a/packages/ti_opencti/manifest.yml#L12-L14

You can see the most recent published version of the Open CTI integration on EPR here: https://epr.elastic.co/search?package=ti_opencti. 

It would be helpful to double check that you're not configuring a custom registry via `xpack.fleet.registryUrl` in `kibana.yml`, or that there's not a proxy potentially interfering with requests made to https://epr.elastic.co. It sounds like we're pretty confident that we're just hitting EPR with the default behavior, though. 

Next, you could try this API request in Kibana dev tools and see if Open CTI is included in the results:

```
GET kbn:/api/fleet/epm/packages
```

This is the API that the integrations UI queries to populate the integrations grid UI. It essentially wraps the EPR service and adds some cache control and adds capabilities to filter by beta/ga, etc. 

You could also try to install the integration directly via the Fleet API, e.g. 

```
POST kbn:/api/fleet/epm/packages/ti_opencti/2.1.0
```

It'd be interesting to see what the results are for both of these requests. Do we get a 404 for the installation? Does the integration show up in the list API, but something is filtering it out in the UI? Are there any interesting messages in the Kibana logs during the execution of either of these requests? 

Happy to help further - hopefully this gives us a few things to try in an effort diagnose the root cause here!

**Comment by SokolSec** [comment]
@kpollich 
Greetings! Thank you for a very detailed answer and quick help! The problem turned out to be xpack.fleet.registryUrl, I changed to the original address and everything appeared! Thank you very much!

**Comment by kpollich** [comment]
Glad to hear! Thanks for confirming ❤️
